blueprint:
  name: Zigbee2MQTT - Sonoff SNZB-01 Zigbee Wireless Switch
  description: Automate your Sonoff SNZB-01 Zigbee Wireless Switch via Zigbee2MQTT.
  domain: automation
  input:
    device_id:
      name: Sonoff SNZB-01 Zigbee Wireless Switch
      description: Sonoff SNZB-01 Zigbee Wireless Switch to use
      selector:
        device:
          integration: mqtt
          manufacturer: SONOFF
          model: Wireless button (SNZB-01)
    discovery_id:
      name: MQTT discovery id
      description: device id code as discover in mqtt
      selector:
        text:
    single_press:
      name: Single Press
      description: Action to run on single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double Press
      description: Action to run on double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long Press
      description: Action to run on long press (4 seconds)
      default: []
      selector:
        action: {}
  #source_url: https://github.com/AramidX/ha-blueprint/blob/dc4b846bc4dfa8725526606b07c051947bfc9687/blueprints/sonoff/sonoff_snzb01_wireless_switch_z2m.yaml
mode: restart
max_exceeded: silent
variables:
    discovery_id: !input discovery_id 
trigger:
  - platform: device
    domain: mqtt
    device_id: !input device_id
    type: action
    subtype: long
    discovery_id: "{{discovery_id}} action_long"
    id: long
  - platform: device
    domain: mqtt
    device_id: !input device_id
    type: action
    subtype: single
    id: single
    discovery_id: "{{discovery_id}} action_single"
  - platform: device
    domain: mqtt
    device_id: !input device_id
    type: action
    subtype: double
    id: double
    discovery_id: "{{discovery_id}} action_double"
action:
- choose:
  - conditions: 
    - condition: trigger
      id: single
    sequence: !input "single_press"
  - conditions: 
    - condition: trigger
      id: double
    sequence: !input "double_press"
  - conditions: 
    - condition: trigger
      id: long
    sequence: !input "long_press"