
binary_sensor:
  - platform: template
    sensors:
      automower_error:
        friendly_name: Etat Robot tondeuse
        device_class: problem
        value_template: >
            {{ is_state('lawn_mower.gardenbot',['error','unavailable'])}}
          
alert:
  automower:
    name: "Robot tondeuse en erreur"
    message: >
      {%- set mower_id = 'lawn_mower.gardenbot' -%}
      {%- if is_state(mower_id,'error') -%}
      "Robot tondeuse bloqué"
      {%- elif is_state(mower_id,'unavailable') -%}
      "Robot tondeuse indisponible"
      {%- endif -%}
    done_message: >
      "Robot tondeuse de nouveau ok"
    entity_id: binary_sensor.automower_error
    state: "on"   # Optional, 'on' is the default value
    repeat: 720
    can_acknowledge: true  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify
