
sensor:
  - platform: history_stats
    name: Durée filtration piscine 24h
    entity_id: switch.hub_cf4cac
    state: "on"
    type: time
    duration: "24:00:00"
    end: "{{now()}}"


binary_sensor:
  - platform: template
    sensors:
      flipr_data_freshness:
        device_class: problem
        friendly_name: Flipr réception données
        value_template: >
          {{ (now() - (states('sensor.flipr_1a5be6_date_measure')| as_datetime)) > timedelta(hours=12) }}

alert:
  flipr_ph_alert:
    name: "Alerte PH Piscine"
    message: >
      "PH piscine anormal ({{ states('sensor.flipr_1a5be6_ph') }})"
    done_message: >
      "PH piscine de nouveau normal ({{ states('sensor.flipr_1a5be6_ph') }})"
    entity_id: binary_sensor.flipr_1a5be6_ph_status
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify
  flipr_clore_alert:
    name: "Alerte clore Piscine"
    message: >
      "Clore piscine anormal ({{ states('sensor.flipr_1a5be6_chlorine') | round(2)}})"
    done_message: >
      "Clore piscine de nouveau normal ({{ states('sensor.flipr_1a5be6_chlorine') | round(2) }})"
    entity_id: binary_sensor.flipr_1a5be6_chlorine_status
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify
  flipr_disconnected_alert:
    name: "Alerte Flipr déconnecté"
    message: >
      "Flipr déconnecté depuis {{ relative_time((states('sensor.flipr_1a5be6_date_measure')| as_datetime))}}"
    done_message: >
      "Flipr de nouveau connecté"
    entity_id: binary_sensor.flipr_data_freshness
    state: "on"   # Optional, 'on' is the default value
    repeat: 180
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify
  flipr_flitering_alert:
    name: "Alerte Flipr filtration"
    message: >
      "Alerte pas de filtration depuis 24h"
    done_message: >
      "Filtration Flipr de nouveau actif"
    entity_id: sensor.duree_filtration_piscine_24h
    state: 0.0
    repeat: 180
    can_acknowledge: true  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify