
template:
  - binary_sensor:
    - device_class: problem
      default_entity_id: binary_sensor.ico_data_freshness
      name: Ico réception données
      state: >-
        {{ (now() - as_local(states.sensor.plouf_oxydo_reduction_potential.last_changed)) >
           timedelta(hours=12) }}
    - device_class: problem
      default_entity_id: binary_sensor.ico_ph
      name: Ico Ph problem
      state: >-
        {{ ((states('sensor.plouf_ph') | float) < 7.0
            or (states('sensor.plouf_ph') | float) > 7.5)
            and not is_state('input_boolean.piscine_en_hivernage', ['on']) }}
    - device_class: problem
      default_entity_id: binary_sensor.ico_temperature
      name: Ico temperature problem
      state: >-
        {{ ((states('sensor.plouf_temperature') | float) < 26
            or (states('sensor.plouf_temperature') | float) > 34)
            and not is_state('input_boolean.piscine_en_hivernage', ['on']) }}
    - device_class: problem
      default_entity_id: binary_sensor.ico_redox
      name: ico redox problem
      state: >-
        {{ ((states('sensor.plouf_oxydo_reduction_potential') | float) <
            state_attr('sensor.plouf_oxydo_reduction_potential', 'treshold_low')
            or (states('sensor.plouf_oxydo_reduction_potential') | float) >
            state_attr('sensor.plouf_oxydo_reduction_potential', 'treshold_high'))
            and not is_state('input_boolean.piscine_en_hivernage', ['on']) }}
    - device_class: problem
      default_entity_id: binary_sensor.ico_salt
      name: ico salt problem
      state: >-
        {{ ((states('sensor.plouf_salt') | float) < 3000
            or (states('sensor.plouf_salt') | float) > 5000)
            and not is_state('input_boolean.piscine_en_hivernage', ['on']) }}
    - device_class: problem
      default_entity_id: binary_sensor.ico_battery
      name: ico battery problem
      state: >-
        {{ (states('sensor.plouf_batterie') | float) < 15 }}

alert:
  ico_disconnected_alert:
    name: "Alerte Ico déconnecté"
    message: >
      "Ico déconnecté depuis {{ relative_time(states.sensor.plouf_oxydo_reduction_potential.last_changed)}}"
    done_message: >
      "Ico de nouveau connecté"
    entity_id: binary_sensor.ico_data_freshness
    state: "on"   # Optional, 'on' is the default value
    repeat: 180
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify
  ico_battery_alert:
    name: "Alerte Ico pile faible"
    message: >
      "niveau de pile Ico faible {{ states('sensor.plouf_batterie') }}"
    done_message: >
      "Ico à de nouveau des piles"
    entity_id: binary_sensor.ico_battery
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify

homeassistant:
  customize:
   sensor.plouf_oxydo_reduction_potential:
      treshold_low: 650
      treshold_high: 750
