intent_script:
################################################################################
  readyTesla:
    speech:
      text: "Préparation de la voiture en cours."
    action:
      - action: script.integration_tesla_ready_to_leave

script:
################################################################################
  integration_tesla_ready_to_leave:
    alias: Tesla - Préparation au départ
    mode: single
    sequence:
      - action: climate.set_temperature
        data:
          temperature: 23
          hvac_mode: heat_cool
        target:
          entity_id: climate.electromobile_climate
      - action: climate.set_preset_mode
        metadata: {}
        data:
          preset_mode: keep
        target:
          entity_id: climate.electromobile_climate
      - if:
          - condition: numeric_state
            entity_id: sensor.electromobile_temperature_exterieure
            below: 5
        then:
          - action: switch.turn_on
            target:
              entity_id: switch.electromobile_defrost
            data: {}
      - if:
          - condition: state
            entity_id: device_tracker.electromobile_location
            state: home
        then:
          - action: lock.unlock
            target:
              entity_id: lock.electromobile_lock
            data: {}
      - if:
          - condition: state
            entity_id: lock.electromobile_charge_cable_lock
            state: locked
        then:
          - action: lock.unlock
            target:
              entity_id: lock.electromobile_charge_cable_lock
            data: {}
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - binary_sensor.electromobile_user_present
            to: "on"
        continue_on_timeout: true
        timeout:
          hours: 0
          minutes: 10
          seconds: 0
          milliseconds: 0
      - if:
          - condition: template
            value_template: "{{wait.completed}}"
        then:
          - stop: ""
        else:
          - action: switch.turn_off
            target:
              entity_id:
                - switch.electromobile_defrost
            data: {}
          - action: climate.set_preset_mode
            metadata: {}
            data:
              preset_mode: "off"
            target:
              entity_id: climate.electromobile_climate
          - action: climate.set_temperature
            data:
              temperature: 23
              hvac_mode: "off"
            target:
              entity_id: climate.electromobile_climate
          - action: lock.lock
            target:
              entity_id:
                - lock.electromobile_lock
            data: {}


automation:
###############################################
- id: 'integration_tesla_smart_overheat'
  alias: Tesla - Aération intelligente
  mode: single
  triggers:
    - entity_id:
        - sensor.electromobile_temperature_interieure
      above: 40
      id: open_windows
      trigger: numeric_state
    - entity_id:
        - sensor.electromobile_temperature_interieure
      below: 35
      id: close_windows
      trigger: numeric_state
    - entity_id:
        - input_boolean.night_mode
      to: "on"
      id: night_mode
      trigger: state
  conditions:
    - condition: state
      entity_id: device_tracker.electromobile_location
      state: home
    - condition: state
      entity_id: binary_sensor.electromobile_user_present
      state: "off"
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: open_windows
          sequence:
            - action: cover.open_cover
              target:
                entity_id: cover.electromobile_windows
              data: {}
            - condition: state
              state: locked
              entity_id: lock.electromobile_charge_cable_lock
            - action: climate.set_hvac_mode
              target:
                entity_id:
                  - climate.electromobile_cabin_overheat_protection
              data:
                hvac_mode: fan_only
        - conditions:
            - condition: trigger
              id: close_windows
            - condition: state
              state: open
              entity_id: cover.electromobile_windows
          sequence:
            - action: cover.close_cover
              target:
                entity_id: cover.electromobile_windows
              data: {}
            - action: climate.set_hvac_mode
              target:
                entity_id: climate.electromobile_cabin_overheat_protection
              data:
                hvac_mode: "off"
        - conditions:
            - condition: trigger
              id: night_mode
            - condition: state
              state: open
              entity_id: cover.electromobile_windows
          sequence:
            - action: cover.close_cover
              target:
                entity_id: cover.electromobile_windows
              data: {}
            - action: climate.set_hvac_mode
              target:
                entity_id: climate.electromobile_cabin_overheat_protection
              data:
                hvac_mode: "off"
            - action: lock.lock
              metadata: {}
              data: {}
              target:
                entity_id: lock.electromobile_lock
