
automation:
###############################################
- id: Zendur_batterie_low
  alias: Integration - Zendure - Low Batterie
  description: ""
  mode: single
  triggers:
    - trigger: numeric_state
      entity_id:
        - sensor.ace_1500_garage_electric_level
      below: 15
      id: bellow20
    - trigger: numeric_state
      entity_id:
        - sensor.ace_1500_garage_electric_level
      below: 10
      id: bellow10
  conditions: []
  actions:
    - if:
        - condition: state
          entity_id: switch.power_plug_ups_garage_prise_onduleur_garage
          state: "off"
      then:
        - action: switch.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: switch.power_plug_ups_garage_prise_onduleur_garage
      else:
        - action: notify.all_mobile
          metadata: {}
          data:
            message: Niveau batterie garage faible ({{states('sensor.electriclevel')}}%)

- id: Zendur_output_off
  alias: Integration - Zendure - Force output On
  description: Remet le switch sur ON s'il passe à un état autre que ON (hors unavailable/unknown)
  mode: single
  trigger:
    - trigger: state
      entity_id: switch.ace_1500_garage_ac_switch
      not_to:
        - "on"
        - "unavailable"
        - "unknown"

  action:
    - action: switch.turn_on
      target:
        entity_id: switch.ace_1500_garage_ac_switch
