- id: '1618666809324'
  alias: Interagration - Aspirateur - Auto
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'off'
  action:
  - service: xiaomi_miio.vacuum_remote_control_start
    data:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  - service: notify.mobile_seb
    data:
      title: Roomba - Lancement auto
  mode: single
- id: area_salon_bouton
  alias: Area - Salon - Bouton
  description: ''
  use_blueprint:
    path: Jarne_Roussard/aqara-opple-6-buttons-for-zha.yaml
    input:
      remote: 38e094538f2e11349ab8b2b623a978a3
      button_top_left_single_press:
      - service: script.sonos_rdc_ambiance_meditation
      button_top_left_double_press:
      - service: script.sonos_rdc_ambiance_piano
      button_middle_left_single_press:
      - service: script.sonos_rdc_ambiance_pop
      button_middle_left_double_press:
      - service: script.sonos_rdc_ambiance_matin
      button_bottom_left_single_press:
      - service: light.turn_on
        target:
          entity_id: light.salon_lumieres
      button_bottom_right_single_press:
      - service: light.turn_off
        target:
          entity_id: light.salon_lumieres
