
homeassistant:
  packages: !include_dir_named packages
  media_dirs: 
    sounds: /media/sounds
    deepstack: /media/deepstack
  allowlist_external_dirs:
    - '/media/sounds'
    - '/media/deepstack'

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include_dir_merge_named themes


