light:
  - platform: group
    name: buanderie lumieres
    unique_id: buanderie_lumieres
    entities:
      - light.laundry_ceiling_light


automation:
################################################################################
- id: 'buanderie_mashingmachine_end'
  alias: Area - Buanderie - Fin machine à laver
  description: ''
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.washing_machine_plug_end
      from: "off"
      to: "on"
  condition: []
  action:
    - action: notify.mobile_seb
      data:
        message: "la machine à laver a terminé."
  mode: restart

################################################################################
- id: 'buanderie_lumiere_auto'
  alias: Area - Buanderie - Lumière Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.buanderie_lumieres
      adaptive_lighting: switch.adaptive_lighting_default
      motion_sensor: binary_sensor.blumotion_buanderie_motion
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30 
      only_during_night: false
      light_sensor: sensor.blumotion_buanderie_illuminance
      lux_cutoff: 60
      lux_sun_cutoff: 250 
      only_turn_off: false    
      toggle_trigger:
        trigger: state
        entity_id: 
          - binary_sensor.laundry_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle

