automation:
################################################################################
- id: 'buanderie_mashingmachine_end'
  alias: Area - Buanderie - Fin machine à laver
  description: ''
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.washing_machine_plug_end
      from: "off"
      to: "on"
  condition: []
  action:
    - service: notify.mobile_seb
      data:
        message: "la machine à laver a terminé."
  mode: restart

################################################################################


