
binary_sensor:
  - platform: group
    name: "Capteurs mouvement bureau"
    device_class: motion
    unique_id: bureau_motion_sensors #binary_sensor.capteurs_mouvement_bureau
    all: false
    entities:
      - binary_sensor.bureau_capteur_presence_presence
      - binary_sensor.bureau_capteur_mouvement_occupancy
      - binary_sensor.bureau_person_occupancy

sensor:
  - name: mouvement_bureau_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_bureau
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: bureau_light_auto
  alias: Area - Bureau - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.hue_color_lamp_5_3
          - light.barre_led_ecran
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_turn_off: true
      light_sensor:
      lux_cutoff:
################################################################################
