binary_sensor:
  - platform: group
    #binary_sensor.capteurs_mouvement_bureau
    name: "Capteurs mouvement bureau"
    device_class: occupancy
    unique_id: bureau_motion_sensors #binary_sensor.capteurs_mouvement_bureau
    all: false
    entities:
      - binary_sensor.bureau_capteur_presence_presence
      - binary_sensor.bureau_capteur_mouvement_occupancy
      - binary_sensor.bureau_person_occupancy
      - binary_sensor.capteur_presence_bureau_occupancy

light:
  - platform: group
    name: bureau lumieres
    entities:
      - light.hue_color_lamp_5_3
      - light.office_light_switch_l1

sensor:
  - name: mouvement_bureau_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_bureau
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

input_boolean:
  auto_light_kill_switch_bureau:
    name: Lumière mode manuel (bureau)
    icon: mdi:autorenew-off
  meeting_mode:
    name: mode reunion
    icon: mdi:monitor-account

automation:
################################################################################
- id: bureau_light_auto
  alias: Area - Bureau - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.bureau_lumieres
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_during_night: false
      light_sensor: sensor.capteur_presence_bureau_light_sensor
      lux_cutoff: 80
      lux_sun_cutoff: 250
      only_turn_off: false
      kill_switch: input_boolean.auto_light_kill_switch_bureau
################################################################################
- id: 'bureau_couloir_light_hallway'
  alias: Area - Bureau - Lumière couloir
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.office_hallway_light_switch_swipe_right
      touchfield_1: binary_sensor.office_hallway_light_switch_touchfield_1
      touchfield_2: binary_sensor.office_hallway_light_switch_touchfield_2
      long_press: binary_sensor.office_hallway_light_switch_long_press
      multi_touch: binary_sensor.office_hallway_light_switch_multi_touch
      swipe_left: binary_sensor.office_hallway_light_switch_swipe_left
      touchfield_1_action:
        - action: light.toggle
          target:
            entity_id: light.office_light_switch_l2

      swipe_left_action:
        - action: light.turn_on
          data: {}
          target:
            entity_id:
              - light.office_light_switch_l2
        - delay: "00:00:03" 
        - action: light.turn_on
          data: {}
          target:
            entity_id:
              - light.bureau_lumieres
        - delay: "00:00:03"
        - action: light.turn_off
          data: {}
          target:
            entity_id:
              - light.office_light_switch_l2

      multi_touch_action:
        - action: light.turn_off
          target:
            area_id: "{{room}}"
        - action: switch.turn_off
          entity_id: switch.fire_tablet_screen
        - action: script.play_mood_music
          data:
            action: media_stop
            rooms: "{{room}}"
################################################################################
- id: 'bureau_light_switch_entrance'
  alias: Area - Bureau - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.office_light_switch_swipe_right
      touchfield_1: binary_sensor.office_light_switch_touchfield_1
      touchfield_2: binary_sensor.office_light_switch_touchfield_2
      long_press: binary_sensor.office_light_switch_long_press
      multi_touch: binary_sensor.office_light_switch_multi_touch
      swipe_left: binary_sensor.office_light_switch_swipe_left


      multi_touch_action:
        - parallel: 
          - action: light.turn_off
            target:
              area_id: "{{room}}"
          - action: switch.turn_off
            entity_id: switch.fire_tablet_screen
          - action: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"

      swipe_left_action:
        - action: cover.toggle
          target:
            entity_id:
              - cover.store_bureau_droite
              - cover.store_bureau_gauche

      swipe_right_action:
        - action: cover.toggle
          target:
            entity_id:
              - cover.store_bureau_droite
              - cover.store_bureau_gauche
################################################################################
- id: 'bureau_light_switch_desk'
  alias: Area - Bureau - Bouton applique
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.desk_light_switch_swipe_right
      touchfield_1: binary_sensor.desk_light_switch_touchfield_1
      touchfield_2: binary_sensor.desk_light_switch_touchfield_2
      touchfield_3: binary_sensor.desk_light_switch_touchfield_3
      long_press: binary_sensor.desk_light_switch_long_press
      multi_touch: binary_sensor.desk_light_switch_multi_touch
      swipe_left: binary_sensor.desk_light_switch_swipe_left

      touchfield_1_action:
        - action: light.toggle
          target:
            entity_id: light.office_light_switch_l1

      touchfield_2_action:
        - action: light.toggle
          target:
            entity_id: light.hue_color_lamp_5_3

      touchfield_3_action:
        - action: light.toggle
          target:
            entity_id: light.hue_color_lamp_5_3

      multi_touch_action:
        - parallel: 
          - action: light.turn_off
            target:
              area_id: "{{room}}"
          - action: switch.turn_off
            entity_id: switch.fire_tablet_screen
          - action: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"

      swipe_left_action:
        - action: cover.toggle
          target:
            entity_id:
              - cover.store_bureau_droite
              - cover.store_bureau_gauche

      swipe_right_action:
        - action: cover.toggle
          target:
            entity_id:
              - cover.store_bureau_droite
              - cover.store_bureau_gauche
################################################################################
- id: bureau_turn_off
  alias: Area - Bureau - Tout eteindre
  description: ''
  mode: single
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
      for:
        minutes: 5
  condition: []
  action:
    - action: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - media_player.bureau
          - switch.fire_tablet_screen
################################################################################
- id: bureau_heater-auto
  alias: Area - Bureau - Chauffage auto
  description: ""
  mode: single
  trigger:
    - id: presence
      trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "off"
      to: "on"
      for:
        minutes: 5 
    - id: absence
      trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
      for:
        minutes: 5      
    - id: morning
      trigger: time
      at: "08:30:00"
    - id: aurore
      trigger: time
      at: "04:30:00"
      
  condition: []

  action:
    - choose:
        - conditions:
            - condition: trigger
              id: morning
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: state
              entity_id: person.sebastien
              state: home
            - condition: not
              conditions:
              - condition: state
                entity_id: sensor.rte_tempo_prochaine_couleur
                state: Rouge
          sequence:
            - action: climate.set_preset_mode
              data:
                preset_mode: Travail
              target:
                entity_id: climate.mobile_heater_plug_thermostat
            - action: climate.turn_on
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat                
        - conditions:
            - condition: trigger
              id: aurore
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
            - condition: state
              entity_id: person.sebastien
              state: home
            - condition: state
              entity_id: sensor.rte_tempo_prochaine_couleur
              state: Rouge
          sequence:
            - action: climate.set_temperature
              target:
                entity_id: climate.mobile_heater_plug_thermostat
              data:
                temperature: 23
            - action: climate.turn_on
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat
        - conditions:
            - condition: trigger
              id:
                - presence
            - condition: not
              conditions:
              - condition: state
                entity_id: sensor.rte_tempo_prochaine_couleur
                state: Rouge
          sequence:
            - if:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: "on"
              then:
                - action: climate.set_preset_mode
                  data:
                    preset_mode: Travail
                  target:
                    entity_id: climate.mobile_heater_plug_thermostat
              else:
                - action: climate.set_preset_mode
                  data:
                    preset_mode: home
                  target:
                    entity_id: climate.mobile_heater_plug_thermostat
            - action: climate.turn_on
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat
        - conditions:
            - condition: trigger
              id:
                - absence
          sequence:
            - action: climate.turn_off
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat
################################################################################
- id: iron_auto_filter
  alias: Area - Bureau - Fer à souder auto
  description: ""
  mode: single
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
      for:
        hours: 0
        minutes: 5
        seconds: 0
      id: away
    - platform: numeric_state
      entity_id:
        - sensor.office_solder_iron_switch_power
      above: 10
      id: iron_in_use
    - platform: numeric_state
      entity_id:
        - sensor.office_solder_iron_switch_power
      for:
        hours: 0
        minutes: 0
        seconds: 10
      below: 5
      id: iron_not_in_use
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - away
          sequence:
            - action: switch.turn_off
              metadata: {}
              data: {}
              target:
                entity_id:
                  - switch.office_solder_iron_switch_fer_souder
                  - switch.office_solder_fume_filtre_fum_e_soudure
        - conditions:
            - condition: trigger
              id:
                - iron_in_use
          sequence:
            - action: switch.turn_on
              metadata: {}
              data: {}
              target:
                entity_id: switch.office_solder_fume_filtre_fum_e_soudure
        - conditions:
            - condition: trigger
              id:
                - iron_not_in_use
          sequence:
            - action: switch.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: switch.office_solder_fume_filtre_fum_e_soudure
################################################################################
- id: reconnect_ble_desk
  alias: Area - Bureau - Reconnecter bureau Idasen BLE
  description: ""
  mode: single
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      to: "on"
  condition: []
  action:
    - if:
        - condition: state
          entity_id: binary_sensor.idasen_ble_desk_connection
          state: "off"
      then:
        - action: button.press
          metadata: {}
          data: {}
          target:
            entity_id: button.desk_6897_connect
################################################################################
- id: office_meeting_mode
  alias: Area - Bureau - mode réunion
  description: "Manage le mode réunion"
  mode: single
  triggers:
    - trigger: state
      entity_id:
        - input_boolean.meeting_mode
      to: "on"
      id: mode_reunion_on
    - trigger: state
      entity_id:
        - input_boolean.meeting_mode
      to: "off"
      id: mode_reunion_off
    - trigger: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      to: "off"
      id: presence_bureau_off
    - platform: tag
      tag_id: 72-E5-4D-3D
      id: "mode_reunion_toggle"
  conditions: []
  actions:
    - choose:
        - alias: mode_reunion_on
          conditions:
            - condition: trigger
              id:
                - mode_reunion_on
          sequence:
            - action: media_player.media_stop
              metadata: {}
              data: {}
              target:
                area_id: bureau
        - alias: presence_bureau_off
          conditions:
            - condition: trigger
              id:
                - presence_bureau_off
          sequence:
            - action: input_boolean.turn_off
              metadata: {}
              data: {}
              target:
                entity_id: input_boolean.meeting_mode
        - alias: presence_bureau_toggle
          conditions:
            - condition: trigger
              id:
                - mode_reunion_toggle
          sequence:
            - action: input_boolean.toggle
              metadata: {}
              data: {}
              target:
                entity_id: input_boolean.meeting_mode
################################################################################
- id: scan_tag_office
  alias: Area - Bureau - Tag Lapin
  description: "Delanche les actions des lapins"
  mode: single
  triggers:
    - platform: tag
      tag_id: 91-E5-4D-3D
      id: "launch_music"
  conditions: []
  actions:
    - choose:
        - alias: launch_music
          conditions:
            - condition: trigger
              id:
                - launch_music
          sequence:
            - action: script.play_mood_music
              metadata: {}
              data:
                rooms:
                  - bureau
################################################################################
- id: bureau_wled_pc_auto
  alias: Area - Bureau - Barres LED écran auto
  description: 'Allume les barres LED de l''écran quand PC connecté, éteint sur déconnexion ou absence'
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.wled
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      turn_on_trigger:
        trigger: state
        entity_id:
          - binary_sensor.capteur_bureau_pc_connected
        from: ["off"]
        to: ["on"]
        id: turn_on
      turn_off_trigger:
        trigger: state
        entity_id:
          - binary_sensor.capteur_bureau_pc_connected
        from: ["on"]
        to: ["off"]
        id: turn_off
      no_motion_wait:
        minutes: 5
      no_motion_warning: 30
      only_during_night: false
      only_turn_off: true
      kill_switch: input_boolean.auto_light_kill_switch_bureau
################################################################################



script:
################################################################################
  office_door_bell_ring:
    alias: Bureau - Sonnette
    sequence:
      - if:
          - alias: "Si en réunion"
            condition: state
            entity_id: input_boolean.meeting_mode
            state: "off"
        then:
          - action: script.sound_notify
            data:
              media_player_entities:
                - media_player.bureau
              #media_content_id: "media-source://media_source/sounds/bb8_sound.mp3" > sonos doesn't find local url anymore (home.intra.sberard.fr)
              #media_content_id: "https://home.berard.me/http-sounds/bb8_sound.mp3"
              media_content_id: "https://home.berard.me/http-sounds/harrypotter_ringbell.mp3"
        else:
          - action: select.select_option
            metadata: {}
            data:
              option: DoorBell
            target:
              entity_id: select.wled_preset
          - delay:
              seconds: 30
          - action: select.select_option
            metadata: {}
            data:
              option: default
            target:
              entity_id: select.wled_preset








homeassistant:
  customize:
    binary_sensor.capteurs_mouvement_bureau:
      room_main: occupancy
    media_player.fire_tablet:
      room_main: tts

