
binary_sensor:
  - platform: group
    name: "Capteurs mouvement bureau"
    device_class: occupancy
    unique_id: bureau_motion_sensors #binary_sensor.capteurs_mouvement_bureau
    all: false
    entities:
      - binary_sensor.bureau_capteur_presence_presence
      - binary_sensor.bureau_capteur_mouvement_occupancy
      - binary_sensor.bureau_person_occupancy

light:
  - platform: group
    name: bureau lumieres
    entities:
      - light.hue_color_lamp_5_3
      - light.wled
      - light.office_light_switch_l1
      - light.office_light_switch_l2

sensor:
  - name: mouvement_bureau_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_bureau
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: bureau_light_auto
  alias: Area - Bureau - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.bureau_lumieres
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_turn_off: true
      light_sensor:
      lux_cutoff:
################################################################################
- id: bureau_turn_off
  alias: Area - Bureau - Tout eteindre
  description: ''
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
    - platform: state
      entity_id:
        - binary_sensor.office_light_switch_multi_touch
      from: "off"
      to: "on"
  condition: []
  action:
    - service: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - light.bureau_lumieres
          - media_player.bureau
          - switch.fire_tablet_screen

################################################################################
homeassistant:
  customize:
    binary_sensor.capteurs_mouvement_bureau:
      room_main: occupancy
    media_player.fire_tablet:
      room_main: tts

