climate:
  - platform: generic_thermostat
    name: Bureau thermostat
    heater: switch.bureau_prise_1
    target_sensor: sensor.bureau_capteur_temperature_temperature
    hot_tolerance: 0.5
    min_temp: 12
    max_temp: 26
    min_cycle_duration:
      minutes: 2
    keep_alive:
      minutes: 5

binary_sensor:
  - platform: group
    name: "Capteurs mouvement bureau"
    device_class: motion
    unique_id: bureau_motion_sensors #binary_sensor.capteurs_mouvement_bureau
    all: false
    entities:
      - binary_sensor.bureau_capteur_presence_presence_2
      - binary_sensor.bureau_capteur_mouvement_occupancy
      - binary_sensor.bureau_person_motion

template:
  - sensor:
    - unique_id: temperature_bureau
      name: Temperature Bureau
      device_class: temperature
      state: "{{ state_attr('climate.netatmo_bureau', 'current_temperature') }}"

sensor:
  - name: mouvement_bureau_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_bureau
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: bureau_light_auto
  alias: Area - Bureau - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.hue_color_lamp_5_3
          - light.barre_led_ecran
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_turn_off: true
      light_sensor:
      lux_cutoff:
################################################################################
