
binary_sensor:
  - platform: group
    #binary_sensor.capteurs_mouvement_bureau
    name: "Capteurs mouvement bureau"
    device_class: occupancy
    unique_id: bureau_motion_sensors #binary_sensor.capteurs_mouvement_bureau
    all: false
    entities:
      - binary_sensor.bureau_capteur_presence_presence
      - binary_sensor.bureau_capteur_mouvement_occupancy
      - binary_sensor.bureau_person_occupancy

light:
  - platform: group
    name: bureau lumieres
    entities:
      - light.hue_color_lamp_5_3
      - light.wled
      - light.office_light_switch_l1

sensor:
  - name: mouvement_bureau_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_bureau
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: bureau_light_auto
  alias: Area - Bureau - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id:
          - light.bureau_lumieres
      motion_sensor: binary_sensor.capteurs_mouvement_bureau
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_turn_off: true
      light_sensor:
      lux_cutoff:

################################################################################
- id: 'bureau_couloir_light_hallway'
  alias: Area - Bureau - Lumière couloir
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.office_hallway_light_switch_swipe_right
      touchfield_1: binary_sensor.office_hallway_light_switch_touchfield_1
      touchfield_2: binary_sensor.office_hallway_light_switch_touchfield_2
      long_press: binary_sensor.office_hallway_light_switch_long_press
      multi_touch: binary_sensor.office_hallway_light_switch_multi_touch
      swipe_left: binary_sensor.office_hallway_light_switch_swipe_left
      touchfield_1_action:
        - service: light.toggle
          target:
            entity_id: light.office_light_switch_l2

      swipe_left_action:
        - service: light.turn_on
          data: {}
          target:
            entity_id:
              - light.office_light_switch_l2
        - delay: "00:00:03" 
        - service: light.turn_on
          data: {}
          target:
            entity_id:
              - light.bureau_lumieres
        - delay: "00:00:03"
        - service: light.turn_off
          data: {}
          target:
            entity_id:
              - light.office_light_switch_l2

      multi_touch_action:
        - service: light.turn_off
          target:
            area_id: "{{room}}"
        - service: switch.turn_off
          entity_id: witch.fire_tablet_screen
        - service: script.play_mood_music
          data:
            action: media_stop
            rooms: "{{room}}"
################################################################################
- id: 'bureau_light_switch_entrance'
  alias: Area - Bureau - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.office_light_switch_swipe_right
      touchfield_1: binary_sensor.office_light_switch_touchfield_1
      touchfield_2: binary_sensor.office_light_switch_touchfield_2
      long_press: binary_sensor.office_light_switch_long_press
      multi_touch: binary_sensor.office_light_switch_multi_touch
      swipe_left: binary_sensor.office_light_switch_swipe_left


      multi_touch_action:
        - parallel: 
          - service: light.turn_off
            target:
              area_id: "{{room}}"
          - service: switch.turn_off
            entity_id: witch.fire_tablet_screen
          - service: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"
################################################################################
- id: 'bureau_light_switch_desk'
  alias: Area - Bureau - Bouton applique
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.desk_light_switch_swipe_right
      touchfield_1: binary_sensor.desk_light_switch_touchfield_1
      touchfield_2: binary_sensor.desk_light_switch_touchfield_2
      long_press: binary_sensor.desk_light_switch_long_press
      multi_touch: binary_sensor.desk_light_switch_multi_touch
      swipe_left: binary_sensor.desk_light_switch_swipe_left

      multi_touch_action:
        - parallel: 
          - service: light.turn_off
            target:
              area_id: "{{room}}"
          - service: switch.turn_off
            entity_id: witch.fire_tablet_screen
          - service: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"
################################################################################
- id: bureau_turn_off
  alias: Area - Bureau - Tout eteindre
  description: ''
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
      for:
        minutes: 5
  condition: []
  action:
    - service: homeassistant.turn_off
      data: {}
      target:
        entity_id:
          - media_player.bureau
          - switch.fire_tablet_screen
################################################################################
- id: bureau_heater-auto
  alias: Area - Bureau - Chauffage auto
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "off"
      to: "on"
      for:
        minutes: 5
      id: presence
    - platform: state
      entity_id:
        - binary_sensor.capteurs_mouvement_bureau
      from: "on"
      to: "off"
      for:
        minutes: 5
      id: absence
    - platform: time
      at: "08:30:00"
      id: morning
  condition:
    - condition: or
      conditions:
        - condition: trigger
          id:
            - presence
            - absence
        - condition: and
          conditions:
            - condition: state
              entity_id: person.sebastien
              state: home
            - condition: trigger
              id:
                - morning
            - condition: state
              entity_id: binary_sensor.workday_sensor
              state: "on"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id:
                - presence
                - morning
          sequence:
            - if:
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: "on"
              then:
                - service: climate.set_preset_mode
                  data:
                    preset_mode: Travail
                  target:
                    entity_id: climate.mobile_heater_plug_thermostat
              else:
                - service: climate.set_preset_mode
                  data:
                    preset_mode: home
                  target:
                    entity_id: climate.mobile_heater_plug_thermostat
            - service: climate.turn_on
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat
        - conditions:
            - condition: trigger
              id:
                - absence
          sequence:
            - service: climate.turn_off
              data: {}
              target:
                entity_id: climate.mobile_heater_plug_thermostat
################################################################################




homeassistant:
  customize:
    binary_sensor.capteurs_mouvement_bureau:
      room_main: occupancy
    media_player.fire_tablet:
      room_main: tts

