
automation:
################################################################################
- id: cars_polo_bouton_portails
  alias: Area - Voiture - Bonton portails Polo
  description: ""
  use_blueprint:
    path: antorfr/BluButtonRC1.yaml
    input:
      button_device: 77b6d1f9d19be9f69ebf967df0d893b7
      button_short:
        - action: cover.toggle
          metadata: {}
          data: {}
          target:
            entity_id: cover.portail_2
      button_double:
        - action: cover.toggle
          metadata: {}
          data: {}
          target:
            entity_id: cover.garage_1
      button_triple:
        - action: cover.toggle
          metadata: {}
          data: {}
          target:
            entity_id: cover.garage_2
      button_long:
        - action: input_boolean.turn_on
          target:
            entity_id: input_boolean.away_mode
################################################################################