
light:
  - platform: group
    name: Chambre parents lumieres
    entities:
      - light.chambre
      - light.veilleuse_lit_parent

automation:
################################################################################
- id: 'chambre_parent_button_seb'
  alias: Area - Chambre - Bouton lit Sébastien
  description: ''
  use_blueprint:
    path: garykrige/zha-sonoff-zigbee-switch.yaml
    input:
      sonoff_button: 00885357a5b4e685c3ea692c95e4db63
      toggle_action:
      - type: toggle
        device_id: e9d42fb1963c8eb9bdee7c45834230b8
        entity_id: light.plafonnier_chambre_parents
        domain: light
      off_action:
      - service: switch.turn_on
        target:
          entity_id: switch.night_mode
      on_action:
      - service: switch.toggle
        data: {}
        entity_id: switch.couverture_seb
################################################################################
