template:
  - sensor:
    - unique_id: temperature_chambre_emilie
      name: Chambre Émilie temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.netatmo_chambre_emilie', 'current_temperature')|float }}"

input_boolean:
  curfew_emilie:
    name: Couvre feu Émilie
    icon: bha:night-light

automation:
################################################################################
- id: 'chambre_emilie_prise_moustique'
  alias: Area - Chambre Emilie - Prise anti-moustique
  description: ''
  trigger: 
    platform: time_pattern
    hours: '/2'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: "person.emilie"
          state: "home"
        - condition: time
          after: '20:00:00'
          before: '06:00:00'
  action:
  - entity_id:  switch.chambre_emilie_prise_bureau
    service: switch.turn_on
  - delay: 00:45:00
  - entity_id: switch.chambre_emilie_prise_bureau
    service: switch.turn_off
################################################################################
- id: 'chambre_emilie_bouton_lumiere'
  alias: Area - Chambre Émilie - Bouton Lumière
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.chambre_emilie_plafonnier
      adaptive_lighting: switch.adaptive_lighting_chambre_emilie
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        platform: state
        entity_id: binary_sensor.emilie_entrance_switch_touchfield_3
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_emilie_button_lit'
  alias: Area - Chambre Émilie - Bouton lit
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: 23afcee06ee96560d15972e61663763b
      type: toggle
      subtype: 'toggle'
      discovery_id: 0x0004740000890033 action_toggle
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.chambre_emilie_plafonnier
################################################################################
- id: 'chambre_emilie_music_curfew'
  alias: Area - Chambre Émilie - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.emilie
      input_target: input_boolean.curfew_emilie
################################################################################
- id: 'chambre_emilie_light_switch'
  alias: Area - Chambre Émilie - Bouton
  description: ''
  trigger:
  - platform: state
    entity_id: 
      - binary_sensor.emilie_entrance_switch_long_press
    from: ["off"]
    to: ["on"]
    id: long_press
  - platform: state
    entity_id: 
      - binary_sensor.emilie_entrance_switch_touchfield_2
    from: ["off"]
    to: ["on"]
    id: touchfield_2
  - platform: state
    entity_id: 
      - binary_sensor.emilie_entrance_switch_touchfield_1
    from: ["off"]
    to: ["on"]
    id: touchfield_1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: long_press
      sequence:
      - if: 
          - condition: state
            entity_id:
              - media_player.emilie
            state:
              - playing
        then:
          - service: media_player.media_stop
            entity_id:
              - media_player.emilie
        else:
          - service: script.play_mood_music
            data:
              rooms:
                - chambre_emilie
    - conditions:
      - condition: trigger
        id: touchfield_2
      sequence:
        - service: cover.toggle
          entity_id: cover.chambre_emilie_volet_roulant
    - conditions:
      - condition: trigger
        id: touchfield_1
      sequence:
        - service: light.toggle
          entity_id: light.horloge_emilie
    default: []
  mode: parallel

