
light:
  - platform: group
    unique_id: timothee_lumieres
    name: Lumieres Timothée
    entities:
      - light.ceiling_light_timothee_plafonnier_timoth_e
      - light.veilleuse_timothee
      - light.timothee_bed_light_lumi_res_lit_timoth_e
      - light.daynight_light_cadre_lumineux_timoth_e

input_boolean:
  curfew_timothee:
    name: Couvre feu Timothée
    icon: bha:night-light


automation:
################################################################################
- id: 'chambre_timothee_button_lit'
  alias: Area - Chambre Timothée - Bouton lit
  description: ''
  use_blueprint:
    path: antorfr/BluButtonRC4.yaml
    input:
      button_device: 221cf9f74ef0916bcdff574a0f9be521
      button_1_short:
        - action: light.toggle
          data: {}
          target:
            entity_id: light.ceiling_light_timothee_plafonnier_timoth_e
      button_3_short:
        - action: cover.toggle
          target:
            area_id: chambre_timothee
          data: {}
      button_2_short:
        - action: select.select_option
          target:
            entity_id: select.display_mode
          data:
            option: Clock
        - action: light.toggle
          target:
            entity_id: light.led_matrix
          data: {}
      button_4_short:
        - if:
            - condition: state
              entity_id: media_player.timothee
              state: playing
          then:
            - action: media_player.media_play_pause
              metadata: {}
              data: {}
              target:
                entity_id: media_player.timothee
          else:
            - action: script.chambre_timothee_music_douce
              metadata: {}
              data: {}
################################################################################
- id: 'chambre_timothee_lumiere_auto'
  alias: Area - Chambre Timothée - Lumière Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.ceiling_light_timothee_plafonnier_timoth_e
      adaptive_lighting: switch.adaptive_lighting_chambre_timothee
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        trigger: state
        entity_id: 
          - binary_sensor.timothee_bed_switch_touchfield_1
          - binary_sensor.timothee_entrance_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_timothee_lumiere_auto_lit'
  alias: Area - Chambre Timothée - Lumière lit Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.timothee_bed_light_lumi_res_lit_timoth_e
      adaptive_lighting: switch.adaptive_lighting_chambre_timothee
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        trigger: state
        entity_id: 
          - binary_sensor.timothee_bed_switch_touchfield_2
          - binary_sensor.timothee_entrance_switch_touchfield_2
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_timothee_light_switch_bed'
  alias: Area - Chambre Timothée - Bouton lit
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.timothee_bed_switch_swipe_right
      touchfield_1: binary_sensor.timothee_bed_switch_touchfield_1
      touchfield_2: binary_sensor.timothee_bed_switch_touchfield_2
      long_press: binary_sensor.timothee_bed_switch_long_press
      multi_touch: binary_sensor.timothee_bed_switch_multi_touch
      swipe_left: binary_sensor.timothee_bed_switch_swipe_left
      swipe_right_action:
        - action: cover.toggle
          target:
            area_id: chambre_timothee
      swipe_left_action:
        - action: cover.toggle
          target:
            area_id: chambre_timothee
################################################################################
- id: 'chambre_timothee_light_switch_entrance'
  alias: Area - Chambre Timothée - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.timothee_entrance_switch_swipe_right
      touchfield_1: binary_sensor.timothee_entrance_switch_touchfield_1
      touchfield_2: binary_sensor.timothee_entrance_switch_touchfield_2
      touchfield_3: binary_sensor.timothee_entrance_switch_touchfield_3
      long_press: binary_sensor.timothee_entrance_switch_long_press
      multi_touch: binary_sensor.timothee_entrance_switch_multi_touch
      swipe_left: binary_sensor.timothee_entrance_switch_swipe_left 
      touchfield_3_action:
        - action: light.toggle
          target:
            entity_id: light.led_matrix
        - action: select.select_option
          target:
            entity_id: select.display_mode
          data:
            option: Clock
      swipe_right_action:
        - action: cover.toggle
          target:
            area_id: chambre_timothee
      swipe_left_action:
        - action: cover.toggle
          target:
            area_id: chambre_timothee
################################################################################
- id: 'chambre_timothee_party_mode'
  alias: Area - Chambre Timothée - Mode fête
  description: "Chambre Timothée - Mode fête"
  trigger:
    - platform: tag
      tag_id: 53-10-D0-D6-60-00-01
  condition: []
  action:
    - action: tts.cloud_say
      data:
        entity_id: media_player.timothee
        message: Super, c'est la fête !
        cache: true
    - action: light.turn_on
      data:
        effect: Color Wipe
        brightness_pct: 100
      target:
        entity_id: light.timothee_bed_light_lumi_res_lit_timoth_e
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - action: script.play_mood_music
      data:
        rooms:
          - chambre_timothee
        title: Lolirock
  mode: single
################################################################################
- id: 'chambre_timothee_music_curfew'
  alias: Area - Chambre Timothée - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.timothee
      input_target: input_boolean.curfew_timothee

script:
################################################################################
  chambre_timothee_music_douce:
    alias: Chambre Timothée - Musique douce
    mode: restart
    icon: mdi:playlist-music
    use_blueprint:
      path: antorfr/music_soft_curfew_ma.yaml
      input:
        room: chambre_timothee
        media_id: spotify:playlist:14TCh5wWTPpF2C3RuRTPX9
        duration: "00:20:00"