
light:
  - platform: group
    unique_id: timothee_lumieres
    name: Lumieres Timothée
    entities:
      - light.plafond_timothee
      - light.veilleuse_timothee
      - light.timothee_bed_light_lumi_res_lit_timoth_e
      - light.daynight_light_cadre_lumineux_timoth_e

input_boolean:
  curfew_timothee:
    name: Couvre feu Timothée
    icon: bha:night-light


automation:
################################################################################
- id: 'chambre_timothee_lumiere_auto'
  alias: Area - Chambre Timothée - Lumière Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.plafond_timothee
      adaptive_lighting: switch.adaptive_lighting_chambre_timothee
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.timothee_bed_switch_touchfield_1
          - binary_sensor.timothee_entrance_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_timothee_lumiere_auto_lit'
  alias: Area - Chambre Timothée - Lumière lit Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.timothee_bed_light_lumi_res_lit_timoth_e
      adaptive_lighting: switch.adaptive_lighting_chambre_timothee
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.timothee_bed_switch_touchfield_2
          - binary_sensor.timothee_entrance_switch_touchfield_2
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_timothee_light_switch_bed'
  alias: Area - Chambre Timothée - Bouton lit
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.timothee_bed_switch_swipe_right
      touchfield_1: binary_sensor.timothee_bed_switch_touchfield_1
      touchfield_2: binary_sensor.timothee_bed_switch_touchfield_2
      long_press: binary_sensor.timothee_bed_switch_long_press
      multi_touch: binary_sensor.timothee_bed_switch_multi_touch
      swipe_left: binary_sensor.timothee_bed_switch_swipe_left

################################################################################
- id: 'chambre_timothee_light_switch_entrance'
  alias: Area - Chambre Timothée - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.timothee_entrance_switch_swipe_right
      touchfield_1: binary_sensor.timothee_entrance_switch_touchfield_1
      touchfield_2: binary_sensor.timothee_entrance_switch_touchfield_2
      touchfield_3: binary_sensor.timothee_entrance_switch_touchfield_3
      long_press: binary_sensor.timothee_entrance_switch_long_press
      multi_touch: binary_sensor.timothee_entrance_switch_multi_touch
      swipe_left: binary_sensor.timothee_entrance_switch_swipe_left 
      touchfield_3_action:
        - service: light.toggle
          target:
            entity_id: light.led_matrix
        - service: select.select_option
          target:
            entity_id: select.display_mode
          data:
            option: Clock

################################################################################
- id: 'chambre_timothee_button_volet'
  alias: Area - Chambre Timothée - Bouton volets
  description: ''
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: ff76dd5000f655268be400dc3d22cf31
      type: action
      subtype: open
      discovery_id: 0x0004740000ad983d action_open
      id: open
    - platform: device
      domain: mqtt
      device_id: ff76dd5000f655268be400dc3d22cf31
      type: action
      subtype: close
      discovery_id: 0x0004740000ad983d action_close
      id: close
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: open
          sequence:
            - service: cover.open_cover
              data: {}
              target:
                area_id: chambre_timothee
        - conditions:
            - condition: trigger
              id: close
          sequence:
            - service: cover.close_cover
              data: {}
              target:
                area_id: chambre_timothee
      default: []
################################################################################
- id: 'chambre_timothee_party_mode'
  alias: Area - Chambre Timothée - Mode fête
  description: "Chambre Timothée - Mode fête"
  trigger:
    - platform: tag
      tag_id: 53-4F-E4-D7-60-00-01
  condition: []
  action:
    - service: tts.cloud_say
      data:
        entity_id: media_player.timothee
        message: Super, c'est la fête !
        cache: true
    - service: light.turn_on
      data:
        effect: Color Wipe
        brightness_pct: 100
      target:
        entity_id: light.timothee_bed_light_lumi_res_lit_timoth_e
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: script.play_mood_music
      data:
        rooms:
          - chambre_timothee
        title: Lolirock
  mode: single
################################################################################
- id: 'chambre_timothee_music_curfew'
  alias: Area - Chambre Timothée - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.timothee
      input_target: input_boolean.curfew_timothee