climate:
  - platform: generic_thermostat
    name: Chambre parent thermostat
    heater: switch.radiateur_mobile
    target_sensor: sensor.chambre_parents_capteur_temperature_temperature
    hot_tolerance: 0.5
    min_temp: 12
    max_temp: 28
    min_cycle_duration:
      minutes: 2
    keep_alive:
      minutes: 5

binary_sensor:
  - platform: group
    name: "Capteurs mouvement chambre parents"
    device_class: motion
    unique_id: chambre_parents_motion_sensors
    all: false
    entities:
      - binary_sensor.chambre_parent_capteur_presence_lit_presence
      - binary_sensor.presence_lit



light:
  - platform: group
    name: Chambre parents lumieres
    entities:
      - light.chambre
      - light.veilleuse_lit_parent
      - light.chambre_parent_coeur_ardent

template:
  - binary_sensor:
    - unique_id: withing_bed_presence_1
      name: Presence lit
      device_class: occupancy
      state: "{{ is_state('input_boolean.withing_bed_presence_1', 'on') }}"

automation:
################################################################################
- id: 'chambre_parent_button_seb'
  alias: Area - Chambre - Bouton lit Sébastien
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_single
      discovery_id: 0x84fd27fffe849e6c action_1_single
      id: action_1_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_double
      discovery_id: 0x84fd27fffe849e6c action_1_double
      id: action_1_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_hold
      discovery_id: 0x84fd27fffe849e6c action_1_hold
      id: action_1_hold
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_single
      discovery_id: 0x84fd27fffe849e6c action_2_single
      id: action_2_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_double
      discovery_id: 0x84fd27fffe849e6c action_2_double
      id: action_2_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_hold
      discovery_id: 0x84fd27fffe849e6c action_2_hold
      id: action_2_hold
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 3_single
      discovery_id: 0x84fd27fffe849e6c action_3_single
      id: action_3_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_single
      discovery_id: 0x84fd27fffe849e6c action_4_single
      id: action_4_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_double
      discovery_id: 0x84fd27fffe849e6c action_4_double
      id: action_4_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_hold
      discovery_id: 0x84fd27fffe849e6c action_4_hold
      id: action_4_hold
  condition: []
  action:
  - choose:
    - conditions: 
      - condition: trigger
        id: action_1_single
      sequence:
        - service: light.toggle
          target:
            entity_id: light.chambre
    - conditions: 
      - condition: trigger
        id: action_1_double
      sequence:
        - service: script.routine_night_all_light_turn_off
    - conditions: 
      - condition: trigger
        id: action_1_hold
      sequence:
        - choose:
          - conditions:
            - condition: time
              after: '05:00:00'
              before: '19:00:00'
            sequence:
            - service: input_boolean.turn_off
              data: {}
              target:
                entity_id: input_boolean.night_mode
          default:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.night_mode
    - conditions: 
      - condition: trigger
        id: action_2_single
      sequence:
        - service: light.toggle
          target:
            entity_id: light.veilleuse_lit_parent
          data:
            brightness_pct: 100
            effect: autoPlay
            color_name: white
    - conditions: 
      - condition: trigger
        id: action_2_double
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_lit_parent
          data:
            color_name: red
            effect: color
            brightness_pct: 50
    - conditions: 
      - condition: trigger
        id: action_2_hold
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_lit_parent
          data:
            color_name: red
            effect: color
            brightness_pct: 8
    - conditions: 
      - condition: trigger
        id: action_3_single
      sequence:
        - service: cover.toggle
          target:
            area_id: chambre_parent
    - conditions: 
      - condition: trigger
        id: action_4_single
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 15
              entity: switch.couverture_seb
    - conditions: 
      - condition: trigger
        id: action_4_double
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 30
              entity: switch.couverture_seb
    - conditions: 
      - condition: trigger
        id: action_4_hold
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: switch.toggle
          data: {}
          entity_id: switch.couverture_seb

################################################################################
- id: 'chambre_parent_button_low'
  alias: Area - Chambre - Bouton lit Laurine
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_single
      discovery_id: 0x60a423fffefbc33d action_1_single
      id: action_1_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_double
      discovery_id: 0x60a423fffefbc33d action_1_double
      id: action_1_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_hold
      discovery_id: 0x60a423fffefbc33d action_1_hold
      id: action_1_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_single
      discovery_id: 0x60a423fffefbc33d action_2_single
      id: action_2_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_double
      discovery_id: 0x60a423fffefbc33d action_2_double
      id: action_2_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_hold
      discovery_id: 0x60a423fffefbc33d action_2_hold
      id: action_2_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_single
      discovery_id: 0x60a423fffefbc33d action_3_single
      id: action_3_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_double
      discovery_id: 0x60a423fffefbc33d action_3_double
      id: action_3_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_hold
      discovery_id: 0x60a423fffefbc33d action_3_hold
      id: action_3_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 4_single
      discovery_id: 0x60a423fffefbc33d action_4_single
      id: action_4_single
  condition: []
  action:
  - choose:
    - conditions: 
      - condition: trigger
        id: action_2_single
      sequence:
        - service: light.toggle
          target:
            entity_id: light.chambre
    - conditions: 
      - condition: trigger
        id: action_2_double
      sequence:
        - service: script.routine_night_all_light_turn_off
    - conditions: 
      - condition: trigger
        id: action_2_hold
      sequence:
        - choose:
          - conditions:
            - condition: time
              after: '05:00:00'
              before: '19:00:00'
            sequence:
            - service: input_boolean.turn_off
              data: {}
              target:
                entity_id: input_boolean.night_mode
          default:
          - service: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.night_mode
    - conditions: 
      - condition: trigger
        id: action_1_single
      sequence:
        - service: light.toggle
          target:
            entity_id: light.veilleuse_lit_parent
          data:
            brightness_pct: 100
            effect: autoPlay
            color_name: white
    - conditions: 
      - condition: trigger
        id: action_1_double
      sequence:
        - service: light.turn_on
          target:
            entity_id:
              - light.veilleuse_lit_parent
          data:
            color_name: red
            effect: color
            brightness_pct: 50
    - conditions: 
      - condition: trigger
        id: action_1_hold
      sequence:
        - service: light.turn_on
          target:
            entity_id:
              - light.veilleuse_lit_parent
          data:
            color_name: red
            effect: color
            brightness_pct: 8
    - conditions: 
      - condition: trigger
        id: action_4_single
      sequence:
        - service: cover.toggle
          target:
            area_id: chambre_parent
    - conditions: 
      - condition: trigger
        id: action_3_single
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 15
              entity: switch.couverture_laurine
    - conditions: 
      - condition: trigger
        id: action_3_double
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 30
              entity: switch.couverture_laurine
    - conditions: 
      - condition: trigger
        id: action_3_hold
      sequence:
        - service: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - service: switch.toggle
          data: {}
          entity_id: switch.couverture_laurine
################################################################################
- id: 'chambre_parent_coeur_auto'
  alias: Area - Chambre - Coeur auto
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.chambre_parent_capteur_presence_lit_presence
      from: "off"
      to: "on"
      id: presence
    - platform: state
      entity_id:
        - binary_sensor.chambre_parent_capteur_presence_lit_presence
      from: "on"
      to: "off"
      id: absence
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: "off"
    - condition: state
      entity_id: input_boolean.away_mode
      state: "off"
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: presence
          sequence:
            - service: light.turn_on
              data:
                rgb_color: [255, 0, 0]
                brightness_pct: 42
              target:
                entity_id: light.chambre_parent_coeur_ardent
            - service: light.turn_on
              data:
                rgb_color: [0, 0, 255]
                brightness_pct: 100
                effect: Twinkle
              target:
                entity_id: light.chambre_parent_coeur_ardent_ambiance
        - conditions:
            - condition: trigger
              id: absence
          sequence:
            - service: light.turn_off
              data: {}
              target:
                entity_id:
                  - light.chambre_parent_coeur_ardent
                  - light.chambre_parent_coeur_ardent_ambiance
