
binary_sensor:
  - platform: group
    name: "Presence lit chambre parents"
    device_class: occupancy
    unique_id: chambre_parents_bed_sensors
    all: false
    entities:
      - binary_sensor.smart_bed_parent_presence_droite
      - binary_sensor.smart_bed_parent_presence_gauche
      - binary_sensor.presence_lit

  - platform: group
    name: "Capteurs mouvement chambre parents"
    device_class: occupancy
    unique_id: chambre_parents_motion_sensors
    all: false
    entities:
      - binary_sensor.smart_bed_parent_mouvement_droite
      - binary_sensor.smart_bed_parent_mouvement_gauche
      - binary_sensor.smart_bed_parent_presence_droite
      - binary_sensor.smart_bed_parent_presence_gauche
      - binary_sensor.smart_bed_parent_moving_target
      
light:
  - platform: group
    name: Chambre parents lumieres
    entities:
      - light.chambre
      - light.parent_bed_light
      - light.chambre_parent_coeur_ardent
      - light.smart_bed_parent_lumi_re_gauche

template:
  - binary_sensor:
    - unique_id: withing_bed_presence_1
      name: Presence lit
      device_class: occupancy
      state: "{{ is_state('input_boolean.withing_bed_presence_1', 'on') }}"

input_boolean:
  auto_light_kill_switch_chambre_parent:
    name: Lumière mode manuel (chambre parent)
    initial: false
    icon: mdi:autorenew-off

automation:
################################################################################
- id: 'chambre_parent_button_seb'
  alias: Area - Chambre - Bouton lit Sébastien
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_single
      discovery_id: 0x84fd27fffe849e6c action_1_single
      id: action_1_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_double
      discovery_id: 0x84fd27fffe849e6c action_1_double
      id: action_1_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 1_hold
      discovery_id: 0x84fd27fffe849e6c action_1_hold
      id: action_1_hold
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_single
      discovery_id: 0x84fd27fffe849e6c action_2_single
      id: action_2_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_double
      discovery_id: 0x84fd27fffe849e6c action_2_double
      id: action_2_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 2_hold
      discovery_id: 0x84fd27fffe849e6c action_2_hold
      id: action_2_hold
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 3_single
      discovery_id: 0x84fd27fffe849e6c action_3_single
      id: action_3_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_single
      discovery_id: 0x84fd27fffe849e6c action_4_single
      id: action_4_single
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_double
      discovery_id: 0x84fd27fffe849e6c action_4_double
      id: action_4_double
    - platform: device
      domain: mqtt
      device_id: b65a33ba24ff394bf8586fa47f15177c
      type: action
      subtype: 4_hold
      discovery_id: 0x84fd27fffe849e6c action_4_hold
      id: action_4_hold
  condition: []
  action:
  - choose:
    - conditions: 
      - condition: trigger
        id: action_1_single
      sequence:
        - action: light.toggle
          target:
            entity_id: light.chambre
    - conditions: 
      - condition: trigger
        id: action_1_double
      sequence:
        - action: script.routine_night_all_light_turn_off
    - conditions: 
      - condition: trigger
        id: action_1_hold
      sequence:
        - choose:
          - conditions:
            - condition: time
              after: '05:00:00'
              before: '19:00:00'
            sequence:
            - action: input_boolean.turn_off
              data: {}
              target:
                entity_id: input_boolean.night_mode
          default:
          - action: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.night_mode
    - conditions: 
      - condition: trigger
        id: action_2_single
      sequence:
        - action: light.toggle
          target:
            entity_id: light.parent_bed_light
    - conditions: 
      - condition: trigger
        id: action_2_double
      sequence:
        - action: light.turn_on
          target:
            entity_id: light.parent_bed_light
          data:
            color_name: red
            effect: color
            brightness_pct: 50
    - conditions: 
      - condition: trigger
        id: action_2_hold
      sequence:
        - action: light.turn_on
          target:
            entity_id: light.parent_bed_light
          data:
            color_name: red
            effect: color
            brightness_pct: 8
    - conditions: 
      - condition: trigger
        id: action_3_single
      sequence:
        - action: cover.toggle
          target:
            area_id: chambre_parent
    - conditions: 
      - condition: trigger
        id: action_4_single
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 15
              entity: switch.couverture_seb
    - conditions: 
      - condition: trigger
        id: action_4_double
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 30
              entity: switch.couverture_seb
    - conditions: 
      - condition: trigger
        id: action_4_hold
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: switch.toggle
          data: {}
          entity_id: switch.couverture_seb

################################################################################
- id: 'chambre_parent_button_low'
  alias: Area - Chambre - Bouton lit Laurine
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_single
      discovery_id: 0x60a423fffefbc33d action_1_single
      id: action_1_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_double
      discovery_id: 0x60a423fffefbc33d action_1_double
      id: action_1_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 1_hold
      discovery_id: 0x60a423fffefbc33d action_1_hold
      id: action_1_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_single
      discovery_id: 0x60a423fffefbc33d action_2_single
      id: action_2_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_double
      discovery_id: 0x60a423fffefbc33d action_2_double
      id: action_2_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 2_hold
      discovery_id: 0x60a423fffefbc33d action_2_hold
      id: action_2_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_single
      discovery_id: 0x60a423fffefbc33d action_3_single
      id: action_3_single
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_double
      discovery_id: 0x60a423fffefbc33d action_3_double
      id: action_3_double
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 3_hold
      discovery_id: 0x60a423fffefbc33d action_3_hold
      id: action_3_hold
    - platform: device
      domain: mqtt
      device_id: 704f5c1ef5a473ba50b11b5730e36ba3
      type: action
      subtype: 4_single
      discovery_id: 0x60a423fffefbc33d action_4_single
      id: action_4_single
  condition: []
  action:
  - choose:
    - conditions: 
      - condition: trigger
        id: action_2_single
      sequence:
        - action: light.toggle
          target:
            entity_id: light.chambre
    - conditions: 
      - condition: trigger
        id: action_2_double
      sequence:
        - action: script.routine_night_all_light_turn_off
    - conditions: 
      - condition: trigger
        id: action_2_hold
      sequence:
        - choose:
          - conditions:
            - condition: time
              after: '05:00:00'
              before: '19:00:00'
            sequence:
            - action: input_boolean.turn_off
              data: {}
              target:
                entity_id: input_boolean.night_mode
          default:
          - action: input_boolean.turn_on
            data: {}
            target:
              entity_id: input_boolean.night_mode
    - conditions: 
      - condition: trigger
        id: action_1_single
      sequence:
        - action: light.toggle
          target:
            entity_id: light.parent_bed_light
          data:
            brightness_pct: 100
            effect: autoPlay
            color_name: white
    - conditions: 
      - condition: trigger
        id: action_1_double
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.parent_bed_light
          data:
            color_name: red
            effect: color
            brightness_pct: 50
    - conditions: 
      - condition: trigger
        id: action_1_hold
      sequence:
        - action: light.turn_on
          target:
            entity_id:
              - light.parent_bed_light
          data:
            color_name: red
            effect: color
            brightness_pct: 8
    - conditions: 
      - condition: trigger
        id: action_4_single
      sequence:
        - action: cover.toggle
          target:
            area_id: chambre_parent
    - conditions: 
      - condition: trigger
        id: action_3_single
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 15
              entity: switch.couverture_laurine
    - conditions: 
      - condition: trigger
        id: action_3_double
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: script.turn_on
          target:
            entity_id: script.on_off_tempo
          data:
            variables:
              minutes: 30
              entity: switch.couverture_laurine
    - conditions: 
      - condition: trigger
        id: action_3_hold
      sequence:
        - action: script.turn_off
          target:
            entity_id: script.on_off_tempo
        - action: switch.toggle
          data: {}
          entity_id: switch.couverture_laurine

################################################################################  
- id: chambre_parent_bed_light_auto_left
  alias: Area - Chambre parent - Lumière lit auto gauche
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.smart_bed_parent_lumi_re_gauche
      motion_sensor: 
        - binary_sensor.smart_bed_parent_mouvement_gauche
        - binary_sensor.smart_bed_parent_moving_target
      no_motion_wait:
        seconds: 5
      kill_switch: input_boolean.auto_light_kill_switch_chambre_parent
      only_during_night: true
      turn_on_data:
        color_name: red
        brightness_pct: 20
################################################################################
- id: chambre_parent_bed_light_auto_right
  alias: Area - Chambre parent - Lumière lit auto droite
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.smart_bed_parent_lumi_re_droite
      motion_sensor: 
        - binary_sensor.smart_bed_parent_mouvement_droite
        - binary_sensor.smart_bed_parent_moving_target
      no_motion_wait:
        seconds: 5
      kill_switch: input_boolean.auto_light_kill_switch_chambre_parent
      only_during_night: true
      turn_on_data:
        color_name: red
        brightness_pct: 20
################################################################################
- id: 'chambre_parent_lumiere_auto'
  alias: Area - Chambre parent - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.chambre
      adaptive_lighting: switch.adaptive_lighting_chambre_parent
      motion_sensor: 
        - binary_sensor.smart_bed_parent_mouvement_droite
        - binary_sensor.smart_bed_parent_mouvement_gauche
        - binary_sensor.smart_bed_parent_moving_target
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30
      kill_switch: 
        - input_boolean.auto_light_kill_switch_chambre_parent
        - binary_sensor.presence_lit_chambre_parents
        - input_boolean.night_mode
      only_turn_off: false
      only_during_night: true      
      toggle_trigger:
        trigger: state
        entity_id: binary_sensor.parent_light_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'chambre_parent_bed_light_switch'
  alias: Area - Chambre parent - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.parent_light_switch_swipe_right
      touchfield_1: binary_sensor.parent_light_switch_touchfield_1
      touchfield_2: binary_sensor.parent_light_switch_touchfield_2
      long_press: binary_sensor.parent_light_switch_long_press
      multi_touch: binary_sensor.parent_light_switch_multi_touch
      swipe_left: binary_sensor.parent_light_switch_swipe_left
      swipe_right_action:
        - action: light.turn_on
          data: 
            color_name: red
            brightness_pct: 30
          target:
            entity_id:
              - light.smart_bed_parent_lumi_re_gauche
              - light.smart_bed_parent_lumi_re_droite
        - delay: "00:00:15" 
        - action: light.turn_off
          data: {}
          target:
            entity_id:
              - light.smart_bed_parent_lumi_re_gauche
              - light.smart_bed_parent_lumi_re_droite
################################################################################

homeassistant:
  customize:
   binary_sensor.capteurs_mouvement_chambre_parents:
      room_main: occupancy