template:
  - sensor:
    - unique_id: temperature_chambre_emilie
      name: Chambre Émilie temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.chambre_emilie', 'current_temperature')|float }}"

input_boolean:
  curfew_emilie:
    name: Couvre feu Émilie
    icon: bha:night-light

input_select:
  music_browser_chambre_emilie:
    name: Music Browser Chambre Émilie
    options:
      - ' '
    icon: mdi:playlist-music

automation:
################################################################################
- id: 'chambre_emilie_button_lit'
  alias: Area - Chambre Émilie - Bouton lit
  description: ''
  use_blueprint:
    path: antorfr/BluButtonRC4.yaml
    input:
      button_device: c6d010664c0f83b44711aa515d987fe0
      button_1_short:
        - action: light.toggle
          data: {}
          target:
            entity_id: light.chambre_emilie_plafonnier
      button_3_short:
        - action: cover.toggle
          target:
            area_id: chambre_emilie
          data: {}
      button_2_short:
        - action: select.select_option
          target:
            entity_id: select.emilie_clock_display_mode
          data:
            option: Clock
        - action: light.toggle
          target:
            entity_id: light.emilie_clock_led_matrix
          data: {}
      button_4_short:
        - if:
            - condition: state
              entity_id: media_player.emilie
              state: playing
          then:
            - action: media_player.media_play_pause
              metadata: {}
              data: {}
              target:
                entity_id: media_player.emilie
          else:
            - action: script.chambre_music_douce
              metadata: {}
              data:
                child: Émilie
################################################################################
- id: 'chambre_emilie_music_curfew'
  alias: Area - Chambre Émilie - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.emilie
      input_target: input_boolean.curfew_emilie
################################################################################
- id: 'chambre_emilie_light_switch'
  alias: Area - Chambre Émilie - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.emilie_entrance_switch_swipe_right
      touchfield_1: binary_sensor.emilie_entrance_switch_touchfield_1
      touchfield_2: binary_sensor.emilie_entrance_switch_touchfield_2
      long_press: binary_sensor.emilie_entrance_switch_long_press
      multi_touch: binary_sensor.emilie_entrance_switch_multi_touch
      swipe_left: binary_sensor.emilie_entrance_switch_swipe_left
      touchfield_1_action:
        - action: light.toggle
          target:
            entity_id: light.emilie_clock_led_matrix
        - action: select.select_option
          target:
            entity_id: select.emilie_clock_display_mode
          data:
            option: Clock
      touchfield_2_action:
        - action: switch.toggle
          target:
            entity_id: switch.chambre_emilie_prise_bureau
      multi_touch_action:
        - parallel: 
          - action: light.turn_off
            target:
              area_id: "{{room}}"
          - action: switch.turn_off
            entity_id: switch.chambre_emilie_prise_bureau
            data: {}
          - action: script.play_mood_music
            data:
              action: media_stop
              areas: "{{room}}"
      swipe_right_action:
        - action: cover.toggle
          target:
            area_id: chambre_emilie
      swipe_left_action:
        - action: cover.toggle
          target:
            area_id: chambre_emilie      
################################################################################
- id: 'chambre_emilie_light_switch_desk'
  alias: Area - Chambre Émilie - Bouton bureau
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.emilie_desk_switch_swipe_right
      touchfield_1: binary_sensor.emilie_desk_switch_touchfield_1
      touchfield_2: binary_sensor.emilie_desk_switch_touchfield_2
      long_press: binary_sensor.emilie_desk_switch_long_press
      multi_touch: binary_sensor.emilie_desk_switch_multi_touch
      swipe_left: binary_sensor.emilie_desk_switch_swipe_left
      touchfield_1_action:
        - action: switch.toggle
          target:
            entity_id: switch.chambre_emilie_prise_bureau
      multi_touch_action:
        - parallel: 
          - action: light.turn_off
            target:
              area_id: "{{room}}"
          - action: switch.turn_off
            entity_id: switch.chambre_emilie_prise_bureau 
          - action: script.play_mood_music
            data:
              action: media_stop
              areas: "{{room}}"
      swipe_right_action:
        - action: cover.toggle
          target:
            area_id: chambre_emilie
      swipe_left_action:
        - action: cover.toggle
          target:
            area_id: chambre_emilie   
################################################################################
- id: 'chambre_emilie_lumiere_auto'
  alias: Area - Chambre Émilie - Lumière Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.chambre_emilie_plafonnier
      adaptive_lighting: switch.adaptive_lighting_chambre_emilie
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        trigger: state
        entity_id: 
          - binary_sensor.emilie_entrance_switch_touchfield_3
          - binary_sensor.emilie_desk_switch_touchfield_2
        from: ["off"]
        to: ["on"]
        id: toggle