automation:
################################################################################
- id: 'chambre_emilie_prise_moustique'
  alias: Area - Chambre Emilie - Prise anti-moustique
  description: ''
  trigger: 
    platform: time_pattern
    hours: '/2'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: "person.emilie"
          state: "home"
        - condition: time
          after: '20:00:00'
          before: '06:00:00'
  action:
  - entity_id:  switch.smart_power_outlet_2
    service: switch.turn_on
  - delay: 00:45:00
  - entity_id: switch.smart_power_outlet_2
    service: switch.turn_off
################################################################################