template:
  - sensor:
    - unique_id: temperature_chambre_emilie
      name: Chambre Émilie temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.netatmo_chambre_emilie', 'current_temperature')|float }}"

input_boolean:
  curfew_emilie:
    name: Couvre feu Émilie
    icon: bha:night-light

automation:
################################################################################
- id: 'chambre_emilie_button_lit'
  alias: Area - Chambre Émilie - Bouton lit
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: 23afcee06ee96560d15972e61663763b
      type: toggle
      subtype: 'toggle'
      discovery_id: 0x0004740000890033 action_toggle
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.chambre_emilie_plafonnier
################################################################################
- id: 'chambre_emilie_music_curfew'
  alias: Area - Chambre Émilie - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.emilie
      input_target: input_boolean.curfew_emilie
################################################################################
- id: 'chambre_emilie_light_switch'
  alias: Area - Chambre Émilie - Bouton entrée
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.emilie_entrance_switch_swipe_right
      touchfield_1: binary_sensor.emilie_entrance_switch_touchfield_1
      touchfield_2: binary_sensor.emilie_entrance_switch_touchfield_2
      long_press: binary_sensor.emilie_entrance_switch_long_press
      multi_touch: binary_sensor.emilie_entrance_switch_multi_touch
      swipe_left: binary_sensor.emilie_entrance_switch_swipe_left
      touchfield_1_action:
        - service: light.toggle
          target:
            entity_id: light.horloge_emilie
      touchfield_2_action:
        - service: switch.toggle
          target:
            entity_id: switch.chambre_emilie_prise_bureau
      multi_touch_action:
        - parallel: 
          - service: light.turn_off
            target:
              area_id: "{{room}}"
          - service: switch.turn_off
            entity_id: switch.chambre_emilie_prise_bureau
            data: {}
          - service: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"
################################################################################
- id: 'chambre_emilie_light_switch_desk'
  alias: Area - Chambre Émilie - Bouton bureau
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.emilie_desk_switch_swipe_right
      touchfield_1: binary_sensor.emilie_desk_switch_touchfield_1
      touchfield_2: binary_sensor.emilie_desk_switch_touchfield_2
      long_press: binary_sensor.emilie_desk_switch_long_press
      multi_touch: binary_sensor.emilie_desk_switch_multi_touch
      swipe_left: binary_sensor.emilie_desk_switch_swipe_left
      touchfield_1_action:
        - service: switch.toggle
          target:
            entity_id: switch.chambre_emilie_prise_bureau
      multi_touch_action:
        - parallel: 
          - service: light.turn_off
            target:
              area_id: "{{room}}"
          - service: switch.turn_off
            entity_id: switch.chambre_emilie_prise_bureau 
          - service: script.play_mood_music
            data:
              action: media_stop
              rooms: "{{room}}"
################################################################################
- id: 'chambre_emilie_lumiere_auto'
  alias: Area - Chambre Émilie - Lumière Auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.chambre_emilie_plafonnier
      adaptive_lighting: switch.adaptive_lighting_chambre_emilie
      motion_sensor: binary_sensor.anyone_home
      no_motion_wait:
        minutes: 15
      no_motion_warning: 30  
      only_turn_off: true      
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.emilie_entrance_switch_touchfield_3
          - binary_sensor.emilie_desk_switch_touchfield_2
        from: ["off"]
        to: ["on"]
        id: toggle