
input_boolean:
  curfew_timothee:
    name: Couvre feu Timothée
    icon: bha:night-light

automation:
################################################################################
- id: 'chambre_timothee_button_lumiere'
  alias: Area - Chambre Timothée - Bouton lumière
  description: ''
  mode: restart
  trigger:
    - platform: device
      domain: mqtt
      device_id: a4b9a8eb714cd58a2183a5af310d162d
      type: action
      subtype: 'off'
      discovery_id: 0x0004740000890060 action_off
    - platform: device
      domain: mqtt
      device_id: a4b9a8eb714cd58a2183a5af310d162d
      type: action
      subtype: 'on'
      discovery_id: 0x0004740000890060 action_on
  condition: []
  action:
  - choose:
      - conditions:
          - condition: device
            type: is_off
            device_id: 6bb7ab79426cb51ac7610517636240b4
            entity_id: light.chambre_timothee_plafonnier
            domain: light
          - condition: time
            after: '20:00'
            before: '07:00'
          - condition: state
            entity_id: cover.chambre_timothee_volet_roulant
            state: open
            for:
              hours: 0
              minutes: 30
              seconds: 0
        sequence:
          - service: cover.close_cover
            data: {}
            target:
              area_id: chambre_timothee
      - conditions:
          - condition: state
            entity_id: cover.chambre_timothee_volet_roulant
            state: closed
            for:
              hours: 0
              minutes: 30
              seconds: 0
          - condition: device
            type: is_off
            device_id: 6bb7ab79426cb51ac7610517636240b4
            entity_id: light.chambre_timothee_plafonnier
            domain: light
          - condition: time
            after: '08:00'
            before: '12:00'
        sequence:
          - service: cover.open_cover
            data: {}
            target:
              area_id: chambre_timothee
    default: []
  - service: light.toggle
    data: {}
    target:
      entity_id: light.chambre_timothee_plafonnier
################################################################################
- id: 'chambre_timothee_button_volet'
  alias: Area - Chambre Timothée - Bouton volets
  description: ''
  mode: single
  trigger:
    - platform: device
      domain: mqtt
      device_id: ff76dd5000f655268be400dc3d22cf31
      type: action
      subtype: open
      discovery_id: 0x0004740000ad983d action_open
      id: open
    - platform: device
      domain: mqtt
      device_id: ff76dd5000f655268be400dc3d22cf31
      type: action
      subtype: close
      discovery_id: 0x0004740000ad983d action_close
      id: close
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: open
          sequence:
            - service: cover.open_cover
              data: {}
              target:
                area_id: chambre_timothee
        - conditions:
            - condition: trigger
              id: close
          sequence:
            - service: cover.close_cover
              data: {}
              target:
                area_id: chambre_timothee
      default: []
################################################################################
- id: 'chambre_timothee_party_mode'
  alias: Area - Chambre Timothée - Mode fête
  description: "Chambre Timothée - Mode fête"
  trigger:
    - platform: tag
      tag_id: 53-4F-E4-D7-60-00-01
  condition: []
  action:
    - service: tts.cloud_say
      data:
        entity_id: media_player.timothee
        message: Super, c'est la fête !
        cache: true
    - service: light.turn_on
      data:
        effect: Color Wipe
        brightness_pct: 100
      target:
        entity_id: light.timothee_bed_light_lumires_lit_timothe
    - delay:
        hours: 0
        minutes: 0
        seconds: 1
        milliseconds: 0
    - service: script.play_mood_music
      data:
        rooms:
          - chambre_timothee
        title: Dance Émilie
  mode: single
################################################################################
- id: 'chambre_timothee_music_curfew'
  alias: Area - Chambre Timothée - couvre-feu musique
  description: ""
  use_blueprint:
    path: antorfr/curfew.yaml
    input:
      media_player_target: media_player.timothee
      input_target: input_boolean.curfew_timothee