group:
  couloir_sensors:
    name: Capteurs mouvement couloir
    all: false
    entities:
      - binary_sensor.camera_couloir
      - binary_sensor.blumotion_couloir_etage_motion

sensor:
  - name: mouvement_couloir_5min
    platform: history_stats
    entity_id: group.couloir_sensors
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

