homeassistant:
  customize:
   binary_sensor.capteurs_mouvement_cuisine:
      room_main: occupancy

binary_sensor:
  - platform: group
    name: "Capteurs mouvement cuisine"
    device_class: occupancy
    unique_id: cuisine_motion_sensors
    all: false
    entities:
      - binary_sensor.kitchen_presence_sensor_occupancy
      - binary_sensor.blumotion_cuisine_motion
      - binary_sensor.blumotion_cuisine_entree_motion

light:
  - platform: group
    name: Cusine plafonier
    entities:
      - light.plafonier_cusine_1
      - light.hue_color_lamp_5
      - light.hue_color_lamp_5_2
      - light.hue_color_candle_salon
      - light.liseuse_laurine
      - light.hue_color_candle_2

  - platform: group
    name: Cusine spot
    entities:
      - light.hue_ambiance_spot_7
      - light.hue_ambiance_spot_5
      - light.hue_ambiance_spot_6

template:
  - sensor:
    - unique_id: temperature_cuisine
      name: Cuisine temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.cuisine', 'current_temperature')|float }}"

sensor:
  - name: mouvement_cuisine_5min
    platform: history_stats
    entity_id: binary_sensor.cuisine_capteur_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:5:00
    end: "{{now()}}"

input_boolean:
  auto_light_kill_switch_cuisine:
    name: Lumière mode manuel (cuisine)
    initial: false
    icon: mdi:autorenew-off

automation:
################################################################################
- id: cuisine_light_auto
  alias: Area - Cuisine - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.cusine_plafonier
          - light.cusine_spot
      motion_sensor: binary_sensor.capteurs_mouvement_cuisine
      no_motion_wait: 
        minutes: 10
      no_motion_warning: 30
      only_during_night: false
      light_sensor: sensor.cuisine_capteur_luminosite_illuminance
      lux_cutoff: 60
      lux_sun_cutoff: 250
      adaptive_lighting: switch.adaptive_lighting_cuisine
      kill_switch: input_boolean.auto_light_kill_switch_cuisine
################################################################################


