light:
  - platform: group
    name: Cusine plafonier
    entities:
      - light.plafonier_cusine_1
      - light.hue_color_lamp_5
      - light.hue_color_lamp_5_2
      - light.hue_color_candle_salon
      - light.liseuse_laurine
      - light.hue_color_candle_2

  - platform: group
    name: Cusine spot
    entities:
      - light.hue_ambiance_spot_7
      - light.hue_ambiance_spot_5
      - light.hue_ambiance_spot_6

automation:

################################################################################
- id: 'cuisine_light_auto'
  alias: Area - Cuisine - Lumière auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    platform: state
    entity_id: binary_sensor.cuisine_capteur_mouvement_ias_zone
    from: "off"
    to: "on"

  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: light.cusine_plafonier
          state: "off"

  action:
  - choose:
      - conditions:
        - condition: state
          entity_id: switch.adaptive_lighting_cuisine
          state: 'on'
        sequence:
        - service: adaptive_lighting.apply
          entity_id: switch.adaptive_lighting_cuisine
          data:
            lights:
              - light.cusine_plafonier
            turn_on_lights: true
    default:
        - service: light.turn_on
          target: 
            entity_id: light.cusine_plafonier
  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.cuisine_capteur_mouvement_ias_zone
      from: "on"
      to: "off"
  - delay:
      minutes: 2
  - service: light.turn_off
    target: 
      entity_id: 
      - light.cusine_plafonier
      - light.cusine_spot
################################################################################
