light:
  - platform: group
    name: Entrée Spots
    entities:
      - light.hue_color_spot_12
      - light.hue_color_spot_13
      - light.hue_color_spot_14
      - light.hue_color_spot_15

sensor:
  - name: mouvement_entree_5min
    platform: history_stats
    entity_id: binary_sensor.entree_capteur_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'entree_button'
  alias: Area - Entrée - Bouton portail
  description: ''
  trigger:
    - platform: device
      domain: mqtt
      device_id: 6d056f737f6d1c5c6e93a60b58875307
      type: action
      subtype: single
      discovery_id: 0x00124b001f6618d8 action_single
  condition: []
  action:
    - service: cover.toggle
      data: {}
      entity_id: cover.portail
################################################################################

################################################################################
- id: 'entree_light_auto'
  alias: Area - Entrée - Lumière auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: state
      entity_id: binary_sensor.entree_capteur_mouvement_occupancy
      to: "on"
      id: "on"
    - platform: state
      entity_id: binary_sensor.entree_capteur_mouvement_occupancy
      to: "off"
      for:
        minutes: 3
      id: "off"

  condition:
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 'on' 
          - condition: numeric_state
            entity_id: sensor.entree_capteur_luminosite_illuminance_lux
            below: 60
          - condition: state
            entity_id: light.entree_spots
            state: 'off'
      - condition: and
        conditions:
          - condition: trigger
            id: 'off' 
          - condition: state
            entity_id: light.entree_spots
            state: 'on'        

  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - choose:
          - conditions:
            - condition: state
              entity_id: switch.adaptive_lighting_default
              state: 'on'
            sequence:
            - service: adaptive_lighting.apply
              entity_id: switch.adaptive_lighting_default
              data:
                lights:
                  - light.entree_spots
                turn_on_lights: true
        default:
            - service: light.turn_on
              target: 
                entity_id: light.entree_spots
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.entree_capteur_mouvement_occupancy
          to: "off"
          for:
            minutes: 2
  - service: light.turn_off
    target: 
      entity_id: light.entree_spots
################################################################################

################################################################################
- id: 'entree_light_button'
  alias: Area - Entrée - Lumière bouton
  description: ''
  trigger:
  - platform: state
    entity_id: switch.telerupteur_lumiere_l2
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.entree_spots
  - delay:
      seconds: 1
  mode: single
  ################################################################################