light:
  - platform: group
    name: Entrée Spots
    entities:
      - light.hue_color_spot_12
      - light.hue_color_spot_13
      - light.hue_color_spot_14
      - light.hue_color_spot_15

sensor:
  - name: mouvement_entree_5min
    platform: history_stats
    entity_id: binary_sensor.entree_capteur_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'entree_button'
  alias: Area - Entrée - Bouton portail
  description: ''
  trigger:
    - platform: device
      domain: mqtt
      device_id: 6d056f737f6d1c5c6e93a60b58875307
      type: action
      subtype: single
      discovery_id: 0x00124b001f6618d8 action_single
  condition: []
  action:
    - service: cover.toggle
      data: {}
      target:
        entity_id: cover.portail_2
################################################################################

################################################################################
- id: 'entree_light_auto'
  alias: Area - Entrée - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.entree_spots
      motion_sensor: binary_sensor.entree_capteur_mouvement_occupancy
      no_motion_wait:
        minutes: 3
      no_motion_warning: 30
      light_sensor: sensor.entree_capteur_luminosite_illuminance_lux
      lux_cutoff: 60
      adaptive_lighting: switch.adaptive_lighting_default
      only_during_night: false
################################################################################

################################################################################
- id: 'entree_light_button'
  alias: Area - Entrée - Lumière bouton
  description: ''
  trigger:
  - platform: state
    entity_id: switch.telerupteur_lumiere_l2
    from: ["on", "off"]
    to: ["on","off"]
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.entree_spots
  - delay:
      seconds: 1
  mode: single
  ################################################################################