binary_sensor:
  - platform: group
    name: "Escalier Capteurs mouvement"
    device_class: occupancy
    unique_id: escaliers_motion_sensors
    all: false
    entities:
      - binary_sensor.couloir_etage_capteur_mouvement_occupancy
      - binary_sensor.blumotion_escalier_haut_motion
      - binary_sensor.blumotion_escalier_bas_motion
      - binary_sensor.couloir_person_occupancy

sensor:
  - name: mouvement_escalier_5min
    platform: history_stats
    entity_id: binary_sensor.escalier_capteurs_mouvement
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: escalier_light_auto
  alias: Area - Escalier - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.couloir_etage
          - light.escaliers
      motion_sensor: binary_sensor.escalier_capteurs_mouvement
      no_motion_wait:
        minutes: 1
      no_motion_warning: 30
      only_during_night: false
      adaptive_lighting: switch.adaptive_lighting_couloir_etage
################################################################################
- id: escalier_light_button
  alias: Area - Escalier - Lumière bouton
  description: ''
  trigger:
  - platform: state
    entity_id: switch.telerupteur_lumiere_l1
    from: ["on", "off"]
    to: ["on","off"]
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.couloir_etage
          state: 'on'
        - condition: state
          entity_id: light.escaliers
          state: 'on' 
      sequence:  
      - service: light.turn_off
        data: {}
        target:
          entity_id: 
          - light.escaliers
          - light.couloir_etage
    default:
    - service: light.turn_on
      target: 
        entity_id:
          - light.escaliers
          - light.couloir_etage
  - delay:
      seconds: 1
  mode: single
  ################################################################################

homeassistant:
  customize:
   binary_sensor.escalier_capteurs_mouvement:
      room_main: occupancy