group:
  escalier_sensors:
    name: Capteurs mouvement escalier
    all: false
    entities:
      - binary_sensor.escalier_capteur_mouvement_occupancy
      - binary_sensor.couloir_etage_capteur_mouvement_occupancy
      - binary_sensor.escalier_capteur_mouvement_haut_occupancy


sensor:
  - name: mouvement_escalier_5min
    platform: history_stats
    entity_id: group.escalier_sensors
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: escalier_light_auto
  alias: Area - Escalier - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.couloir_etage
          - light.escaliers
      motion_sensor: group.escalier_sensors
      no_motion_wait: 60
      no_motion_warning: 30
      only_during_night: 0
      light_sensor:
      lux_cutoff:
      adaptive_lighting: switch.adaptive_lighting_default
################################################################################
- id: escalier_light_button
  alias: Area - Escalier - Lumière bouton
  description: ''
  trigger:
  - platform: state
    entity_id: switch.telerupteur_lumiere_l1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.couloir_etage
          state: 'on'
        - condition: state
          entity_id: light.escaliers
          state: 'on' 
      sequence:  
      - service: light.turn_off
        data: {}
        target:
          entity_id: 
          - light.escaliers
          - light.couloir_etage
    default:
    - service: light.turn_on
      target: 
        entity_id:
          - light.escaliers
          - light.couloir_etage
  - delay:
      seconds: 1
  mode: single
  ################################################################################