group:
  escalier_sensors:
    name: Capteurs mouvement escalier
    all: false
    entities:
      - binary_sensor.escalier_capteur_mouvement_ias_zone
      - binary_sensor.lumi_lumi_sensor_motion_aq2_ias_zone

automation:
################################################################################
- id: escalier_light_auto
  alias: Area - Escalier - Lumière auto
  description: ''
  # If motion is detected within the delay,
  # we restart the script.
  mode: restart
  max_exceeded: silent

  trigger:
    platform: state
    entity_id: group.escalier_sensors
    from: "off"
    to: "on"

  #condition:
  # condition: numeric_state
  #  entity_id: sensor.lumi_lumi_sensor_motion_aq2_illuminance
  #  below: 50

  action:
  - choose:
      - conditions:
        - condition: state
          entity_id: switch.adaptive_lighting_default
          state: 'on'
        sequence:
        - service: adaptive_lighting.apply
          entity_id: switch.adaptive_lighting_default
          data:
            lights:
              - light.couloir_etage
              - light.escaliers
            turn_on_lights: true
    default:
        - service: light.turn_on
          target: 
            entity_id:
              - light.couloir_etage
              - light.escaliers
  - wait_for_trigger:
      platform: state
      entity_id: group.escalier_sensors
      from: "on"
      to: "off"
  - delay: 30
  - service: light.turn_off
    target: 
      entity_id:
        - light.couloir_etage
        - light.escaliers
################################################################################
- id: escalier_light_button
  alias: Area - Escalier - Lumière bouton
  description: ''
  trigger:
  - platform: state
    entity_id: light.lumi_lumi_relay_c2acn01_3ae1cf05_on_off
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: 
      - light.hue_color_spot_11
      - light.couloir_etage
  - delay:
      seconds: 1
  mode: single
  ################################################################################