
sensor:
  - name: mouvement_garage-3_10min
    platform: history_stats
    entity_id: binary_sensor.motion_garage_3
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{ now() }}"

automation:
################################################################################
- id: 'garage_switch_garage2'
  alias: Area - Garage - Bouton Garage 2
  description: ''
  mode: parallel
  trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: 950e5646555ea54652e2273c4c3034dd
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - variables:
      command: '{{ trigger.event.data.command }}'
  - choose:
    - conditions:
      - '{{ command == "toggle" }}'
      sequence:
        - service: cover.toggle
          target:
            entity_id: cover.garage_2 
################################################################################