
sensor:
  - name: mouvement_garage-3_10min
    platform: history_stats
    entity_id: binary_sensor.garage_3_person_occupancy
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{ now() }}"

  - platform: min_max
    type: mean
    name: temperature garage
    unique_id: garage_temperature
    round_digits: 1
    entity_ids:
      - sensor.garage_door_2_temperature
      - sensor.garage_door_3_temperature
  - platform: min_max
    type: mean
    name: humiditée garage
    unique_id: garage_humidity
    round_digits: 1
    entity_ids:
      - sensor.garage_door_2_humidity
      - sensor.garage_door_3_humidity
  - platform: min_max
    type: mean
    name: Pression garage
    unique_id: garage_pressure
    round_digits: 1
    entity_ids:
      - sensor.garage_door_2_pressure
      - sensor.garage_door_3_pressure

template:
  - binary_sensor:
      - name: "Porte Garage 2 ouverte"
        device_class: garage_door
        unique_id: "garage2_door_virtual_sensor"
        state: >
          {{not is_state('cover.garage_2',['closed','unavailable'])}}


binary_sensor:
  - platform: group
    name: "Capteurs mouvement garage 2"
    device_class: occupancy
    unique_id: garage2_motion_sensors
    all: false
    entities:
      - binary_sensor.porte_garage_2_ouverte


automation:
################################################################################
- id: 'garage_switch_garage2'
  alias: Area - Garage - Bouton Garage 2
  description: ''
  mode: parallel
  trigger:
  - platform: device
    domain: mqtt
    device_id: 88e0c253966ea547d2e98bc8bbdb64db
    type: action
    subtype: single
    discovery_id: 0x00124b0022419681 action_single
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: cover.toggle
    target:
      entity_id: cover.garage_2 
################################################################################
- id: 'garage_switch_garage1'
  alias: Area - Garage - Bouton Garage 1
  description: ''
  mode: parallel
  trigger:
  - platform: device
    domain: mqtt
    device_id: ca89b98653f56284ee8d128ac1d6c5cf
    type: action
    subtype: single
    discovery_id: 0x00124b0022424be8 action_single
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: cover.toggle
    target:
      entity_id: cover.garage_1
################################################################################
- id: garage2_light_auto
  alias: Area - Garage 2 - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.plafonnier_garage_2
      motion_sensor: binary_sensor.capteurs_mouvement_garage_2
      no_motion_wait: 
        minutes: 2
      only_during_night: true
################################################################################