template:
  - sensor:
    - name: "Temperature Exterieur"
      state: "{{ state_attr('weather.petit_mars', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement

sensor:
  - name: mouvement_patio_10min
    platform: history_stats
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_air_de_jeux_10min
    platform: history_stats
    entity_id: binary_sensor.motion_air_de_jeux
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_entree_10min
    platform: history_stats
    entity_id: binary_sensor.camera_entree
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_parking_10min
    platform: history_stats
    entity_id: binary_sensor.camera_parking
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_terasse_10min
    platform: history_stats
    entity_id: binary_sensor.motion_terrasse
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"

