template:
  - sensor:
    - name: "Temperature Exterieur"
      state: "{{ state_attr('weather.petit_mars', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
  - trigger: #Portail viens de s'ouvrir
      - platform: state
        entity_id:
          - cover.portail_2
        to: open
    binary_sensor:
      - name: Portail just open
        auto_off: "00:01:00"
        state: "true"
        device_class: occupancy

binary_sensor:
  - platform: group
    name: "Jardin devant presence"
    unique_id: jardin_devant_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.entree_person_occupancy
      - binary_sensor.entrance_driveway_car_occupancy
      - binary_sensor.camera_entree_person
      - binary_sensor.portail_front_car_occupancy
      - binary_sensor.portail_just_open
  - platform: group
    name: "Jardin parking presence"
    unique_id: jardin_parking_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.camera_parking_person
      - binary_sensor.parking_person_occupancy

sensor:
  - name: mouvement_patio_10min
    platform: history_stats
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_air_de_jeux_10min
    platform: history_stats
    entity_id: binary_sensor.air_de_jeux_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_entree_10min
    platform: history_stats
    entity_id: binary_sensor.jardin_devant_presence
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_parking_10min
    platform: history_stats
    entity_id: binary_sensor.jardin_parking_presence
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_terasse_10min
    platform: history_stats
    entity_id: binary_sensor.terrasse_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'jardin_xmas-light_auto'
  alias: Area - Jardin - Guirlande auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: sun
      event: sunset
      id: 'sunset'
    - platform: sun
      event: sunrise
      id: 'sunrise'
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: 'sleep'
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: 'wake-up'
    - platform: event
      event_type: routine_event
      event_data:
        type: home
      id: 'come-back'
    - platform: event
      event_type: routine_event
      event_data:
        type: away
      id: 'leaving'

  action:
  - choose:
    - alias: "sunrise and wake up and at home > turn on"
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 
              - 'sunset'
              - 'wake-up'
              - 'come-back'
          - condition: or
            conditions:
              - condition: state
                entity_id: sun.sun
                state: 'below_horizon'
              - condition: trigger
                id: sunset
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
          - condition: state
            entity_id: input_boolean.mode_noel
            state: 'on'
      sequence:
        - service: switch.turn_on
          entity_id: switch.guirlandes_noel_switch
        - service: light.turn_on
          entity_id: light.guirlandes_noel
    - alias: "sunrise or at sleep or away  > turn off"
      conditions:
        - condition: trigger
          id: 
            - 'sunrise'
            - 'sleep'
            - 'leaving'
      sequence:
        - service: switch.turn_off
          entity_id:
            - switch.guirlandes_noel_switch
        - service: light.turn_off
          entity_id:
            - light.guirlandes_noel
################################################################################
- id: 'jardin_sonette_portail'
  alias: Area - Jardin - Sonnette portail
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: state
      entity_id: binary_sensor.sonette_portail_doorbell
      to: 'on'

  action:
  - choose:
    - alias: "Si a la maison"
      conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
      sequence:
        - service: script.sound_notify
          data:
            media_player_entities:
              - media_player.cuisine
              - media_player.salon
              - media_player.salle_a_manger
              - media_player.cuisine_move
              - media_player.bureau
            #media_content_id: "media-source://media_source/sounds/bb8_sound.mp3" > sonos doesn't find local url anymore (home.intra.sberard.fr)
            media_content_id: "https://njm0evdcyztwiwq3vdi76nyi8dbd4zkf.ui.nabu.casa/media/sounds/bb8_sound.mp3"
  - service: notify.all_mobile
    data:
      message: "Quelqu'un sonne au portail"
      data:
        #ios
        entity_id: camera.g4_doorbell_high
        push:
          sound:
            name: "default"
            critical: 1
            volume: 1.0
        #android
        image: "/api/camera_proxy/camera.g4_doorbell_high"
        ttl: 0
        priority: high

        actions:
          - action: "URI" # The key you are sending for the event
            title: "camera" # The button title
            uri: "/lovelace-maison/portails"
            icone: "sfsymbols:video.doorbell"
          - action: "OPEN_FRONTE_GATE" # Must be set to URI if you plan to use a URI
            title: "Ouvrir le portail"
            icone: "sfsymbols:pedestrian.gate.open"
   
################################################################################
- id: 'jardin_sonette_portail_action_notif'
  alias: Area - Jardin - Sonnette portail Actionable
  description: ''
  mode: parallel
  max_exceeded: silent

  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: 'OPEN_FRONTE_GATE'
  action:
      - service: cover.open_cover
        target:
          entity_id: cover.portail_2

################################################################################
- id: jardin_front_light_auto
  alias: Area - Jardin - Lumière devant auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.lumiere_jardin_devant
          #comment parking light to avoid short-circuit
          #- light.garden_parking_light
      motion_sensor: 
        - binary_sensor.jardin_devant_presence
      no_motion_wait:
        minutes: 2
      no_motion_warning: 0
      only_during_night: true
################################################################################
- id: jardin_front_light2_auto
  alias: Area - Jardin - Lumière parking auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.garden_parking_light
      motion_sensor: 
        - binary_sensor.jardin_parking_presence
      no_motion_wait:
        minutes: 3
      no_motion_warning: 0
      only_during_night: true
################################################################################
- id: jardin_back_light_auto
  alias: Area - Jardin - Lumière arriere auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.jardin_lumiere_arriere
      motion_sensor: binary_sensor.terasse_person_occupancy
      no_motion_wait:
        minutes: 10
      no_motion_warning: 0
      only_during_night: true