sensor:
  - platform: template
    sensors:
      temperature_exterieur:
        friendly_name: Temperature Exterieur
        entity_id: weather.petit_mars
        device_class: temperature
        unit_of_measurement: "°C"
        value_template: "{{ state_attr('weather.petit_mars', 'temperature') }}"

