template:
  - sensor:
    - name: "Temperature Exterieur"
      state: "{{ state_attr('weather.petit_mars', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement
  - trigger: #Portail viens de s'ouvrir
      - platform: state
        entity_id:
          - cover.portail_2
        to: open
    binary_sensor:
      - name: Portail just open
        auto_off: "00:01:00"
        state: "true"
        device_class: occupancy

light:
  - platform: group
    unique_id: jardin_lumieres
    name: Jardin lumieres
    entities:
      - light.guirlandes_noel
      - light.jardin_lumiere_arriere
      - light.garden_parking_light
      - light.lumiere_jardin_devant
      - light.jardin

binary_sensor:
  - platform: group
    name: "Jardin devant presence"
    unique_id: jardin_devant_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.entree_person_occupancy
      - binary_sensor.entrance_driveway_car_occupancy
      - binary_sensor.camera_entree_person
      - binary_sensor.portail_front_car_occupancy
      - binary_sensor.portail_just_open
  - platform: group
    name: "Jardin parking presence"
    unique_id: jardin_parking_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.camera_parking_person
      - binary_sensor.parking_person_occupancy
  - platform: group
    name: "Jardin derrière presence"
    unique_id: jardin_derriere_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.air_de_jeux_person_occupancy
      - binary_sensor.terasse_person_occupancy
  - platform: group
    name: "Jardin presence"
    unique_id: jardin_presence
    device_class: occupancy
    all: false
    entities:
      - binary_sensor.jardin_devant_presence
      - binary_sensor.jardin_parking_presence
      - binary_sensor.jardin_derriere_presence


sensor:
  - name: mouvement_patio_10min
    platform: history_stats
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_air_de_jeux_10min
    platform: history_stats
    entity_id: binary_sensor.air_de_jeux_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_entree_10min
    platform: history_stats
    entity_id: binary_sensor.jardin_devant_presence
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_parking_10min
    platform: history_stats
    entity_id: binary_sensor.jardin_parking_presence
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_terasse_10min
    platform: history_stats
    entity_id: binary_sensor.terrasse_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'jardin_xmas-light_auto'
  alias: Area - Jardin - Guirlande auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: sun
      event: sunset
      id: 'sunset'
    - platform: sun
      event: sunrise
      id: 'sunrise'
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: 'sleep'
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: 'wake-up'
    - platform: event
      event_type: routine_event
      event_data:
        type: home
      id: 'come-back'
    - platform: event
      event_type: routine_event
      event_data:
        type: away
      id: 'leaving'

  action:
  - choose:
    - alias: "sunrise and wake up and at home > turn on"
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 
              - 'sunset'
              - 'wake-up'
              - 'come-back'
          - condition: or
            conditions:
              - condition: state
                entity_id: sun.sun
                state: 'below_horizon'
              - condition: trigger
                id: sunset
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
          - condition: state
            entity_id: input_boolean.mode_noel
            state: 'on'
      sequence:
        - service: switch.turn_on
          entity_id: switch.guirlandes_noel_switch
        - service: light.turn_on
          entity_id: light.guirlandes_noel
    - alias: "sunrise or at sleep or away  > turn off"
      conditions:
        - condition: trigger
          id: 
            - 'sunrise'
            - 'sleep'
            - 'leaving'
      sequence:
        - service: switch.turn_off
          entity_id:
            - switch.guirlandes_noel_switch
        - service: light.turn_off
          entity_id:
            - light.guirlandes_noel

################################################################################
- id: jardin_front_light_auto
  alias: Area - Jardin - Lumière devant auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.lumiere_jardin_devant
          - light.garden_parking_light
      motion_sensor: 
        - binary_sensor.jardin_devant_presence
      no_motion_wait:
        minutes: 2
      no_motion_warning: 0
      only_during_night: true
################################################################################
- id: jardin_front_light2_auto
  alias: Area - Jardin - Lumière parking auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.garden_parking_light
      motion_sensor: 
        - binary_sensor.jardin_parking_presence
      no_motion_wait:
        minutes: 3
      no_motion_warning: 0
      only_during_night: true
################################################################################
- id: jardin_back_light_auto
  alias: Area - Jardin - Lumière arriere auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.jardin_lumiere_arriere
      motion_sensor: binary_sensor.terasse_person_occupancy
      no_motion_wait:
        minutes: 10
      no_motion_warning: 0
      only_during_night: true

homeassistant:
  customize:
   binary_sensor.jardin_presence:
      room_main: occupancy
      