template:
  - sensor:
    - name: "Temperature Exterieur"
      state: "{{ state_attr('weather.petit_mars', 'temperature') }}"
      unit_of_measurement: "°C"
      device_class: temperature
      state_class: measurement

sensor:
  - name: mouvement_patio_10min
    platform: history_stats
    entity_id: binary_sensor.hue_outdoor_motion_sensor_1_motion
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_air_de_jeux_10min
    platform: history_stats
    entity_id: binary_sensor.motion_air_de_jeux
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_entree_10min
    platform: history_stats
    entity_id: binary_sensor.camera_entree
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_camera_parking_10min
    platform: history_stats
    entity_id: binary_sensor.camera_parking
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"
  - name: mouvement_terasse_10min
    platform: history_stats
    entity_id: binary_sensor.motion_terrasse
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'jardin_xmas-light_auto'
  alias: Area - Jardin - Guirlande auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: sun
      event: sunset
      id: 'sunset'
    - platform: sun
      event: sunrise
      id: 'sunrise'
    - platform: state
      entity_id: switch.night_mode
      to: 'on'
      id: 'sleep'
    - platform: state
      entity_id: switch.night_mode
      to: 'off'
      id: 'wake-up'
    - platform: event
      event_type: routine_event
      event_data:
        type: home
      id: 'come-back'
    - platform: event
      event_type: routine_event
      event_data:
        type: away
      id: 'leaving'

  action:
  - choose:
    - alias: "sunrise and wake up and at home > turn on"
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 
              - 'sunset'
              - 'wake-up'
              - 'come-back'
          - condition: or
            conditions:
              - condition: state
                entity_id: sun.sun
                state: 'below_horizon'
              - condition: trigger
                id: sunset
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
      sequence:
        - service: switch.turn_on
          entity_id: switch.guirlandes_noel_switch
        - service: light.turn_on
          entity_id: light.guirlandes_noel
    - alias: "sunrise or at sleep or away  > turn off"
      conditions:
        - condition: trigger
          id: 
            - 'sunrise'
            - 'sleep'
            - 'leaving'
      sequence:
        - service: switch.turn_off
          entity_id: switch.guirlandes_noel_switch
        - service: light.turn_off
          entity_id: light.guirlandes_noel
################################################################################
