light:
  - platform: switch
    name: piscine lumière
    entity_id: switch.piscine_lumiere
  - platform: group
    name: piscine
    entities:
      - light.piscine_spot_immergee
      - light.piscine_lumiere

sensor:
  - name: mouvement_piscine_10min
    platform: history_stats
    entity_id: binary_sensor.indoor_pool_person_occupancy
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{ now() }}"
  - platform: history_stats
    name: Durée filtration piscine 24h
    entity_id: switch.piscine_filtration
    state: "on"
    type: time
    duration: "24:00:00"
    end: "{{now()}}"
  - platform: history_stats
    name: Durée electrolyse piscine 24h
    entity_id: switch.piscine_electrolyse
    state: "on"
    type: time
    duration: "24:00:00"
    end: "{{now()}}"

binary_sensor:
  - platform: template
    sensors:
      swiming_pool_door_problem:
        device_class: safety
        friendly_name: Piscine Sécurisée
        value_template: >
          {{is_state('input_boolean.alarme_piscine', 'on') 
          and not(is_state('binary_sensor.piscine_porte_bulle_contact','off'))
          and not(is_state('binary_sensor.indoor_pool_person_occupancy', 'on'))
          }}

alert:
  swiming_pool:
    name: "Porte Piscine non sécurisée"
    message: >
      {% if is_state('binary_sensor.piscine_porte_bulle_contact', 'on') %}
      Attention, la porte de la piscine est restée ouverte sans personne
      {% elif is_state('binary_sensor.piscine_porte_bulle_contact', 'unavailable') %}
      Attention, la porte de la piscine est déconnectée.
      {% else %}
      Tout va bien
      {% endif %}
    done_message: >
      {% if is_state('input_boolean.alarme_piscine', 'off') %}
      Alarme désactivée
      {% else %}
      "Porte Piscine sécurisée"
      {% endif %}
    data:
      entity_id: camera.piscine_high
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0
        #android
      image: "/api/camera_proxy/camera.piscine_high"
      ttl: 0
      priority: high
    entity_id: binary_sensor.swiming_pool_door_problem
    state: "on"   # Optional, 'on' is the default value
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: false  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - all_mobile

  pool_flitering_alert:
    name: "Alerte Piscine filtration"
    message: >
      "Alerte pas de filtration depuis 24h"
    done_message: >
      "Filtration de nouveau actif"
    entity_id: sensor.duree_filtration_piscine_24h
    state: 0.0
    repeat: 180
    can_acknowledge: true  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify

automation:
################################################################################
- id: 'Swimingpool_light_auto'
  alias: Area - Piscine - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.piscine_spot_immergee
          - light.piscine_lumiere
      motion_sensor:
        - binary_sensor.piscine_porte_bulle_contact
        - binary_sensor.indoor_pool_person_occupancy
      no_motion_wait:
        minutes: 10
      no_motion_warning: 0
      only_during_night: true
################################################################################
#- id: 'Swimingpool_auto_filtering_barry'
#  alias: Area - Piscine - Filtration automatique (barry)
#  description: Filtration de la piscine en fonction du prix de l'electricité
#  trigger:
#  - platform: time_pattern
#    minutes: '0'
#    seconds: '0'
#  condition: []
#  variables:
#    duree: 12    
#  action:
#  - choose:
#    - conditions:
#      - condition: template
#        value_template: >
#          {{state_attr('sensor.barry_kwh_total_price','current_frame') < duree}}
#      sequence:
#      - type: turn_on
#        device_id: a2fceb42992a0147a40d883d02e130f8
#        entity_id: switch.hub_cf4cac
#        domain: switch
#    default:
#    - type: turn_off
#      device_id: a2fceb42992a0147a40d883d02e130f8
#      entity_id: switch.hub_cf4cac
#      domain: switch
#  mode: single
################################################################################
- id: 'Swimingpool_auto_filtering_hchp'
  alias: Area - Piscine - Filtration automatique (HP-HC)
  description: Filtration de la piscine en fonction du prix de l'electricité
  trigger:
    - platform: state
      entity_id: sensor.template_teleinfo_periode_tarifaire
  condition: []  
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: sensor.template_teleinfo_periode_tarifaire
        state: HC
      sequence:
        - service: switch.turn_on
          entity_id:
            - switch.piscine_filtration
            - switch.piscine_electrolyse
    default:
      - service: switch.turn_off
        entity_id:
          - switch.piscine_filtration
          - switch.piscine_electrolyse
  mode: single
################################################################################
#- id: 'Swimingpool_auto_boiler_barry'
#  alias: Area - Piscine - Chauffe eau automatique (barry)
#  description: Chauffe eau en fonction du prix de l'electricité
#  trigger:
#  - platform: time_pattern
#    minutes: '0'
#    seconds: '0'
#  condition: []
#  variables:
#    duree: 2   
#  action:
#  - choose:
#    - conditions:
#      - condition: template
#        value_template: >
#          {{state_attr('sensor.barry_kwh_total_price','current_frame') < duree}}
#      sequence:
#      - type: turn_on
#        device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
#        entity_id: switch.piscine_chauffe_eau
#        domain: switch
#    default:
#    - type: turn_off
#      device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
#      entity_id: switch.piscine_chauffe_eau
#      domain: switch
#  mode: single
################################################################################
- id: 'Swimingpool_auto_boiler_hphc'
  alias: Area - Piscine - Chauffe eau automatique (HP-HC)
  description: Chauffe eau en fonction du prix de l'electricité
  trigger:
    - platform: state
      entity_id: sensor.template_teleinfo_periode_tarifaire
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
        - condition: state
          entity_id: sensor.template_teleinfo_periode_tarifaire
          state: HC
      sequence:
      - type: turn_on
        device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
        entity_id: switch.piscine_chauffe_eau
        domain: switch
    default:
    - type: turn_off
      device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
      entity_id: switch.piscine_chauffe_eau
      domain: switch
  mode: single
################################################################################
homeassistant:
  customize:
    automation.area_piscine_filtration_automatique_hp_hc:
      icon: mdi:pool