light:
  - platform: group
    name: piscine
    entities:
      - light.piscine_lumiere_immergee
      - light.piscine_lumiere_2

sensor:
  - name: mouvement_piscine_10min
    platform: history_stats
    entity_id: binary_sensor.indoor_pool_person_occupancy
    state: "on"
    type: time
    duration: 00:10:00
    end: "{{ now() }}"
  - platform: history_stats
    name: Durée filtration piscine 24h
    entity_id: switch.piscine_filtration
    state: "on"
    type: time
    duration: "24:00:00"
    end: "{{now()}}"
  - platform: history_stats
    name: Durée electrolyse piscine 24h
    entity_id: switch.piscine_electrolyse
    state: "on"
    type: time
    duration: "24:00:00"
    end: "{{now()}}"

binary_sensor:
  - platform: template
    sensors:
      swiming_pool_door_problem:
        device_class: safety
        friendly_name: Piscine Sécurisée
        value_template: >
          {{is_state('input_boolean.alarme_piscine', 'on') 
          and not(is_state('binary_sensor.piscine_capteur_porte_door','off'))
          and not(is_state('binary_sensor.indoor_pool_person_occupancy', 'on'))
          }}
  - platform: group
    name: "Piscine capteurs presence"
    device_class: occupancy
    unique_id: piscine_occupancy_sensors
    all: false
    entities:
      - binary_sensor.indoor_pool_person_occupancy


template:
  - binary_sensor:
    - unique_id: water_low_level_pool_problem
      name: Niveau d'eau piscine bas
      device_class: problem
      availability: "{{states('sensor.pool_water_sensor_niveau_d_eau') != 'unknown'}}"
      state: "{{ (states('sensor.pool_water_sensor_niveau_d_eau')|int < 17400 )| d(false)  }}"


alert:
  swiming_pool:
    name: "Porte Piscine non sécurisée"
    message: >
      {% if is_state('binary_sensor.piscine_capteur_porte_door', 'on') %}
      Attention, la porte de la piscine est restée ouverte sans personne
      {% elif is_state('binary_sensor.piscine_capteur_porte_door', 'unavailable') %}
      Attention, la porte de la piscine est déconnectée.
      {% else %}
      Tout va bien
      {% endif %}
    done_message: >
      {% if is_state('input_boolean.alarme_piscine', 'off') %}
      Alarme désactivée
      {% else %}
      "Porte Piscine sécurisée"
      {% endif %}
    data:
      entity_id: camera.piscine_high
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0
        #android
      image: "/api/camera_proxy/camera.piscine_high"
      ttl: 0
      priority: high
    entity_id: binary_sensor.swiming_pool_door_problem
    state: "on"   # Optional, 'on' is the default value
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: false  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - all_mobile

  pool_flitering_alert:
    name: "Alerte Piscine filtration"
    message: >
      "Alerte pas de filtration depuis 24h"
    done_message: >
      "Filtration de nouveau actif"
    entity_id: sensor.duree_filtration_piscine_24h
    state: 0.0
    repeat: 180
    can_acknowledge: true  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify

  pool_ph_alert:
    name: "Alerte PH Piscine"
    message: >
      "PH piscine anormal ({{ states('sensor.plouf_ph') }})"
    done_message: >
      "PH piscine de nouveau normal ({{ states('sensor.plouf_ph') }})"
    entity_id: binary_sensor.ico_ph
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify

  pool_clore_alert:
    name: "Alerte clore Piscine"
    message: >
      {% if (states('sensor.plouf_oxydo_reduction_potential') | float) < state_attr('sensor.plouf_oxydo_reduction_potential','treshold_low') %}
      "Clore piscine trop bas: {{ states('sensor.plouf_oxydo_reduction_potential') | round(2)}}"
      {% elif (states('sensor.plouf_oxydo_reduction_potential') | float) > state_attr('sensor.plouf_oxydo_reduction_potential','treshold_high') %}
      "Clore piscine trop élevé: {{ states('sensor.plouf_oxydo_reduction_potential') | round(2)}}"
      {% else %}
      Tout va bien
      {% endif %}
    done_message: >
      "Clore piscine de nouveau normal ({{ states('sensor.plouf_oxydo_reduction_potential') | round(2) }})"
    entity_id: binary_sensor.ico_redox
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - notify

  pool_low_level:
    name: "Alerte niveau d'eau piscine"    
    message: "Niveau piscine trop bas."
    done_message: "Niveau d'eau piscine de nouveau correcte."
    entity_id: binary_sensor.niveau_d_eau_piscine_bas
    state: "on"   # Optional, 'on' is the default value
    repeat: 1440
    can_acknowledge: true  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify

automation:
################################################################################
- id: 'Swimingpool_light_auto'
  alias: Area - Piscine - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: 
          - light.piscine_lumiere_immergee
          - light.piscine_lumiere_2
      motion_sensor:
        - binary_sensor.piscine_capteur_porte_door
        - binary_sensor.indoor_pool_person_occupancy
      no_motion_wait:
        minutes: 10
      no_motion_warning: 0
      only_during_night: true
################################################################################
#- id: 'Swimingpool_auto_filtering_barry'
#  alias: Area - Piscine - Filtration automatique (barry)
#  description: Filtration de la piscine en fonction du prix de l'electricité
#  trigger:
#  - platform: time_pattern
#    minutes: '0'
#    seconds: '0'
#  condition: []
#  variables:
#    duree: 12    
#  action:
#  - choose:
#    - conditions:
#      - condition: template
#        value_template: >
#          {{state_attr('sensor.barry_kwh_total_price','current_frame') < duree}}
#      sequence:
#      - type: turn_on
#        device_id: a2fceb42992a0147a40d883d02e130f8
#        entity_id: switch.hub_cf4cac
#        domain: switch
#    default:
#    - type: turn_off
#      device_id: a2fceb42992a0147a40d883d02e130f8
#      entity_id: switch.hub_cf4cac
#      domain: switch
#  mode: single
################################################################################
- id: 'Swimingpool_auto_filtering_hchp'
  alias: Area - Piscine - Filtration automatique (HP-HC)
  description: Filtration de la piscine en fonction du prix de l'electricité
  trigger:
    - platform: state
      entity_id: sensor.template_teleinfo_periode_tarifaire
    - platform: state
      entity_id: schedule.filtration_piscine_ete
  condition:
    - condition: state
      entity_id: input_boolean.piscine_en_hivernage 
      state: 'off'
  action:
  - choose:
    - conditions:
      - alias: "Heure creuse ou Filtration ete"
        condition: or
        conditions:
          - condition: state
            entity_id: sensor.template_teleinfo_periode_tarifaire
            state: HC
          - alias: "Temperature trop chaude et Tempo non rouge"
            condition: and
            conditions:
              - condition: state
                entity_id: schedule.filtration_piscine_ete
                state: 'on'
              - condition: numeric_state
                entity_id:
                  - sensor.piscine_capteur_porte_temperature
                above: 30
              - condition: not
                conditions:
                  - condition: state
                    entity_id: sensor.linky_couleur_actuelle
                    state: rouge
      sequence:
        - service: switch.turn_on
          target:
            entity_id:
              - switch.piscine_filtration
        - if:
          - condition: template
            value_template: >
              {% set th = state_attr('sensor.plouf_oxydo_reduction_potential','treshold_high') %}
              {% set tl = state_attr('sensor.plouf_oxydo_reduction_potential','treshold_low') %}
              {% set target = (th-tl)/2+tl %}
              {{(states('sensor.plouf_oxydo_reduction_potential') | float) < target}}            
          then:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.piscine_electrolyse
    default:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.piscine_filtration
            - switch.piscine_electrolyse
  mode: single
################################################################################
- id: 'Swimingpool_auto_filtering_winter'
  alias: Area - Piscine - Filtration automatique (hivernage)
  description: Filtration de la piscine (hivernage)
  trigger:
    - platform: state
      entity_id: schedule.filtration_piscine_hivernage
  condition: 
    - condition: state
      entity_id: input_boolean.piscine_en_hivernage 
      state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: schedule.filtration_piscine_hivernage
        state: 'on'
      sequence:
        - service: switch.turn_on
          target:
            entity_id:
              - switch.piscine_filtration
              - switch.piscine_electrolyse
    default:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.piscine_filtration
            - switch.piscine_electrolyse
  mode: single
################################################################################
#- id: 'Swimingpool_auto_boiler_barry'
#  alias: Area - Piscine - Chauffe eau automatique (barry)
#  description: Chauffe eau en fonction du prix de l'electricité
#  trigger:
#  - platform: time_pattern
#    minutes: '0'
#    seconds: '0'
#  condition: []
#  variables:
#    duree: 2   
#  action:
#  - choose:
#    - conditions:
#      - condition: template
#        value_template: >
#          {{state_attr('sensor.barry_kwh_total_price','current_frame') < duree}}
#      sequence:
#      - type: turn_on
#        device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
#        entity_id: switch.piscine_chauffe_eau
#        domain: switch
#    default:
#    - type: turn_off
#      device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
#      entity_id: switch.piscine_chauffe_eau
#      domain: switch
#  mode: single
################################################################################
- id: 'Swimingpool_auto_boiler_hphc'
  alias: Area - Piscine - Chauffe eau automatique (HP-HC)
  description: Chauffe eau en fonction du prix de l'electricité
  trigger:
    - platform: state
      entity_id: sensor.template_teleinfo_periode_tarifaire
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.away_mode
          state: 'off'
        - condition: state
          entity_id: input_boolean.piscine_en_hivernage
          state: 'off'
        - condition: state
          entity_id: sensor.template_teleinfo_periode_tarifaire
          state: HC
      sequence:
      - type: turn_on
        device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
        entity_id: switch.piscine_chauffe_eau
        domain: switch
    default:
    - type: turn_off
      device_id: 4d5af4c5d0a5bd84eafb9ef394b320b5
      entity_id: switch.piscine_chauffe_eau
      domain: switch
  mode: single
################################################################################

- id: 'Swimingpool_auto_stop_filling'
  alias: Area - Piscine - Arret automatique remplissage
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - switch.vanne_piscine
      to: "on"
      for:
        hours: 2
        minutes: 0
        seconds: 0
    - platform: numeric_state
      entity_id:
        - sensor.pool_water_sensor_niveau_d_eau
      for:
        hours: 0
        minutes: 30
        seconds: 0
      above: 19100
  condition:
    - condition: state
      entity_id: switch.vanne_piscine
      state: "on"
    - condition: numeric_state
      entity_id: sensor.pool_water_sensor_niveau_d_eau
      above: 19000
  action:
    - action: switch.turn_off
      target:
        entity_id: switch.vanne_piscine
      data: {}
    - action: notify.all_mobile
      metadata: {}
      data:
        message: Arrosage piscine coupée.
################################################################################

homeassistant:
  customize:
    automation.area_piscine_filtration_automatique_hp_hc:
      icon: mdi:air-filter
    binary_sensor.piscine_capteurs_presence:
      room_main: occupancy