light:
  - platform: group
    name: Salle de douche lumieres
    unique_id: salle_de_douche_lumieres
    entities:
      - light.dressing_plafonnier
      - light.salle_de_douche_plafonnier
      - light.shower_light_lumi_re_douche
      - light.shower_light_switch_l2

automation:
################################################################################
- id: 'salle_de_douche_light'
  alias: Area - Salle de douche - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.salle_de_douche_lumieres
      adaptive_lighting: switch.adaptive_lighting_salle_de_douche
      motion_sensor: binary_sensor.anyone_home
      only_turn_off: true   
      no_motion_wait:
        minutes: 5
      no_motion_warning: 30
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.dressing_light_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle
################################################################################
- id: 'salle_de_douche_light_switch_dressing'
  alias: Area - Salle de douche - Bouton dressing
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.dressing_light_switch_swipe_right
      touchfield_1: binary_sensor.dressing_light_switch_touchfield_1
      touchfield_2: binary_sensor.dressing_light_switch_touchfield_2
      long_press: binary_sensor.dressing_light_switch_long_press
      multi_touch: binary_sensor.dressing_light_switch_multi_touch
      swipe_left: binary_sensor.dressing_light_switch_swipe_left

################################################################################
- id: 'salle_de_douche_light_switch_shower'
  alias: Area - Salle de douche - Bouton douche
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.shower_light_switch_swipe_right
      touchfield_1: binary_sensor.shower_light_switch_touchfield_1
      touchfield_2: binary_sensor.shower_light_switch_touchfield_2
      long_press: binary_sensor.shower_light_switch_long_press
      multi_touch: binary_sensor.shower_light_switch_multi_touch
      swipe_left: binary_sensor.shower_light_switch_swipe_left
      touchfield_1_controlled_entites:
        - light.shower_light_lumi_re_douche
      touchfield_2_controlled_entites:
        - light.dressing_plafonnier
        - light.salle_de_douche_plafonnier
################################################################################
- id: 'salle_de_douche_cold_shower_warning'
  alias: "Area - Salle de douche - Alarme douche froide"
  description: ''
  use_blueprint:
    path: antorfr/hot_water_warning.yaml
    input:
      light_target: light.shower_light_lumi_re_douche
      tank_temperature: water_heater.pac_tank
      temp_treshold: 25

