binary_sensor:
  - platform: group
    name: "Salle a manger Capteurs mouvement"
    device_class: motion
    unique_id: salle_a_manger_motion_sensors
    all: false
    entities:
      - binary_sensor.salle_a_manger_capteur_mouvement_occupancy
      - binary_sensor.salle_a_manger_presence_presence

template:
  - sensor:
    - unique_id: temperature_salle_a_manger
      name: Salle à manger temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      state: "{{ state_attr('climate.netatmo_salle_a_manger', 'current_temperature')|float }}"

sensor:
  - name: mouvement_salle_a_manger_5min
    platform: history_stats
    entity_id: binary_sensor.salle_a_manger_capteurs_mouvement
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: salle-a-manger_light_auto
  alias: Area - Salle à manger - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.salle_a_manger
      motion_sensor: binary_sensor.salle_a_manger_capteurs_mouvement
      no_motion_wait:
        minutes: 40
      no_motion_warning: 30
      only_during_night: true
      light_sensor:
      lux_cutoff:
      adaptive_lighting: switch.adaptive_lighting_salle_a_manger
################################################################################
- id: salle-a-manger_light_button
  alias: Area - Salle à manger - bouton
  description: ''
  mode: single
  trigger:
    - platform: device
      domain: tasmota
      device_id: dda5bae70a918c994d724c42d0f35c55
      type: button_short_press
      subtype: switch_1
      discovery_id: 24A160119D21_switch_1_TOGGLE
  condition: []
  action:
    - service: light.toggle
      data: {}
      target:
        area_id: salle_a_manger
################################################################################