light:
  - platform: group
    name: Salle de douche lumieres
    unique_id: salle_de_douche_lumieres
    entities:
      #- light.dressing_plafonnier
      #- light.salle_de_douche_plafonnier
      - light.dressing_light_switch_l1
      - light.shower_light_switch_l2
      - light.shower_light_switch_l1

automation:
################################################################################
- id: 'salle_de_douche_light'
  alias: Area - Salle de douche - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.dressing_light_switch_l1 #light.salle_de_douche_lumieres
      adaptive_lighting: switch.adaptive_lighting_salle_de_douche
      motion_sensor: binary_sensor.anyone_home
      only_turn_off: true   
      no_motion_wait:
        minutes: 5
      no_motion_warning: 30
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.dressing_light_switch_touchfield_1
          - binary_sensor.shower_light_switch_touchfield_2
        from: ["off"]
        to: ["on"]
        id: toggle

################################################################################
- id: 'salle_de_douche_light_switch'
  alias: Area - Salle de douche - Bouton
  description: ''
  trigger:
  - platform: state
    entity_id: 
      - binary_sensor.shower_light_switch_long_press
      - binary_sensor.dressing_light_switch_long_press
    from: ["off"]
    to: ["on"]
    id: long_press
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: long_press
      sequence:
      - if: 
          - condition: state
            entity_id:
              - media_player.sonos_salle_de_douche
            state:
              - playing
        then:
          - service: media_player.media_stop
            entity_id:
              - media_player.sonos_salle_de_douche
        else:
          - service: script.play_mood_music
            data:
              rooms:
                - salle_de_douche
    default: []
  mode: parallel

