light:
  - platform: group
    name: Salle de bain lumieres
    unique_id: salle_de_bain_lumieres
    entities:
      - light.salle_de_bain

input_boolean:
  auto_light_kill_switch_salle_de_bain:
    name: Lumière mode manuel (salle de bain)
    initial: false
    icon: mdi:autorenew-off

automation:
################################################################################
- id: 'salle_de_bain_light'
  alias: Area - Salle de bain - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.salle_de_bain_lumieres
      adaptive_lighting: switch.adaptive_lighting_default   
      motion_sensor: binary_sensor.bathroom_presence_sensor_occupancy
      light_sensor: sensor.bathroom_presence_sensor_light_sensor
      kill_switch: input_boolean.auto_light_salle_de_bain
      lux_cutoff: 30
      lux_sun_cutoff: 200 
      no_motion_wait:
        minutes: 1
      no_motion_warning: 30
      toggle_trigger:
        platform: state
        entity_id: 
          - binary_sensor.bathroom_light_switch_touchfield_1
        from: ["off"]
        to: ["on"]
        id: toggle

################################################################################
- id: 'salle_de_bain_light_switch'
  alias: Area - Salle de bain - Bouton
  description: ''
  use_blueprint:
    path: antorfr/tx_ultimate.yaml
    input:
      swipe_right: binary_sensor.bathroom_light_switch_swipe_right
      touchfield_1: binary_sensor.bathroom_light_switch_touchfield_1
      touchfield_2: binary_sensor.bathroom_light_switch_touchfield_2
      long_press: binary_sensor.bathroom_light_switch_long_press
      multi_touch: binary_sensor.bathroom_light_switch_multi_touch
      swipe_left: binary_sensor.bathroom_light_switch_swipe_left


################################################################################
homeassistant:
  customize:
   binary_sensor.bathroom_presence_sensor_occupancy:
      room_main: occupancy
