binary_sensor:
  - platform: group
    name: "Salle a manger Capteurs mouvement"
    device_class: occupancy
    unique_id: salle_a_manger_motion_sensors
    all: false
    entities:
      - binary_sensor.salle_a_manger_capteur_mouvement_occupancy
      - binary_sensor.presence_sensor_dining_occupancy

template:
  - sensor:
    - unique_id: temperature_salle_a_manger
      name: Salle à manger temperature 
      device_class: temperature
      unit_of_measurement: "°C"
      availability: "{{states('climate.netatmo_salle_a_manger') != 'unknown'}}"
      state: "{{ state_attr('climate.netatmo_salle_a_manger', 'current_temperature')|float | d(none) }}"

sensor:
  - name: mouvement_salle_a_manger_5min
    platform: history_stats
    entity_id: binary_sensor.salle_a_manger_capteurs_mouvement
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

input_boolean:
  auto_light_kill_switch_salle_a_manger:
    name: Lumière mode manuel (salle à manger)
    initial: false
    icon: mdi:autorenew-off


script:
  light_scene_salle_a_manger:
    alias: Ambiance salle à manger
    fields:
      scene:
        selector:
          select:
            options: 
              - Lego
              - Standard
        name: Scene
        required: true
        default: Standard
    description: ""
    icon: mdi:lamps
    sequence:
      - choose:
          - alias: Lego
            conditions:
              - condition: template
                value_template: "{{scene == 'Lego'}}"
            sequence:
              - action: switch.turn_off
                target:
                  entity_id: switch.adaptive_lighting_salle_a_manger
              - action: hue.activate_scene
                target:
                  entity_id: scene.salle_a_manger_lumineux
                data:
                  brightness: 255
        default:
          - action: switch.turn_on
            target:
              entity_id: switch.adaptive_lighting_salle_a_manger                
          - action: light.turn_on
            target:
              entity_id: light.salle_a_manger


automation:
################################################################################
- id: salle-a-manger_light_auto
  alias: Area - Salle à manger - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.salle_a_manger
      motion_sensor: binary_sensor.salle_a_manger_capteurs_mouvement
      no_motion_wait:
        minutes: 20
      no_motion_warning: 30
      only_during_night: false
      light_sensor: sensor.presence_sensor_dining_light_sensor
      lux_cutoff: 30
      lux_sun_cutoff: 100
      adaptive_lighting: switch.adaptive_lighting_salle_a_manger
      kill_switch: input_boolean.auto_light_salle_a_manger
      toggle_trigger:
        platform: state
        entity_id: binary_sensor.garden_light_front_bouton
        from: ["on","off"]
        to: ["on","off"]
        id: toggle
################################################################################

homeassistant:
  customize:
   binary_sensor.salle_a_manger_capteurs_mouvement:
      room_main: occupancy
