
sensor:
  - name: mouvement_salle_a_manger_5min
    platform: history_stats
    entity_id: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: salle-a-manger_light_auto
  alias: Area - Salle à manger - Lumière auto
  description: ''
  # If motion is detected within the delay,
  # we restart the script.
  mode: restart
  max_exceeded: silent

  trigger:
    - platform: state
      entity_id: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
      to: 'on'
      id: 'on'
    - platform: state
      entity_id: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
      to: 'off'
      for:
        minutes: 40
      id: 'off'

  #condition:
  # condition: numeric_state
  #  entity_id: sensor.lumi_lumi_sensor_motion_aq2_illuminance
  #  below: 50
  condition:
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 'on' 
          - condition: state
            entity_id: sun.sun
            state: "below_horizon"
          - condition: state
            entity_id: light.salle_a_manger
            state: "off"
      - condition: and
        conditions:
          - condition: trigger
            id: 'off' 
          - condition: state
            entity_id: light.salle_a_manger
            state: 'on'  

  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - choose:
          - conditions:
            - condition: state
              entity_id: switch.adaptive_lighting_salle_a_manger
              state: 'on'
            sequence:
            - service: adaptive_lighting.apply
              entity_id: switch.adaptive_lighting_salle_a_manger
              data:
                lights:
                  - light.salle_a_manger
                turn_on_lights: true
        default:
            - service: light.turn_on
              target: 
                entity_id:
                  - light.salle_a_manger

      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
          to: "off"
          for: "00:30:00"
  - service: light.turn_off
    target: 
      entity_id:
        - light.salle_a_manger
################################################################################