light:
  - platform: group
    name: Salle de douche lumieres
    entities:
      - light.dressing_plafonnier
      - light.salle_de_douche_plafonnier

automation:
################################################################################
- id: 'salle_de_douche_bouton_light'
  alias: Area - Salle de douche - Bouton Lumière
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: a6f8505efa0f2a49cd2b59f18df944a7
    type: action
    subtype: on_press
    discovery_id: 0x001788010872dc24 action_on_press
    id: turn_on
  - platform: device
    domain: mqtt
    device_id: a6f8505efa0f2a49cd2b59f18df944a7
    type: action
    subtype: off_press
    discovery_id: 0x001788010872dc24 action_off_press
    id: turn_off
  condition: []
  action:
  - choose:
    - alias: "Turn on pressed" 
      conditions:
        - condition: trigger
          id: turn_on
      sequence:
        - choose:
          - conditions: '{{is_state("switch.adaptive_lighting_default","on")}}'
            sequence:
              - service: adaptive_lighting.apply
                entity_id: switch.adaptive_lighting_default
                data:
                  lights: light.salle_de_douche_lumieres
                  turn_on_lights: true
          default:
              - service: light.turn_on
                target: light.salle_de_douche_lumieres
    - alias: "Turn off pressed"
      conditions:
        - condition: trigger
          id: 'turn_off'
      sequence:
        - service: light.turn_off
          target: light.salle_de_douche_lumieres
  mode: restart