
sensor:
  - name: mouvement_salle_a_manger_5min
    platform: history_stats
    entity_id: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: salle-a-manger_light_auto
  alias: Area - Salle à manger - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.salle_a_manger
      motion_sensor: binary_sensor.salle_a_manger_capteur_mouvement_occupancy
      no_motion_wait:
        minutes: 40
      no_motion_warning: 30
      only_during_night: true
      light_sensor:
      lux_cutoff:
      adaptive_lighting: switch.adaptive_lighting_salle_a_manger
################################################################################