
automation:
################################################################################
- id: salle-a-manger_light_auto
  alias: Area - Salle à manger - Lumière auto
  description: ''
  # If motion is detected within the delay,
  # we restart the script.
  mode: restart
  max_exceeded: silent

  trigger:
    platform: state
    entity_id: binary_sensor.mouvement_salle_a_manger
    from: "off"
    to: "on"

  #condition:
  # condition: numeric_state
  #  entity_id: sensor.lumi_lumi_sensor_motion_aq2_illuminance
  #  below: 50
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: sun.sun
          state: "below_horizon"
        - condition: state
          entity_id: light.salle_a_manger
          state: "off"

  action:
  - choose:
      - conditions:
        - condition: state
          entity_id: switch.adaptive_lighting_salle_a_manger
          state: 'on'
        sequence:
        - service: adaptive_lighting.apply
          entity_id: switch.adaptive_lighting_salle_a_manger
          data:
            lights:
              - light.salle_a_manger
            turn_on_lights: true
    default:
        - service: light.turn_on
          target: 
            entity_id:
              - light.salle_a_manger

  - wait_for_trigger:
      platform: state
      entity_id: binary_sensor.mouvement_salle_a_manger
      from: "on"
      to: "off"
  - delay: "00:30:00"
  - service: light.turn_off
    target: 
      entity_id:
        - light.salle_a_manger
################################################################################