light:
  - platform: group
    name: Salon lumieres
    entities:
      - light.salon
      - light.salon_led_buffet
  
sensor:
  - platform: history_stats
    name: Durée Tv aujourd'hui
    entity_id: media_player.tv01
    state: "on"
    type: time
    start: "{{ now().replace(hour=6, minute=0, second=0) }}"
    end: "{{ now().replace(hour=21, minute=0, second=0) }}"
  - platform: history_stats
    name: Durée Apple Tv aujourd'hui
    entity_id: media_player.apple_tv_salon
    state: "playing"
    type: time
    start: "{{ now().replace(hour=6, minute=0, second=0) }}"
    end: "{{ now().replace(hour=21, minute=0, second=0) }}"

  - name: mouvement_salon_5min
    platform: history_stats
    entity_id: binary_sensor.camera_salon
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"


    