light:
  - platform: group
    name: Salon lumieres
    entities:
      - light.salon
      - light.salon_led_buffet

group:
  salon_sensors:
    name: Capteurs mouvement salon
    all: false
    entities:
      - binary_sensor.camera_salon
      - binary_sensor.salon_capteur_mouvement_occupancy
  
sensor:
  - platform: history_stats
    name: Durée Tv aujourd'hui
    entity_id: media_player.tv01
    state: "on"
    type: time
    start: "{{ now().replace(hour=6, minute=0, second=0) }}"
    end: "{{ now().replace(hour=21, minute=0, second=0) }}"
  - platform: history_stats
    name: Durée Apple Tv aujourd'hui
    entity_id: media_player.apple_tv_salon
    state: "playing"
    type: time
    start: "{{ now().replace(hour=6, minute=0, second=0) }}"
    end: "{{ now().replace(hour=21, minute=0, second=0) }}"

  - name: mouvement_salon_5min
    platform: history_stats
    entity_id: group.salon_sensors
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: 'salon_light_auto'
  alias: Area - Salon - Lumière auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: state
      entity_id: binary_sensor.salon_capteur_mouvement_occupancy
      to: "on"
      id: "on"
    - platform: state
      entity_id: binary_sensor.salon_capteur_mouvement_occupancy
      to: "off"
      for:
        minutes: 60
      id: "off"

  condition:
    - condition: or
      conditions:
      - condition: and
        conditions:
          - condition: trigger
            id: 'on' 
          - condition: numeric_state
            entity_id: sensor.salon_capteur_luminosite_illuminance_lux
            below: 60
          - condition: state
            entity_id: light.salon_lumieres
            state: 'off'
      - condition: and
        conditions:
          - condition: trigger
            id: 'off' 
          - condition: state
            entity_id: light.salon_lumieres
            state: 'on'        

  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 'on'
      sequence:
      - choose:
          - conditions:
            - condition: state
              entity_id: switch.adaptive_lighting_salon
              state: 'on'
            sequence:
            - service: adaptive_lighting.apply
              entity_id: switch.adaptive_lighting_salon
              data:
                lights:
                  - light.salon_lumieres
                turn_on_lights: true
        default:
            - service: light.turn_on
              target: 
                entity_id: light.salon_lumieres
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.salon_capteur_mouvement_occupancy
          to: "off"
          for:
            minutes: 30
  - service: light.turn_off
    target: 
      entity_id: light.salon_lumieres
################################################################################

    