sensor:
  - name: mouvement_wc_floor_5min
    platform: history_stats
    entity_id: binary_sensor.blumotion_toilettes_etage_motion
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: toilettes_etage_light_auto
  alias: Area - Toilettes Etage - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.toilette_etage
      motion_sensor: binary_sensor.blumotion_toilettes_etage_motion
      no_motion_wait:
        minutes: 3
      no_motion_warning: 30
      adaptive_lighting: switch.adaptive_lighting_default
      only_during_night: false
      toggle_trigger:
        trigger: state
        entity_id: binary_sensor.restroom_1floor_light_bouton
        from: ["on","off"]
        to: ["on","off"]
        id: toggle
################################################################################

