binary_sensor:
  - platform: group
    name: "Capteurs mouvement toilettes RdC"
    device_class: occupancy
    unique_id: toilettes_rdc_motion_sensors
    all: false
    entities:
      - binary_sensor.blumotion_toilettes_rdc_motion
sensor:
  - name: mouvement_wc_rdc_5min
    platform: history_stats
    entity_id: binary_sensor.capteurs_mouvement_toilettes_rdc
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: toilettes_rdc_light_auto
  alias: Area - Toilettes RdC - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.toilettes_rdc
      motion_sensor: binary_sensor.capteurs_mouvement_toilettes_rdc
      no_motion_wait:
        minutes: 3
      no_motion_warning: 30
      adaptive_lighting: switch.adaptive_lighting_default
      only_during_night: false
      toggle_trigger:
        trigger: state
        entity_id: binary_sensor.restroom_groundfloor_light_bouton
        from: ["on","off"]
        to: ["on","off"]
        id: toggle
################################################################################

#########################################
homeassistant:
  customize:
   binary_sensor.capteurs_mouvement_toilettes_rdc:
      room_main: occupancy
