sensor:
  - name: mouvement_wc_rdc_5min
    platform: history_stats
    entity_id: binary_sensor.toilettes_rdc_capteur_de_mouvement_occupancy
    state: "on"
    type: time
    duration: 00:05:00
    end: "{{now()}}"

automation:
################################################################################
- id: toilettes_rdc_light_auto
  alias: Area - Toilettes RdC - Lumière auto
  description: ''
  use_blueprint:
    path: antorfr/motion_light.yaml
    input:
      light_target:
        entity_id: light.toilettes_rdc
      motion_sensor: binary_sensor.toilettes_rdc_capteur_de_mouvement_occupancy
      no_motion_wait:
        minutes: 3
      no_motion_warning: 30
      adaptive_lighting: switch.adaptive_lighting_default
      only_during_night: false
      toggle_trigger:
        platform: state
        entity_id: binary_sensor.restroom_groundfloor_light_status
        from: ["on","off"]
        to: ["on","off"]
        id: toggle
################################################################################