
input_boolean:
  away_mode:
    name: Mode absence
    icon: mdi:home-export-outline




automation:
################################################################################
- id: 'routine_detect_away'
  alias: Routine - Away - Detect Absence
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.away_mode

################################################################################
- id: 'routine_detect_home'
  alias: Routine - Away - Detect Retour
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.away_mode

################################################################################
- id: 'routine_away'
  alias: Routine - Away - Absence
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition: []
  action:
    - service: script.routine_away
      data: {}
    - alias: "Fire Away routine"
      event: routine_event
      event_data:
        type: away
################################################################################
- id: 'routine_home'
  alias: Routine - Away - Retour
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition: []
  action:
    - service: script.routine_back_home
      data: {}
    - alias: "Fire back home routine"
      event: routine_event
      event_data:
        type: home
################################################################################



script:
################################################################################
  routine_away:
    alias: Routine - Absence
    sequence:
    - service: notify.mobile_app_intra_mob08
      data:
        message: Au revoir
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_all_light_turn_off
          - script.routine_all_media_player_off
          - script.routine_all_power_device_off
          - script.routine_all_cover_close
################################################################################
  routine_back_home:
    alias: Routine - Retour maison
    sequence:
    - service: notify.mobile_app_intra_mob08
      data:
        message: Bienvenue à la maison 
    - service: script.turn_on
      target:
        entity_id: script.routine_all_power_device_on
    - alias: "If sun is up"
      choose:
      - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.routine_all_cover_open

      
################################################################################
  routine_all_light_turn_off:
    alias: Routine - All light off
    sequence:
    - service: light.turn_off
      target:
        area_id:
        - bureau
        - chambre_parent
        - chambre_timothee
        - chambre_emilie
        - couloir_etage
        - cuisine
        - entree
        - toilettes_etage
        - couloir_etage
        - vestibule
        - salle_de_bain
        - salle_a_manger
        - toilettes_rdc
        - toilettes_etage
        - piscine
        - garage
        entity_id:
        - light.salon
        - light.salon_led_buffet
        - light.plafonnier_entree

################################################################################
  routine_all_media_player_off:
    alias: Routine - All Media player off
    sequence:
    - service: media_player.media_stop
      target:
        area_id:
        - bureau
        - chambre_timothee
        - chambre_emilie
        - cuisine
        - salle_de_bain
        - salle_de_douche
        - salle_a_manger
        entity_id: media_player.salon_2
################################################################################
  routine_all_power_device_off:
    alias: Routine - All power saving device off
    sequence:
    - service: switch.turn_off
      target:
        entity_id:
        - switch.couverture_laurine
        - switch.couverture_seb
        - switch.prise_emilie
        - switch.piscine_chauffe_eau

################################################################################
  routine_all_power_device_on:
    alias: Routine - All power saving device off
    sequence:
    - service: switch.turn_off
      target:
        entity_id:
        - switch.mezzanine_prise

################################################################################
  routine_all_cover_close:
    alias: Routine - Close all cover
    sequence:
    - service: cover.close_cover
      target:
        area_id:
        - cuisine
        - salon
        - salle_a_manger
        - chambre_parent
        - chambre_timothee
        - chambre_emilie
        - chambre_d_amis

################################################################################
  routine_all_cover_open:
    alias: Routine - Open all cover
    sequence:
    - service: cover.open_cover
      target:
        area_id:
        - cuisine
        - salon
        - salle_a_manger
        - chambre_parent
        - chambre_timothee
        - chambre_emilie
        - chambre_d_amis