
input_boolean:
  away_mode:
    name: Mode absence
    icon: mdi:home-export-outline
  long_absence_mode:
    name: Absence longue
    icon: mdi:beach

input_datetime:
  long_absence_return_date:
    name: Date retour
    has_date: true
    has_time: false

automation:
################################################################################
- id: 'routine_detect_away'
  alias: Routine - Away - Detect Absence
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
      for:
        minutes: 10
    - alias: "ios action Je sors"
      platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "Depart Maison"
  condition:
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - action: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.away_mode
################################################################################
- id: 'routine_detect_home'
  alias: Routine - Away - Detect Retour
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'on'
    - alias: "ios action Je rentre"
      platform: event
      event_type: ios.action_fired
      event_data:
        actionName: "Retour Maison"
  condition: 
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'on'
  action:
    - action: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.away_mode
################################################################################
- id: 'routine_away'
  alias: Routine - Away - Absence
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
  condition: []
  action:
    - action: script.routine_away
      data: {}
    - alias: "Fire Away routine"
      event: routine_event
      event_data:
        type: away
################################################################################
- id: 'routine_long_absence'
  alias: Routine - Away - Absence longue
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: "off"
      to: 'on'
      for:
        hours: 24
    - platform: state
      entity_id: input_boolean.long_absence_mode
      from: "off"
      to: 'on'
      
  condition: []
  action:
    - action: input_boolean.turn_on
      target:
        entity_id: 
          - input_boolean.long_absence_mode
          - input_boolean.away_mode
    - action: script.routine_long_absence
      data: {}
    - alias: "Fire long absence routine"
      event: routine_event
      event_data:
        type: long_absence
################################################################################
- id: 'routine_prepare_home'
  alias: Routine - Away - Prepare le retour
  description: ''
  trigger:
    - platform: time
      at: input_datetime.long_absence_return_date
      id: date
    - platform: state
      entity_id: input_boolean.long_absence_mode
      from: "on"
      to: 'off'
      id: button
  condition: 
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.long_absence_mode
          state: 'on'
        - condition: trigger
          id: 'button'
  action:
    - action: input_boolean.turn_off
      target:
        entity_id: 
          - input_boolean.long_absence_mode
    - action: script.routine_prepare_home
      data: {}
    - alias: "Fire back home routine"
      event: routine_event
      event_data:
        type: prepare_home
################################################################################
- id: 'routine_home'
  alias: Routine - Away - Retour
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
  condition: []
  action:
    - action: input_boolean.turn_off
      target:
        entity_id: 
          - input_boolean.long_absence_mode
          - input_boolean.away_mode
    - action: script.routine_back_home
      data: {}
    - alias: "Fire back home routine"
      event: routine_event
      event_data:
        type: home

script:
################################################################################
  routine_away:
    alias: Routine - Absence
    sequence:
    - action: notify.mobile_seb
      data:
        message: Au revoir
    - parallel: 
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_light_turn_off
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_media_player_off
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_away_all_power_device_off
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_cover_close
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_garage_door_close
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_lock_lock
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_climate_away
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_away_settings
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_reset_lightning_settings

################################################################################
  routine_back_home:
    alias: Routine - Retour maison
    sequence:
    - action: notify.mobile_seb
      data:
        message: Bienvenue à la maison 
    - parallel: 
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_power_device_on
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_all_lock_unlock
      - action: script.turn_on
        continue_on_error: true
        target:
          entity_id: 
            - script.routine_climate_home
    - alias: "If sun is up"
      choose:
      - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        sequence:
          - action: script.turn_on
            continue_on_error: true
            target:
              entity_id: script.routine_all_cover_open
################################################################################
  routine_long_absence:
    alias: Routine - Absence longue
    sequence:
    - action: notify.mobile_seb
      data:
        message: Mode absence longue actif
    - action: script.turn_on
      target:
        entity_id: 
          - script.routine_climate_long_absence
################################################################################
  routine_prepare_home:
    alias: Routine - prepare retour
    sequence:
    - action: notify.mobile_seb
      data:
        message: Je prépare la maison 
    - action: script.turn_on
      target:
        entity_id: 
          - script.routine_climate_home

      
