
input_boolean:
  away_mode:
    name: Mode absence
    icon: mdi:home-export-outline


automation:
################################################################################
- id: 'routine_detect_away'
  alias: Routine - Away - Detect Absence
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'off'
      for:
        minutes: 10
  condition:
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.away_mode

################################################################################
- id: 'routine_detect_home'
  alias: Routine - Away - Detect Retour
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.anyone_home
      to: 'on'
  condition: 
    - condition: state
      entity_id: input_boolean.away_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.away_mode

################################################################################
- id: 'routine_away'
  alias: Routine - Away - Absence
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
  condition: []
  action:
    - service: script.routine_away
      data: {}
    - alias: "Fire Away routine"
      event: routine_event
      event_data:
        type: away
################################################################################
- id: 'routine_home'
  alias: Routine - Away - Retour
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      to: 'off'
  condition: []
  action:
    - service: script.routine_back_home
      data: {}
    - alias: "Fire back home routine"
      event: routine_event
      event_data:
        type: home
################################################################################



script:
################################################################################
  routine_away:
    alias: Routine - Absence
    sequence:
    - service: notify.mobile_seb
      data:
        message: Au revoir
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_all_light_turn_off
          - script.routine_all_media_player_off
          - script.routine_away_all_power_device_off
          - script.routine_all_cover_close
          - script.routine_all_garage_door_close
          - script.routine_away_settings
################################################################################
  routine_back_home:
    alias: Routine - Retour maison
    sequence:
    - service: notify.mobile_seb
      data:
        message: Bienvenue à la maison 
    - service: script.turn_on
      target:
        entity_id: script.routine_all_power_device_on
    - alias: "If sun is up"
      choose:
      - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.routine_all_cover_open



      
