automation:
###############################################
- id: routine_daylight_light
  alias: Function - Cadre Timothee - Auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: event
      event_type: routine_event
      event_data:
        type: evening
      id: evening
    - platform: event
      event_type: routine_event
      event_data:
        type: children evening ritual
      id: children evening ritual
    - platform: event
      event_type: routine_event
      event_data:
        type: children night
      id: children night
    - platform: event
      event_type: routine_event
      event_data:
        type: children morning
      id: children morning
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: night
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: morning

  action:
  - choose:
    - alias: "Evening - Start sleep ritual"
      conditions:
        - condition: trigger
          id: evening
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_timothee
          data:
            brightness_pct: 100
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 100
            effect: autoPlay
        - service: light.turn_off
          target:
            entity_id: 
              - light.cadre_lumineux_lune
              - light.cadre_lumineux_etoiles
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_soleil
          data:
            effect: color
            rgb_color: [255,127,0]
    - alias: "Evening - Almost sleep time"
      conditions:
        - condition: trigger
          id: children evening ritual
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_timothee
          data:
            brightness_pct: 50
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 50
            effect: autoPlay
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_soleil
          data:
            effect: color
            rgb_color: [255,0,0]
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_lune
          data:
            effect: snowTwinkles
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_etoiles
          data:
            effect: star
            rgb_color: [255,255,255]
        - choose:
            - conditions:
                - condition: state
                  entity_id: light.plafonnier_timothee
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: light.plafonnier_timothee
                  data:
                    brightness_pct: 10
    - alias: "Evening - Children Sleep time"
      conditions:
        - condition: trigger
          id: children night
      sequence:
        - service: light.turn_on
          target:
            entity_id: 
              - light.cadre_lumineux_timothee
              - light.veilleuse_timothee
          data:
            brightness_pct: 10
        - service: light.turn_off
          target:
            entity_id: light.cadre_lumineux_soleil
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_lune
          data:
            effect: color
            rgb_color: [255,255,255]
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_etoiles
          data:
            effect: star
            rgb_color: [255,255,255]
    - alias: "Evening - Night (parent sleep)"
      conditions:
        - condition: trigger
          id: night
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_timothee
          data:
            brightness_pct: 8
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 8
            effect: color
            rgb_color: [255,0,0]
        - service: light.turn_off
          target:
            entity_id: light.cadre_lumineux_soleil
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_lune
          data:
            effect: color
            rgb_color: [255,255,255]
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_etoiles
          data:
            effect: star
            rgb_color: [255,255,255]
    - alias: "Morning - Children morning"
      conditions:
        - condition: trigger
          id: children morning
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_timothee
          data:
            brightness_pct: 20
        - service: light.turn_on
          target:
            entity_id: light.cadre_lumineux_soleil
          data:
            effect: color
            rgb_color: [255,255,255]
        - service: light.turn_off
          target:
            entity_id: 
              - light.cadre_lumineux_lune
              - light.cadre_lumineux_etoiles
  ###############################################

  ###############################################
- id: routine_emilie_clock
  alias: Routine - Horloge Emilie - Auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: event
      event_type: routine_event
      event_data:
        type: evening
      id: evening
    - platform: event
      event_type: routine_event
      event_data:
        type: children evening ritual
      id: children evening ritual
    - platform: event
      event_type: routine_event
      event_data:
        type: children night
      id: children night
    - platform: event
      event_type: routine_event
      event_data:
        type: children morning
      id: children morning
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: night
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: morning
    - platform: event
      event_type: routine_event
      event_data:
        type: home
      id: 'come-back'
    - platform: event
      event_type: routine_event
      event_data:
        type: away
      id: 'leaving'

  action:
  - choose:
    - alias: "Evening - Start sleep ritual"
      conditions:
        - condition: trigger
          id: evening
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 100
            effect: rainbowClock
          target:
            entity_id: light.horloge_emilie
    - alias: "Evening - Almost sleep time"
      conditions:
        - condition: trigger
          id: children evening ritual
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 50
            effect: clock
            color_name: red
          target:
            entity_id: light.horloge_emilie
        - choose:
            - conditions:
                - condition: state
                  entity_id: light.plafonnier_emilie
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: light.plafonnier_emilie
                  data:
                    brightness_pct: 10
    - alias: "Evening - Children Sleep time"
      conditions:
        - condition: trigger
          id: children night
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 10
            effect: clock
            color_name: red
          target:
            entity_id: light.horloge_emilie
    - alias: "Evening - Night (parent sleep)"
      conditions:
        - condition: trigger
          id: night
      sequence:
        - service: light.turn_off
          target:
            entity_id: light.horloge_emilie
    - alias: "Morning - Children morning"
      conditions:
        - condition: trigger
          id: children morning
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 100
            effect: rainbowClock
          target:
            entity_id: light.horloge_emilie
  ###############################################