automation:
###############################################
- id: routine_daylight_light
  alias: Function - Cadre Timothee - Auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: event
      event_type: routine_event
      event_data:
        type: evening
      id: evening
    - platform: event
      event_type: routine_event
      event_data:
        type: children evening ritual
      id: children evening ritual
    - platform: event
      event_type: routine_event
      event_data:
        type: children night
      id: children night
    - platform: event
      event_type: routine_event
      event_data:
        type: children morning
      id: children morning
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: night
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: morning

  action:
  - choose:
    - alias: "Evening - Start sleep ritual"
      conditions:
        - condition: trigger
          id: evening
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 100
            effect: autoPlay
    - alias: "Evening - Almost sleep time"
      conditions:
        - condition: trigger
          id: children evening ritual
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 50
            effect: autoPlay
        - choose:
            - conditions:
                - condition: state
                  entity_id: light.plafond_timothee
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: light.plafond_timothee
                  data:
                    brightness_pct: 30
    - alias: "Evening - Children Sleep time"
      conditions:
        - condition: trigger
          id: children night
      sequence:
        - service: light.turn_on
          target:
            entity_id: 
              - light.veilleuse_timothee
          data:
            brightness_pct: 10
    - alias: "Evening - Night (parent sleep)"
      conditions:
        - condition: trigger
          id: night
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.veilleuse_timothee
          data:
            brightness_pct: 8
            effect: color
            rgb_color: [255,0,0]
    - alias: "Morning - Children morning"
      conditions:
        - condition: trigger
          id: children morning
      sequence: []
###############################################
- id: routine_emilie_clock
  alias: Routine - Horloge Emilie - Auto
  description: ''

  mode: restart
  max_exceeded: silent

  trigger:
    - platform: event
      event_type: routine_event
      event_data:
        type: evening
      id: evening
    - platform: event
      event_type: routine_event
      event_data:
        type: children evening ritual
      id: children evening ritual
    - platform: event
      event_type: routine_event
      event_data:
        type: children night
      id: children night
    - platform: event
      event_type: routine_event
      event_data:
        type: children morning
      id: children morning
    - platform: event
      event_type: routine_event
      event_data:
        type: night
      id: night
    - platform: event
      event_type: routine_event
      event_data:
        type: morning
      id: morning
    - platform: event
      event_type: routine_event
      event_data:
        type: home
      id: 'come-back'
    - platform: event
      event_type: routine_event
      event_data:
        type: away
      id: 'leaving'

  action:
  - choose:
    - alias: "Evening - Start sleep ritual"
      conditions:
        - condition: trigger
          id: evening
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 100
            effect: rainbowClock
          target:
            entity_id: light.horloge_emilie
    - alias: "Evening - Almost sleep time"
      conditions:
        - condition: trigger
          id: children evening ritual
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 50
            effect: clock
            color_name: red
          target:
            entity_id: light.horloge_emilie
        - choose:
            - conditions:
                - condition: state
                  entity_id: light.chambre_emilie_plafonnier
                  state: "on"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: light.chambre_emilie_plafonnier
                  data:
                    brightness_pct: 10
    - alias: "Evening - Children Sleep time"
      conditions:
        - condition: trigger
          id: children night
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 10
            effect: clock
            color_name: red
          target:
            entity_id: light.horloge_emilie
    - alias: "Evening - Night (parent sleep)"
      conditions:
        - condition: trigger
          id: night
      sequence:
        - service: light.turn_off
          target:
            entity_id: light.horloge_emilie
    - alias: "Morning - Children morning"
      conditions:
        - condition: trigger
          id: children morning
        - condition: state
          entity_id: binary_sensor.workday_sensor
          state: 'on'
      sequence:
        - service: light.turn_on
          data:
            brightness_pct: 100
            effect: rainbowClock
          target:
            entity_id: light.horloge_emilie
###############################################
- id: routine_children_bus_time_warning
  alias: Routine - enfants - rappel départ école
  mode: restart
  trigger:
    - platform: calendar
      event: start
      offset: "-0:30:0"
      entity_id: calendar.morning_notifications
    - platform: calendar
      event: start
      offset: "-0:15:0"
      entity_id: calendar.morning_notifications
    - platform: calendar
      event: start
      offset: "-0:10:0"
      entity_id: calendar.morning_notifications
    - platform: calendar
      event: start
      offset: "-0:05:0"
      entity_id: calendar.morning_notifications
    - platform: calendar
      event: start
      entity_id: calendar.morning_notifications
  condition: []
  action:
    - service: "script.bus_time_warning"
      data:
          media_players: 
              - media_player.emilie
              - media_player.timothee
              - media_player.salle_a_manger
          event:
            start: "{{trigger.calendar_event.start}}"
            end: "{{trigger.calendar_event.end}}"
            summary: "{{trigger.calendar_event.summary}}"
            description: "{{trigger.calendar_event.description}}"
          test: "{{trigger.calendar_event}}"

