binary_sensor:
  - platform: workday
    country: FR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
  - platform: workday
    name: workday_tomorrow
    days_offset: 1
    country: FR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

input_boolean:
  night_mode:
    name: Mode nuit
    icon: mdi:weather-night
    
input_select:
  day_phase:
    name: "Phase de la journée"
    options:
      - Aurore
      - "Matin - reveil enfants"
      - Matin
      - Après-midi
      - Soirée
      - "Soirée - retour au calme"
      - "Soirée - enfants couché"
      - Nuit
    icon: mdi:hours-24

input_datetime:
  morning_time:
    name: Matin
    has_time: true
  morning_time_we:
    name: Matin - weekend
    has_time: true
  afternoon_time:
    name: Après midi
    has_time: true
  evening_time:
    name: Soirée
    has_time: true
  evening_time_we:
    name: Soirée - weekend
    has_time: true
  children_morning_time:
    name: Reveil enfants
    has_time: true
    icon: mdi:clock-digital
  children_morning_time_we:
    name: Reveil enfants - weekend
    has_time: true
    icon: mdi:clock-digital
  children_evening_ritual_time:
    name: Soirée - retour au calme
    has_time: true
  children_evening_ritual_time_we:
    name: Soirée (we) - retour au calme
    has_time: true
  children_night_time:
    name: Soirée - enfants couché
    has_time: true
  children_night_time_we:
    name: Soirée (we) - enfants couché
    has_time: true
################################################################################

################################################################################
automation:
################################################################################
- id: 'routine_manual'
  alias: Routine - Day - Manuel
  description: ''
  variables:
    day_phase:
      Aurore: aurore
      "Matin - reveil enfants": children morning
      Matin: morning
      Après-midi: after-noon
      Soirée: evening
      "Soirée - retour au calme": children evening ritual
      "Soirée - enfants couché": children night
      Nuit: night

  trigger:
  - platform: state
    entity_id: input_select.day_phase
  condition: []
  action:
  - alias: "Fire routine_event"
    event: routine_event
    event_data:
      type: "{{ day_phase[trigger.to_state.state]}}"

  mode: single

################################################################################
- id: 'routine_evening'
  alias: Routine - Day - Soirée
  description: ''
  trigger:
  - platform: time
    at: input_datetime.evening_time
    id: week
  - platform: time
    at: input_datetime.evening_time_we
    id: weekend   
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id: week
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id: weekend
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'off'     
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: evening
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: Soirée
  - alias: "desable adaptative light during diner"
    service: switch.turn_off
    target:
      entity_id: switch.adaptive_lighting_salle_a_manger
  mode: single

################################################################################
- id: 'routine_after-noon'
  alias: Routine - Day - Après-midi
  description: ''
  trigger:
  - platform: time
    at: input_datetime.afternoon_time
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'     
  action:
  - alias: "Fire after-noon routine event"
    event: routine_event
    event_data:
      type: after-noon
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: Après-midi
  mode: single
################################################################################
- id: 'routine_children_evening_ritual'
  alias: Routine - Day - Children evening ritual
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_evening_ritual_time
    id: week
  - platform: time
    at: input_datetime.children_evening_ritual_time_we
    id: weekend
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id: week
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id: weekend
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'off' 
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: children evening ritual
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: "Soirée - retour au calme"
  - service: script.turn_on
    target:
      entity_id: script.routine_children_cover_workday

################################################################################
- id: 'routine_children_night'
  alias: Routine - Day - Children night
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_night_time
    id: week
  - platform: time
    at: input_datetime.children_night_time_we
    id: weekend
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id: week
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id: weekend
      - condition: state
        entity_id: binary_sensor.workday_tomorrow
        state: 'off' 
  action:
  - alias: "Fire children night routine event"
    event: routine_event
    event_data:
      type: children night
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option:  "Soirée - enfants couché"
  - alias: "enable adaptative light in dinning room"
    service: switch.turn_on
    target:
      entity_id: switch.adaptive_lighting_salle_a_manger
  - service: switch.turn_on
    target:
      entity_id: switch.adaptive_lighting_sleep_mode_couloir_etage

################################################################################
- id: 'routine_children_morning'
  alias: Routine - Day - Children morning
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_morning_time
    id: week
  - platform: time
    at: input_datetime.children_morning_time
    id: weekend
  condition:
  - condition: state
    entity_id: input_boolean.away_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id: week
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'on'
    - condition: and
      conditions:
      - condition: trigger
        id: weekend
      - condition: state
        entity_id: binary_sensor.workday_sensor
        state: 'off' 
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: children morning
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: "Matin - reveil enfants"

################################################################################
- id: 'routine_detect_morning'
  alias: Routine - Day - Detect Matin
  description: 'Routine matin'
  trigger:
  - platform: time
    at: input_datetime.morning_time
    id: week
  - platform: time
    at: input_datetime.morning_time_we
    id: weekend
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    to: 'on'
    id: motion
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
          - condition: state
            entity_id: input_boolean.night_mode
            state: 'on'
          - condition: time
            after: '06:30:00'
            before: '18:00:00'
          - condition: or
            conditions:
              - condition: trigger
                id: motion
              - condition: and
                conditions:
                - condition: trigger
                  id: week
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'on'
              - condition: and
                conditions:
                - condition: trigger
                  id: weekend
                - condition: state
                  entity_id: binary_sensor.workday_sensor
                  state: 'off' 
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.night_mode
  mode: single

################################################################################
- id: 'routine_detect_night'
  alias: Routine - Day - Detect Nuit
  description: ''
  trigger:
  - platform: time
    at: '03:00:00'
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'on'
    to: 'off'
    for: 02:00:00
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
          - condition: state
            entity_id: input_boolean.night_mode
            state: 'off'
          - condition: time
            after: '22:00:00'
            before: '06:00:00'
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.night_mode
  mode: single

################################################################################
- id: 'routine_detect_aurore'
  alias: Routine - Day - Detect Aurore
  description: 'De bonne heure'
  trigger:
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'off'
    to: 'on'
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.away_mode
            state: 'off'
          - condition: state
            entity_id: input_boolean.night_mode
            state: 'on'
          - condition: time
            after: '05:00:00'
            before: '06:29:59'
  action:
  - service: script.routine_aurore
  mode: single

################################################################################
- id: 'routine_night'
  alias: Routine - Day - Nuit
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.routine_sleep_mode

################################################################################
- id: 'routine_morning'
  alias: Routine - Day - Matin
  description: ''
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition: []
  action:
    - service: script.turn_on
      target:
        entity_id: script.routine_matin
################################################################################

################################################################################
script:
################################################################################
  routine_sleep_mode:
    alias: Routine - Sleep mode
    mode: restart
    icon: mdi:weather-night
    sequence:   
    - alias: "Fire night routine event"
      event: routine_event
      event_data:
        type: night
    - service: input_select.select_option  
      target:
        entity_id: input_select.day_phase
      data:
        option: Nuit
    - service: notify.mobile_app_intra_mob08
      data:
        message: Bonne nuit
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_night_all_light_turn_off
          - script.routine_all_media_player_off
          - script.routine_night_all_power_device_off
          - script.routine_night_all_cover_close
          - script.routine_all_garage_door_close
    - delay:
        seconds: 10
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_all_light_mode_night_on
################################################################################
  routine_matin:
    alias: Routine - Matin
    sequence:
    - alias: "Fire aurore routine event"
      event: routine_event
      event_data:
        type: morning
    - service: input_select.select_option  
      target:
        entity_id: input_select.day_phase
      data:
        option: Matin
    - service: notify.mobile_app_intra_mob08
      data:
        message: Bonjour
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_all_light_mode_night_off
    - alias: "If sun is up"
      choose:
      - conditions:
        - condition: state
          entity_id: sun.sun
          state: "above_horizon"
        sequence:
          - service: script.turn_on
            target:
              entity_id: script.routine_morning_cover_open
################################################################################
  routine_aurore:
    alias: Routine - Aurore
    sequence:
    - alias: "Fire aurore routine event"
      event: routine_event
      event_data:
        type: aurore
    - service: input_select.select_option  
      target:
        entity_id: input_select.day_phase
      data:
        option: Aurore
    - service: notify.mobile_app_intra_mob08
      data:
        message: Bonjour, pas trop dure ?
    - service: script.turn_on
      target:
        entity_id: 
          - script.routine_all_light_mode_night_off
################################################################################

################################################################################
scene:
################################################################################
- id: 'scene_good_night'
  icon: mdi:weather-night
  name: Bonne nuit
  entities:
    input_boolean.night_mode:
      editable: false
      icon: mdi:weather-night
      friendly_name: Mode nuit
      state: 'on'
