binary_sensor:
  - platform: workday
    country: FR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

switch:
  - platform: template
    switches:
      night_mode:
        unique_id: night_mode
        turn_on:
          - service: script.routine_sleep_mode
            data: {}
          - service: input_select.select_option  
            target:
              entity_id: input_select.day_phase
            data:
              option: Nuit
        turn_off:
          - service: script.routine_matin
            data: {}
          - service: input_select.select_option  
            target:
              entity_id: input_select.day_phase
            data:
              option: Matin
        icon_template: >-
          {% if is_state('switch.night_mode', 'on') %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}
    
input_select:
  day_phase:
    name: "Phase de la journée"
    options:
      - Aurore
      - "Matin - reveil enfants"
      - Matin
      - Soirée
      - "Soirée - retour au calme"
      - "Soirée - enfants couché"
      - Nuit
    icon: mdi:hours-24

input_datetime:
  morning_time:
    name: Matin
    has_time: true
  evening_time:
    name: Soirée
    has_time: true
  children_morning_time:
    name: Matin - reveil enfants
    has_time: true
    icon: mdi:clock-digital
  children_evening_ritual_time:
    name: Soirée - retour au calme
    has_time: true
  children_night_time:
    name: Soirée - enfants couché
    has_time: true


automation:
################################################################################
- id: 'routine_manual'
  alias: Routine - Day - Manuel
  description: ''
  variables:
    day_phase:
      Aurore: aurore
      "Matin - reveil enfants": children morning
      Matin: morning
      Soirée: evening
      "Soirée - retour au calme": children evening ritual
      "Soirée - enfants couché": children night
      Nuit: night
    test: toto

  trigger:
  - platform: state
    entity_id: input_select.day_phase
  condition: []
  action:
  - alias: "Fire routine_event"
    event: routine_event
    event_data:
      type: "{{ day_phase[trigger.to_state.state]}}"

  mode: single
################################################################################
- id: 'routine_evening'
  alias: Routine - Day - Soirée
  description: ''
  trigger:
  - platform: time
    at: input_datetime.evening_time
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'on'
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: evening
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: Soirée
  - scene: scene.soiree
  mode: single

################################################################################

- id: 'routine_children_evening_ritual'
  alias: Routine - Day - Children evening ritual
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_evening_ritual_time
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'on'
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: children evening ritual
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: "Soirée - retour au calme"

################################################################################

- id: 'routine_children_night'
  alias: Routine - Day - Children night
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_night_time
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'on'
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: children night
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option:  "Soirée - enfants couché"

################################################################################

- id: 'routine_children_morning'
  alias: Routine - Day - Children morning
  description: ''
  trigger:
  - platform: time
    at: input_datetime.children_morning_time
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'on'
  action:
  - alias: "Fire evening routine event"
    event: routine_event
    event_data:
      type: children morning
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: "Matin - reveil enfants"

################################################################################

- id: 'routine_aurore'
  alias: Routine - Day - Aurore
  description: 'De bonne heure'
  trigger:
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'off'
    to: 'on'
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'on'
          - condition: time
            after: '05:00:00'
            before: '06:29:59'
  action:
  - alias: "Fire aurore routine event"
    event: routine_event
    event_data:
      type: aurore
  - service: input_select.select_option  
    target:
      entity_id: input_select.day_phase
    data:
      option: Aurore
  - service: script.routine_aurore
  mode: single

################################################################################
- id: 'routine_morning'
  alias: Routine - Day - Matin
  description: 'Routine matin'
  trigger:
  - platform: time
    at: input_datetime.morning_time
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    to: 'on'
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'on'
          - condition: time
            after: '06:30:00'
            before: '18:00:00'

  action:
  - alias: "Fire aurore routine event"
    event: routine_event
    event_data:
      type: morning
  - service: switch.turn_off
    target:
      entity_id: switch.night_mode
  mode: single
################################################################################

################################################################################
- id: 'routine_night'
  alias: Routine - Day - Nuit
  description: ''
  trigger:
  - platform: time
    at: '03:00:00'
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'on'
    to: 'off'
    for: 02:00:00
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'off'
          - condition: time
            after: '22:00:00'
            before: '06:00:00'
  action:
  - alias: "Fire aurore routine event"
    event: routine_event
    event_data:
      type: night
  - service: switch.turn_on
    target:
      entity_id: switch.night_mode
  mode: single
################################################################################