binary_sensor:
  - platform: workday
    country: FR
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

switch:
  - platform: template
    switches:
      night_mode:
        turn_on:
          service: script.routine_sleep_mode
          data: {}
        turn_off:
          service: script.routine_matin
          data: {}
        icon_template: >-
          {% if is_state('switch.night_mode', 'on') %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}
          

automation:
################################################################################
- id: 'routine_evening'
  alias: Routine - Day - Soirée
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition:
  - condition: state
    entity_id: binary_sensor.anyone_home
    state: 'on'
  action:
  - scene: scene.soiree
  mode: single
################################################################################

################################################################################
- id: 'routine_aurore'
  alias: Routine - Day - Aurore
  description: 'De bonne heure'
  trigger:
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'off'
    to: 'on'
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'on'
          - condition: time
            after: '05:00:00'
            before: '06:29:59'
  action:
  - service: script.routine_aurore
  mode: single

################################################################################
- id: 'routine_morning'
  alias: Routine - Day - Matin
  description: 'Routine matin'
  trigger:
  - platform: time
    at: "08:00:00"
  - platform: time
    at: "06:30:00"
    id: 'start_time'
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    to: 'on'
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'on'
          - condition: time
            after: '06:30:00'
            before: '18:00:00'
          - condition: or
            conditions:
            - condition: not
              conditions:
              - condition: trigger
                id: 'start_time'
            - condition: state
              entity_id: binary_sensor.maison_rdc_presence
              state: 'on'  
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.night_mode
  mode: single
################################################################################

################################################################################
- id: 'routine_night'
  alias: Routine - Day - Nuit
  description: ''
  trigger:
  - platform: time
    at: '03:00:00'
  - platform: state
    entity_id: binary_sensor.maison_rdc_presence
    from: 'on'
    to: 'off'
    for: 02:00:00
  condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.anyone_home
            state: 'on'
          - condition: state
            entity_id: switch.night_mode
            state: 'off'
          - condition: time
            after: '22:00:00'
            before: '06:00:00'
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.night_mode
  mode: single
################################################################################