sensor:
  - platform: integration
    source: sensor.bureau_prise_pc_1_power
    name: energy_bureau_prise_pc_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_pc_2_power
    name: energy_bureau_prise_pc_2_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_pc_3_power
    name: energy_bureau_prise_pc_3_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.salon_prise_tv_power
    name: energy_salon_prise_tv_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_1_power
    name: energy_bureau_prise_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_routeur_power
    name: energy_bureau_prise_routeur_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.chambre_emilie_prise_bureau_power
    name: energy_chambre_emilie_prise_bureau_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.mezzanine_prise_1_power
    name: energy_mezzanine_prise_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left

automation:
###############################################
- id: energie_change_tarif
  alias: Function - Energie - Changement tarif
  description: Function - Energie - Changement tarif
  trigger:
  - trigger: state
    entity_id:
    - sensor.template_teleinfo_periode_tarifaire
    to: HC
    for:
      seconds: 10
    id: HC
  - trigger: state
    entity_id:
    - sensor.template_teleinfo_periode_tarifaire
    to: HP
    for:
      seconds: 10
    id: HP
  condition: []
  action:
  - choose:
    - alias: Preparation Tempo Rouge
      conditions:
      - condition: trigger
        id:
        - HC
      - condition: state
        entity_id: sensor.rte_tempo_prochaine_couleur
        state: Rouge
      sequence:
      - action: script.turn_on
        target:
          entity_id: script.energy_tempo_red_before
        data: {}
    - alias: Tempo Rouge HP
      conditions:
      - condition: trigger
        id:
        - HP
      - condition: state
        entity_id: sensor.linky_couleur_actuelle
        state: rouge
      sequence:
      - action: script.turn_on
        target:
          entity_id: script.energy_tempo_red_hp
        data: {}
    - alias: Fin Tempo Rouge
      conditions:
      - condition: trigger
        id:
        - HC
      - condition: state
        entity_id: sensor.linky_couleur_actuelle
        state: rouge
      - condition: not
        conditions:
        - condition: state
          entity_id: sensor.rte_tempo_prochaine_couleur
          state: Rouge
      sequence:
      - action: script.turn_on
        target:
          entity_id: script.energy_tempo_red_end
        data: {}
  mode: single

###############################################
script:
###############################################
  energy_tempo_red_before:
    alias: Energie - Tempo rouge Preparation
    sequence:
      - action: notify.mobile_seb
        data:
          message: "Tempo rouge Preparation"
      - action: select.select_option
        continue_on_error: true
        data:
          option: "Tempo rouge"
        target:
          entity_id: select.petit_mars
      - action: script.turn_on
        target:
          entity_id: script.routine_all_power_device_on
      - action: switch.turn_on
        target:
          label_id: 
            - red_power_off
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_soc_set
        data:
          value: "100"
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_min_soc
        data:
          value: "10"
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_input_limit
        data:
          value: "900"
      - action: number.set_value
        target:
          entity_id: number.solarflow_800_pro_soc_maximum
        data:
          value: 100
      - action: number.set_value
        target:
          entity_id: number.solarflow_800_pro_limite_d_entree
        data:
          value: 600
      - action: select.select_option
        target:
          entity_id: select.solarflow_800_pro_mode_de_fonctionnement_ac
        data:
          option: input   
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.panasonic_heat_pump_main_z1_temp','heat') and repeat.index < 10}}"
              sequence:
                - action: climate.turn_on
                  data: {}
                  target:
                    entity_id: 
                      - climate.panasonic_heat_pump_main_z1_temp
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.panasonic_heat_pump_main_dhw_target_temp','temperature', 65) and repeat.index < 10}}"
              sequence:
                - action: water_heater.set_temperature
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    temperature: 65
                - action: water_heater.set_operation_mode
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    operation_mode: performance
                - delay:
                    seconds: 60  
###############################################  
  energy_tempo_red_hp:
    alias: Energie - Tempo rouge HP
    sequence:
      - action: notify.mobile_seb
        data:
          message: "Tempo rouge HP"
      - action: script.turn_on
        target:
          entity_id: script.routine_away_all_power_device_off
      - action: switch.turn_off
        target:
          label_id: 
            - red_power_off
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_input_limit
        data:
          value: "0"
      - action: number.set_value
        target:
          entity_id: number.solarflow_800_pro_limite_de_sortie
        data:
          value: 200
      - action: select.select_option
        target:
          entity_id: select.solarflow_800_pro_mode_de_fonctionnement_ac
        data:
          option: output  
      - action: climate.turn_off
        data: {}
        target:
          entity_id: 
            - climate.mobile_heater_plug_thermostat
      - action: select.select_option
        continue_on_error: true
        data:
          option: "Tempo rouge"
        target:
          entity_id: select.petit_mars
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.panasonic_heat_pump_main_z1_temp','off') and repeat.index < 10}}"
              sequence:
                - action: climate.turn_off
                  data: {}
                  target:
                    entity_id: 
                      - climate.panasonic_heat_pump_main_z1_temp
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.panasonic_heat_pump_main_dhw_target_temp','temperature', 40) and repeat.index < 10}}"
              sequence:
                - action: water_heater.set_temperature
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    temperature: 40
                - action: water_heater.set_operation_mode
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    operation_mode: performance
                - delay:
                    seconds: 60               

  
###############################################  
  energy_tempo_red_end:  
    alias: Energie - Tempo rouge fin
    sequence:
      - action: notify.mobile_seb
        data:
          message: "Fin Tempo rouge"   
      - action: script.turn_on
        target:
          entity_id: script.routine_all_power_device_on
      - action: switch.turn_on
        target:
          label_id: 
            - red_power_off
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_soc_set
        data:
          value: "80"
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_min_soc
        data:
          value: "10"
      - action: number.set_value
        target:
          entity_id: number.ace_1500_garage_input_limit
        data:
          value: "900"
      - action: number.set_value
        target:
          entity_id: number.solarflow_800_pro_soc_maximum
        data:
          value: 80
      - action: number.set_value
        target:
          entity_id: number.solarflow_800_pro_limite_de_sortie
        data:
          value: 200
      - action: select.select_option
        target:
          entity_id: select.solarflow_800_pro_mode_de_fonctionnement_ac
        data:
          option: input  
      - action: select.select_option
        continue_on_error: true
        data:
          option: Normal
        target:
          entity_id: select.petit_mars
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.panasonic_heat_pump_main_z1_temp','heat') and repeat.index < 10}}"
              sequence:
                - action: climate.turn_on
                  data: {}
                  target:
                    entity_id: 
                      - climate.panasonic_heat_pump_main_z1_temp
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.panasonic_heat_pump_main_dhw_target_temp','temperature', 53) and repeat.index < 10}}"
              sequence:
                - action: water_heater.set_temperature
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    temperature: 55
                - action: water_heater.set_operation_mode
                  target:
                    entity_id: water_heater.panasonic_heat_pump_main_dhw_target_temp
                  data:
                    operation_mode: performance
                - delay:
                    seconds: 60      
     
###############################################  
