sensor:
  - platform: integration
    source: sensor.bureau_prise_pc_1_power
    name: energy_bureau_prise_pc_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_pc_2_power
    name: energy_bureau_prise_pc_2_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_pc_3_power
    name: energy_bureau_prise_pc_3_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.salon_prise_tv_power
    name: energy_salon_prise_tv_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_1_power
    name: energy_bureau_prise_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.bureau_prise_routeur_power
    name: energy_bureau_prise_routeur_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.chambre_emilie_prise_bureau_power
    name: energy_chambre_emilie_prise_bureau_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left
  - platform: integration
    source: sensor.mezzanine_prise_1_power
    name: energy_mezzanine_prise_1_power
    unit_prefix: k
    unit_time: h
    round: 2
    method: left

automation:
###############################################
- id: energie_change_tarif
  alias: Function - Energie - Changement tarif
  description: Function - Energie - Changement tarif
  trigger:
  - platform: state
    entity_id:
    - sensor.template_teleinfo_periode_tarifaire
    to: HC
    for:
      seconds: 10
    id: HC
  - platform: state
    entity_id:
    - sensor.template_teleinfo_periode_tarifaire
    to: HP
    for:
      seconds: 10
    id: HP
  condition: []
  action:
  - choose:
    - alias: Preparation Tempo Rouge
      conditions:
      - condition: trigger
        id:
        - HC
      - condition: state
        entity_id: sensor.rte_tempo_prochaine_couleur
        state: Rouge
      sequence:
      - service: script.turn_on
        target:
          entity_id: script.energy_tempo_red_before
        data: {}
    - alias: Tempo Rouge HP
      conditions:
      - condition: trigger
        id:
        - HP
      - condition: state
        entity_id: sensor.linky_couleur_actuelle
        state: rouge
      sequence:
      - service: script.turn_on
        target:
          entity_id: script.energy_tempo_red_hp
        data: {}
    - alias: Fin Tempo Rouge
      conditions:
      - condition: trigger
        id:
        - HC
      - condition: state
        entity_id: sensor.linky_couleur_actuelle
        state: rouge
      - condition: not
        conditions:
        - condition: state
          entity_id: sensor.rte_tempo_prochaine_couleur
          state: Rouge
      sequence:
      - service: script.turn_on
        target:
          entity_id: script.energy_tempo_red_end
        data: {}
  mode: single

###############################################
script:
###############################################
  energy_tempo_red_before:
    alias: Energie - Tempo rouge Preparation
    sequence:
      - service: notify.mobile_seb
        data:
          message: "Tempo rouge Preparation"
      - service: select.select_option
        data:
          option: "Tempo rouge"
        target:
          entity_id: select.petit_mars
      - service: script.turn_on
        target:
          entity_id: script.routine_all_power_device_on
      - service: switch.turn_on
        target:
          label_id: 
            - red_power_off
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.pac_maison','heat') and repeat.index < 10}}"
              sequence:
                - service: climate.turn_on
                  data: {}
                  target:
                    entity_id: 
                      - climate.pac_maison
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.pac_tank','temperature', 65) and repeat.index < 10}}"
              sequence:
                - service: water_heater.set_temperature
                  target:
                    entity_id: water_heater.pac_tank
                  data:
                    temperature: 65
                - delay:
                    seconds: 60  
###############################################  
  energy_tempo_red_hp:
    alias: Energie - Tempo rouge HP
    sequence:
      - service: notify.mobile_seb
        data:
          message: "Tempo rouge HP"
      - service: script.turn_on
        target:
          entity_id: script.routine_away_all_power_device_off
      - service: switch.turn_off
        target:
          label_id: 
            - red_power_off
      - service: climate.turn_off
        data: {}
        target:
          entity_id: 
            - climate.mobile_heater_plug_thermostat
      - service: select.select_option
        data:
          option: "Tempo rouge"
        target:
          entity_id: select.petit_mars
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.pac_maison','off') and repeat.index < 10}}"
              sequence:
                - service: climate.turn_off
                  data: {}
                  target:
                    entity_id: 
                      - climate.pac_maison
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.pac_tank','temperature', 40) and repeat.index < 10}}"
              sequence:
                - service: water_heater.set_temperature
                  target:
                    entity_id: water_heater.pac_tank
                  data:
                    temperature: 40
                - delay:
                    seconds: 60               

  
###############################################  
  energy_tempo_red_end:  
    alias: Energie - Tempo rouge fin
    sequence:
      - service: notify.mobile_seb
        data:
          message: "Fin Tempo rouge"   
      - service: script.turn_on
        target:
          entity_id: script.routine_all_power_device_on
      - service: switch.turn_on
        target:
          label_id: 
            - red_power_off
      - service: select.select_option
        data:
          option: Normal
        target:
          entity_id: select.petit_mars
      - parallel:
        - sequence:
          - repeat:
              while: "{{ not is_state('climate.pac_maison','heat') and repeat.index < 10}}"
              sequence:
                - service: climate.turn_on
                  data: {}
                  target:
                    entity_id: 
                      - climate.pac_maison
                - delay:
                    seconds: 60
          - repeat:
              while: "{{ not is_state_attr('water_heater.pac_tank','temperature', 53) and repeat.index < 10}}"
              sequence:
                - service: water_heater.set_temperature
                  target:
                    entity_id: water_heater.pac_tank
                  data:
                    temperature: 53
                - delay:
                    seconds: 60      
     
###############################################  
