
script:  
################################################################################
  play_music:
    alias: "Function - Music manager - Play the right playlist"
    mode: parallel

    fields:
      media_player:
        name: Enceinte
        required: True
        selector: 
          entity:
            domain: media_player
            multiple: true
      style:
        name: style
        required: False
        selector: 
          select:
            options: ['motivation','chill','work','zen','histoire']
      public:
        name: public
        required: False
        selector: 
          select:
            options: ['Famille','Sebastien','Laurine','Timothee','Emilie']
      title:
        name: titre
        required: False
        selector:
          text:
      
    variables:
      playlists: "{{state_attr('input_select.playlist','playlists') |to_json(ensure_ascii=True)}}"

    sequence:
      - variables:
          input_playlist: "{{states('input_select.playlist')}}"
          reset_playlist: >
            {% if ((title is not defined) or (title is none)  or (title == '')) 
                  and (not is_state('input_select.playlist', ' ')) %}
                True
            {%else%}
                False
            {%endif%} 
      - if:
          - condition: template
            value_template: "{{reset_playlist}}"
        then:
          - service: input_select.select_option
            data:
              option: " "
            target:
              entity_id: input_select.playlist
      - variables:
          selected_playlists: >          
            {%- set ns = namespace(selected_playlists=[]) %}

            {# set to None if not defined or empty #}
            {% if (style is not defined) or (style == '') %}
              {% set style = None %}
            {% endif %}
            {% if (public is not defined) or (public == '')%}
              {% set public = None %}
            {% endif %}
            {% if (title is not defined) or (title == '')%}
              {% set title = None %}
            {% endif %}

            {% if (reset_playlist)%}
              {% set title = input_playlist %}
            {% endif %}

            {%for playlist in playlists%}
              {% if (title is not none and title==playlist.title)%}
                {%- set ns.selected_playlists = ns.selected_playlists + [playlist] %}
              {% elif (style is none or style in playlist.style)
                  and (public is none or public in playlist.public)
                  and (title is none) %}
                {%- set ns.selected_playlists = ns.selected_playlists + [playlist] %}
              {% endif %}
            {% endfor  %}

            {{ns.selected_playlists |to_json(ensure_ascii=True)}}         
          random_playlist: >
            {%if selected_playlists|length > 0 %}
              {{selected_playlists|random |to_json(ensure_ascii=True)}}
            {% endif %}
      
      - if:
          - condition: template
            value_template: "{{ random_playlist is mapping  }}"
        then:
          - service: media_player.play_media
            target:
              entity_id: "{{ media_player }}"
            data:
              media_content_id: "{{ random_playlist.content_id }}"
              media_content_type: "{{ random_playlist.content_type }}"
              enqueue: replace
          - service: notify.mobile_seb
            data:
              message: >
                {% if media_player is not iterable %}
                  {% set media_player = [media_player]%}
                {%endif%}
                "Ok c'est partie ! {{random_playlist.title}} sur {{expand(media_player)|map(attribute="name")|join(', ')}}
        else:
          - stop: "Aucune playlist trouvée"
            error: true


################################################################################
  play_mood_music:
      alias: "Function - Music manager - Guess what to play"
      variables:
        zone_ids:
          RdC:
            manager:  media_player.salle_a_manger
            group_members:
              - media_player.cuisine
              - media_player.cuisine_move
              - media_player.salon
          Bureau:
            manager: media_player.bureau
            group_members: []
          Cuisine:
            manager: media_player.cuisine
            group_members: 
              - media_player.cuisine_move

      fields:
        zone:
          name: zone de lecture
          required: True
          selector: 
            select:
              options: ['RdC','Bureau','Cuisine'] 
        title:
          name: titre
          required: False
          selector:
            text:     
      
      sequence:
        - variables:
            media_player_id: "{{ zone_ids[zone].manager}}"
            group_members: > 
              {{
              (expand(zone_ids[zone].group_members)
                |selectattr('state', 'ne', 'unavailable')
                |rejectattr('attributes.source','defined')
                |map(attribute="entity_id")
                |list) +
              (expand(zone_ids[zone].group_members)
                |selectattr('state', 'ne', 'unavailable')
                |selectattr('attributes.source','defined')
                |rejectattr('attributes.source','eq','TV')
                |map(attribute="entity_id")
                |list) 
              }}

            public: >
              {%if title is defined%}
              {%elif zone=="Bureau" %}
                {% if (is_state('person.sebastien','home')) %}
                Sebastien
                {% elif (is_state('person.laurine','home')) %}
                Laurine
                {%endif%}
              {%elif zone=="RdC" %}
                 {% if (is_state('person.sebastien','home') 
                  and is_state('person.laurine','home')) %}
                Famille
                {% elif (is_state('person.sebastien','home')) %}
                Sebastien
                {% elif (is_state('person.laurine','home')) %}
                Laurine
                {%endif%}             
              {% endif %}

            style: >
              {% if (title is none) or (title == '')%}
                {% set title = null %}
              {% endif %}

              {%if title is defined%}
              {%elif zone=="Bureau" %}
                {% if (utcnow().hour <= 6) %}
                  zen
                {% elif is_state('binary_sensor.workday_sensor','on') 
                    and utcnow().hour <= 19  %}
                  work
                {% elif utcnow().hour <= 10 %}
                  chill
                {% elif utcnow() <= today_at(states('input_datetime.'+iif(is_state('binary_sensor.workday_tomorrow','on'),'children_night_time','children_night_time_we')))  %}
                  motivation
                {% else %}
                  zen
                {%endif %}
              {%elif zone=="RdC" %}
                {% if (utcnow().hour <= 6) %}
                  zen
                {% elif (utcnow().hour <= 10) %}
                  chill
                {% elif utcnow() <= today_at(states('input_datetime.'+iif(is_state('binary_sensor.workday_tomorrow','on'),'children_night_time','children_night_time_we'))) %}
                  motivation
                {% else %}
                  zen
                {%endif %}
              {% endif %}

        - service: media_player.join
          target:
            entity_id: > 
              {{media_player_id}}
          data:
            group_members: >
              {{group_members}}
        - service: script.play_music
          data:
            media_player: "{{media_player_id}}"
            style: "{{style}}"
            public: "{{public}}"
            title: "{{title}}"
################################################################################


automation:
################################################################################
- id: handle_tag_scan
  alias: "Function - Music manager - Handle Tag Scan"
  mode: single
  # Hide warnings when triggered while in delay.
  max_exceeded: silent
  variables:
    # Map scanner device ID to media player entity ID
    media_players:
      fa37e0c36e836c9a3fa47145157df38f: media_player.emilie
      7b6a7b292afbcb0ad93f19416ce95b43: media_player.timothee

    playlists: "{{state_attr('input_select.playlist','playlists') |to_json(ensure_ascii=True)}}"
    tags: >
      {%- set ns = namespace(tags=[]) %}
      {%- for tag in (playlists|map(attribute="tags")|list) %}
        {% if (tag|length > 0)%}
          {%- set ns.tags = ns.tags + tag%}
        {% endif %}
      {%endfor%}
      {{ns.tags|unique|list|to_json(ensure_ascii=True)}} 
  trigger:
    platform: event
    event_type: tag_scanned
  condition:
    # Test that we support this device and tag
    - "{{ trigger.event.data.tag_id in tags }}"
    - "{{ trigger.event.data.device_id in media_players }}"
  action:
    - variables:
        tag: "{{ trigger.event.data.tag_id}}"
        selected_playlist: >
          {%- set ns = namespace(selected_playlists=[]) %}
          {%for playlist in playlists%}
            {% if (tag is not none and tag in playlist.tags)%}
              {%- set ns.selected_playlists = ns.selected_playlists + [playlist] %}
            {% endif %}
          {% endfor  %}
          {{ns.selected_playlists|first|to_json(ensure_ascii=True)}} 

        media_player_entity_id: "{{ media_players[trigger.event.data.device_id] }}"
        media_content_id: "{{ selected_playlist.content_id }}"
        media_content_type: "{{ selected_playlist.content_type }}"
    - service: media_player.play_media
      target:
        entity_id: "{{ media_player_entity_id }}"
      data:
        media_content_id: "{{ media_content_id }}"
        media_content_type: "{{ media_content_type }}"
        enqueue: replace
    - service: media_player.shuffle_set
      data:
        shuffle: true
      target:
        entity_id: "{{ media_player_entity_id }}"
    - delay: 2 # timeout before we allow processing next scan

 ################################################################################         
- id: adapte_volume_salon 
  alias: "Function - Music manager - Adapte volume Salon"
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - media_player.salon
      attribute: source
      to: TV
      id: tv
    - platform: state
      entity_id:
        - media_player.salon
      attribute: source
      from: TV
      id: music
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: tv
          sequence:
            - service: media_player.volume_set
              data:
                volume_level: 0.16
              target:
                entity_id: media_player.salon
        - conditions:
            - condition: trigger
              id: music
          sequence:
            - service: media_player.volume_set
              data:
                volume_level: 0.08
              target:
                entity_id: media_player.salon
      default: []

################################################################################
input_select:
  playlist:
    name: Playlist
    options:
        - ' '
      ## Famille ##
        - La vie est belle
        - Feel good acoustic
        - Chilled Classical
        - Peaceful Meditation
        - Ambient Relaxation
        - Sleep
      ## Sebastien ##
        - Malukah
        - Fantasy board gaming
        - Reading Adventure
        - Sith Mediation
        - Sea Song
        - Champs Marin
      ## Enfants ##
        - Milie D
        - Noisette
        - Kidico
        - KidStory
        - Dance Émilie
        - Princess disney france
        - Magic system
        - Petit loup
        - Bulle et Bob
        - Histoire Aldebert
    icon: mdi:playlist-music

homeassistant:
  customize:
    input_select.playlist:
      playlists:
      ## Famille ##
        - title: La vie est belle
          content_id: spotify:playlist:37i9dQZF1DXdrln2UyZD7F
          content_type: playlist
          style: ['motivation']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
        - title: Feel good acoustic
          content_id: spotify:playlist:37i9dQZF1DWXRvPx3nttRN
          content_type: playlist
          style: ['chill']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
        - title: Chilled Classical
          content_id: spotify:playlist:37i9dQZF1DWUvHZA1zLcjW
          content_type: playlist
          style: ['chill']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
        - title: Peaceful Meditation
          content_id: spotify:playlist:37i9dQZF1DWZqd5JICZI0u
          content_type: playlist
          style: ['zen','work']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
        - title: Ambient Relaxation
          content_id: spotify:playlist:37i9dQZF1DX3Ogo9pFvBkY
          content_type: playlist
          style: ['zen','work']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
        - title: Sleep
          content_id: spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
          content_type: playlist
          style: ['zen','work']
          public: ['Sebastien', 'Laurine', 'Famille']
          tags: []
      ## Sebastien ##
        - title: Malukah
          content_id: spotify:playlist:5ZLgTnEANdMIgkfsX63Ykv
          content_type: playlist
          style: ['chill','motivation']
          public: ['Sebastien']
          tags: []
        - title: Fantasy board gaming
          content_id: spotify:playlist:37i9dQZF1DWVdDMUimLXxx
          content_type: playlist
          style: ['zen','chill','work']
          public: ['Sebastien']
          tags: []
        - title: Reading Adventure
          content_id: spotify:playlist:37i9dQZF1DWUWUfWSLE7dn
          content_type: playlist
          style: ['zen','chill','work']
          public: ['Sebastien']
          tags: []
        - title: Sith Mediation
          content_id: spotify:playlist:0YCerIiq6AF59sE3NlRPLQ
          content_type: playlist
          style: ['chill','work']
          public: ['Sebastien']
          tags: []
        - title: Sea Song
          content_id: spotify:playlist:24f4OwL1tOAyqbRjrpWqhH
          content_type: playlist
          style: ['chill','motivation']
          public: ['Sebastien']
          tags: []
        - title: Champs Marin
          content_id: spotify:playlist:0wR5cFFOx16rfxOVHo4Kdg
          content_type: playlist
          style: ['motivation']
          public: ['Emilie']
          tags: ['CE-E7-4D-3D']
      ## Enfants ##
        - title: Milie D
          content_id: spotify:show:6xZWDWtjxF6dEV9KZZNRTF
          content_type: playlist
          style: ['histoire']
          public: ['Timothee','Emilie']
          tags: ['F7-E3-4D-3D','01-E6-4D-3D']
        - title: Noisette
          content_id: spotify:show:0cfuaJnYvp6iTwXXOFjt0y
          content_type: playlist
          style: ['histoire']
          public: ['Timothee','Emilie']
          tags: ['DF-E7-4D-3D','08-E4-4D-3D']
        - title: Kidico
          content_id: spotify:show:5no3pub2QBaaaeeBdiobLo
          content_type: playlist
          style: ['histoire']
          public: ['Emilie']
          tags: ['C0-E6-4D-3D','10-E4-4D-3D']
        - title: KidStory
          content_id: spotify:show:2OApiYYyIQpZ7VTTPLBp7A
          content_type: playlist
          style: ['histoire']
          public: ['Emilie']
          tags: []
        - title: Dance Émilie
          content_id: spotify:playlist:1OdvIJp6A9yvaFsksZANVj
          content_type: playlist
          style: ['motivation']
          public: ['Emilie']
          tags: ['1A-E5-4D-3D']
        - title: Princess disney france
          content_id: spotify:playlist:6YTRixD9kjc4T9oj0SBNXp
          content_type: playlist
          style: ['chill']
          public: ['Emilie']
          tags: ['F8-E5-4D-3D']
        - title: Magic system
          content_id: spotify:playlist:7aUx9jE0vqYsLFAUIZvkkz
          content_type: playlist
          style: ['motivation']
          public: ['Emilie']
          tags: ['00-E4-4D-3D']
        - title: Petit loup
          content_id: spotify:album:3b5RlFQSq0ivPNktaRYa9c
          content_type: playlist
          style: ['histoire']
          public: ['Emilie','Timothee']
          tags: ['09-E6-4D-3D']
        - title: Bulle et Bob
          content_id: spotify:playlist:4Gj26yoPs0XKz1DJ5iT01G
          content_type: playlist
          style: ['histoire']
          public: ['Emilie','Timothee']
          tags: ['30-E5-4D-3D','AF-E6-4D-3D']
        - title: Histoire Aldebert
          content_id: spotify:playlist:3IBqtadarJNvU5FXB0VvhZ
          content_type: playlist
          style: ['histoire']
          public: ['Emilie','Timothee']











