binary_sensor:
  - platform: group
    name: "portail detection voiture"
    device_class: occupancy
    unique_id: entrance_car_occupancy
    #icon: mdi:car-off
    entities:
      - binary_sensor.entrance_gate_driveway_car_occupancy
      - binary_sensor.portail_front_car_occupancy

automation:
################################################################################
- id: 'function_portail_auto-close'
  alias: Function portail - Fermeture auto
  description: Fermeture automatique du portail
  trigger:
  - platform: state
    entity_id: cover.portail_2
    to: "open"
    for:
      minutes: 3
      seconds: 0
  - platform: state
    entity_id: binary_sensor.portail_detection_voiture
    from: "on"
    to: "off"
    for:
      seconds: 30
  condition: 
    - condition: state
      entity_id: cover.portail_2
      state: "open"
    - condition: state
      entity_id: binary_sensor.portail_detection_voiture
      state: "off"
  action:
    - service: cover.close_cover
      data: {}
      target:
        entity_id: cover.portail_2
  mode: restart
################################################################################
- id: 'function_portail_auto-open'
  alias: Function portail - Ouverture auto
  description: Ouverture automatique du portail
  trigger:
    - platform: state
      entity_id: binary_sensor.entrance_gate_driveway_car_occupancy
      to: "on"
    - platform: state
      entity_id: binary_sensor.entrance_gate_plate_detected
      to: "on"
    - platform: zone
      entity_id: person.sebastien
      zone: zone.home
      event: enter
    - platform: zone
      entity_id: person.laurine
      zone: zone.home
      event: enter
  condition: 
    condition: state
    entity_id: cover.portail_2
    state: closed
    for:
      minutes: 2
  action:
    - service: cover.open_cover
      data: {}
      target:
        entity_id: cover.portail_2
  mode: single

