group:
  parent_home:
    name: Parent à la maison
    icon: mdi:account-supervisor
    entities:
      - person.sebastien
      - person.laurine
  home_occupancy:
    name: detection presence maison
    entities:
      - binary_sensor.maison_rdc_presence
      - binary_sensor.outside_presence
      - binary_sensor.maison_floor1_presence

    
  

input_boolean:
  guest_mode:
    name: Mode invitée
    icon: mdi:account-plus

binary_sensor:
  - platform: template
    sensors:
      anyone_home:
        device_class: occupancy
        friendly_name: 'A la maison'
        value_template: "{{ (states.person | selectattr('state','eq','home') | list | count > 0) or (is_state('input_boolean.guest_mode','on')) }}"

  - name: "maison_rdc_presence"
    device_class: occupancy
    platform: "bayesian"
    prior: 0.60
    probability_threshold: 0.70
    observations:
    - entity_id: sensor.mouvement_salon_5min
      platform: "numeric_state"
      prob_given_true: 0.99
      prob_given_false: 0.30
      above: 0
    - entity_id: sensor.mouvement_entree_5min
      platform: "numeric_state"
      prob_given_true: 0.80
      prob_given_false: 0.50
      above: 0
    - entity_id: sensor.mouvement_salle_a_manger_5min
      platform: "numeric_state"
      prob_given_true: 0.99
      prob_given_false: 0.40
      above: 0
    - entity_id: sensor.mouvement_cuisine_5min
      platform: "numeric_state"
      prob_given_true: 0.80
      prob_given_false: 0.50
      above: 0
    - entity_id: media_player.tv01
      platform: "state"
      prob_given_true: 0.99
      prob_given_false: 0.50
      to_state: "on"     
    - entity_id: sensor.mouvement_wc_rdc_5min
      platform: "numeric_state"
      prob_given_true: 0.80
      prob_given_false: 0.50
      above: 0

  - name: "maison_floor1_presence"
    device_class: occupancy
    platform: "bayesian"
    prior: 0.25
    probability_threshold: 0.80
    observations:    
    - entity_id: sensor.mouvement_couloir_5min
      platform: "numeric_state"
      prob_given_true: 0.80
      prob_given_false: 0.30
      above: 0
    - entity_id: sensor.mouvement_escalier_5min
      platform: "numeric_state"
      prob_given_true: 0.80
      prob_given_false: 0.30
      above: 0
    - entity_id: sensor.mouvement_wc_floor_5min
      platform: "numeric_state"
      prob_given_true: 0.90
      prob_given_false: 0.50
      above: 0
    - entity_id: sensor.mouvement_bureau_5min
      platform: "numeric_state"
      prob_given_true: 0.90
      prob_given_false: 0.50
      above: 0

  - name: "outside_presence"
    device_class: occupancy
    platform: "bayesian"
    prior: 0.25
    probability_threshold: 0.95
    observations:
    - entity_id: "sensor.mouvement_air_de_jeux_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_garage_3_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_patio_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_piscine_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_camera_entree_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_camera_parking_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "sensor.mouvement_terasse_10min"
      platform: "numeric_state"
      prob_given_true: 0.95
      prob_given_false: 0.20
      above: 0
    - entity_id: "vacuum.automower_r_450x_gardenbot"
      platform: "state"
      prob_given_true: 0.25
      prob_given_false: 0.05
      to_state: docked


### Todo set children there by default if parent are there when HA start
automation:
################################################################################
- id: 'function_presence_papamobile_left_home'
  alias: Papa Mobile - Out
  description: Papa mobile n'est plus a la maison
  trigger:
  - platform: state
    entity_id: device_tracker.papamobile
    to: not_home
  condition: []
  action:
  - service: device_tracker.see
    data:
      location_name: not_home
      dev_id: netatmo_emilie
  - service: device_tracker.see
    data:
      location_name: not_home
      dev_id: netatmo_timothee
  mode: single
################################################################################
- id: 'function_presence_car_in_front'
  alias: Function Presence - Voiture devant (on/off)
  description: Function Presence - Voiture devant
  trigger:
  - platform: state
    entity_id: binary_sensor.entree_car_occupancy
    to: 'on'
    for:
      minutes: 10
  condition: 
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.guest_mode
  - wait_for_trigger:
      - platform: state
        entity_id: binary_sensor.entree_car_occupancy
        to: "off"
        for:
          minutes: 5
  - service: input_boolean.turn_off
    entity_id: input_boolean.guest_mode
  mode: single
################################################################################

