binary_sensor:
  - platform: group
    name: Détecteurs fumées
    entities:
      - binary_sensor.capteur_fumee_couloir
      - binary_sensor.capteur_fumee_salon
      - binary_sensor.smoke_sensor_garage3_smoke
    device_class: smoke

alarm_control_panel:
  - platform: manual
    name: Alarme maison
    code: ""
    code_arm_required: false
    arming_time: 120
    delay_time: 120
    trigger_time: 240
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0

alert:
  fire_alert:
    name: "Alarm Incendie"
    entity_id: binary_sensor.detecteurs_fumees
    message: >
      "Incendie ! fumée detecté: {{ expand('binary_sensor.detecteurs_fumees') | selectattr('state', 'eq', 'on') | list | map(attribute='name') | join(', ') }}
    done_message: >
      "Fin d'alarme incendie"
    data:
      entity_id: camera.salon
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0
        #android
      image: "/api/camera_proxy/camera.salon"
      ttl: 0
      priority: high
    state: "on"   # Optional, 'on' is the default value
    repeat: 5
    can_acknowledge: false  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify
      - all_mobile

  swiming_pool:
    name: "Porte Piscine non sécurisée"
    message: >
      {% if is_state('binary_sensor.piscine_capteur_porte_door', 'on') %}
      Attention, la porte de la piscine est restée ouverte sans personne
      {% elif is_state('binary_sensor.piscine_capteur_porte_door', 'unavailable') %}
      Attention, la porte de la piscine est déconnectée.
      {% else %}
      Tout va bien
      {% endif %}
    done_message: >
      {% if is_state('input_boolean.alarme_piscine', 'off') %}
      Alarme désactivée
      {% else %}
      "Porte Piscine sécurisée"
      {% endif %}
    data:
      entity_id: camera.piscine_high
      push:
        sound:
          name: "default"
          critical: 1
          volume: 1.0
        #android
      image: "/api/camera_proxy/camera.piscine_high"
      ttl: 0
      priority: high
    entity_id: binary_sensor.swiming_pool_door_problem
    state: "on"   # Optional, 'on' is the default value
    repeat:
      - 15
      - 30
      - 60
    can_acknowledge: false  # Optional, default is true
    skip_first: true  # Optional, false is the default
    notifiers:
      - all_mobile

automation:
###############################################
- id: 'function_security_arm_when_away'
  alias: 'Function - Security -  Arme quand absent'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: away
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_arm_when_sleep'
  alias: 'Function - Security - Arme quand mode nuit'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: night
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: alarm_control_panel.alarm_arm_night
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_desarm_when_home'
  alias: 'Function - Security -  Désarme au retours des parents'
  trigger:
  - platform: state
    entity_id: group.parent_home
    to: home
  - platform: state
    entity_id: input_boolean.away_mode
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_desarm_when_morning'
  alias: 'Function - Security -  Désarme au reveil'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: morning
  - platform: event
    event_type: routine_event
    event_data:
      type: aurore
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: 'armed_night'
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_triger_while_armed_away'
  alias: 'Function - Security - Alarme (absent)'
  trigger:
    - platform: state
      entity_id: binary_sensor.maison_rdc_presence
      to: "on"
    - platform: state
      entity_id: binary_sensor.outside_presence
      to: "on"
    - platform: state
      entity_id: binary_sensor.maison_floor1_presence
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarme_maison
      state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.alarme_maison

###############################################
- id: 'function_security_triger_while_armed_night'
  alias: 'Function - Security - Alarme (nuit)'
  trigger:
    - platform: state
      entity_id: binary_sensor.outside_presence
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarme_maison
      state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.alarme_maison

###############################################
- id: 'function_security_triger_acton'
  alias: 'Function - Security - Traitement alarme'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarme_maison
      to: "triggered"
  action:
  - service: notify.mobile_seb
    data:
      message: "ALARME! Mouvement detecté: {{ expand('group.home_occupancy') | selectattr('state', 'eq', 'on') | list | map(attribute='name') | join(', ') }}"
###############################################
