alarm_control_panel:
  - platform: manual
    name: Alarme maison
    code: ""
    code_arm_required: false
    arming_time: 120
    delay_time: 120
    trigger_time: 240
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0

alert:
  fire_alert:
    name: "Alarm Incendie"
    message: >
      "Alarm Incendie"
    done_message: >
      "Fin d'alarme incendie"
    entity_id: binary_sensor.capteur_fumee_couloir
    state: "on"   # Optional, 'on' is the default value
    repeat: 5
    can_acknowledge: false  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify

automation:
###############################################
- id: 'function_security_desarm_when_home'
  alias: 'Function - Security -  Désarme au retours des parents'
  trigger:
    - platform: state
      entity_id: group.parent_home
      to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: 'armed_away'
  action:
    - service: alarm_control_panel.alarm_disarm
      target:
        entity_id: alarm_control_panel.alarme_maison
###############################################

###############################################
- id: 'function_security_fire_alarm'
  alias: 'Function - Security -  Alarm Incendie'
  trigger:
    - platform: state
      entity_id: binary_sensor.capteur_fumee_couloir
      to: 'on'
  action:
    - service: notify.mobile_app_intra_mob08
      data:
        message: >
          {%if 'to_state' in trigger %}
          {% set friendly_name = trigger.to_state.attributes.friendly_name %}
          {% endif %}
          Alarm incendie: {{friendly_name|d}}

###############################################