alarm_control_panel:
  - platform: manual
    name: Alarme maison
    code: ""
    code_arm_required: false
    arming_time: 120
    delay_time: 120
    trigger_time: 240
    disarm_after_trigger: false
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0
    armed_night:
      arming_time: 0
      delay_time: 0

alert:
  fire_alert:
    name: "Alarm Incendie"
    message: >
      "Alarm Incendie"
    done_message: >
      "Fin d'alarme incendie"
    entity_id: binary_sensor.capteur_fumee_couloir
    state: "on"   # Optional, 'on' is the default value
    repeat: 5
    can_acknowledge: false  # Optional, default is true
    skip_first: false  # Optional, false is the default
    notifiers:
      - notify

automation:
###############################################
- id: 'function_security_arm_when_away'
  alias: 'Function - Security -  Arme quand absent'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: away
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_arm_when_sleep'
  alias: 'Function - Security - Arme quand mode nuit'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: night
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: disarmed
  action:
  - service: alarm_control_panel.alarm_arm_night
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_desarm_when_home'
  alias: 'Function - Security -  Désarme au retours des parents'
  trigger:
  - platform: state
    entity_id: group.parent_home
    to: home
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: 'armed_away'
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_desarm_when_morning'
  alias: 'Function - Security -  Désarme au reveil'
  trigger:
  - platform: event
    event_type: routine_event
    event_data:
      type: morning
  - platform: event
    event_type: routine_event
    event_data:
      type: aurore
  condition:
  - condition: state
    entity_id: alarm_control_panel.alarme_maison
    state: 'armed_night'
  action:
  - service: alarm_control_panel.alarm_disarm
    target:
      entity_id: alarm_control_panel.alarme_maison
###############################################
- id: 'function_security_triger_while_armed_away'
  alias: 'Function - Security - Alarme (absent)'
  trigger:
    - platform: state
      entity_id: binary_sensor.maison_rdc_presence
      to: "on"
    - platform: state
      entity_id: binary_sensor.outside_presence
      to: "on"
    - platform: state
      entity_id: binary_sensor.maison_floor1_presence
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarme_maison
      state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.alarme_maison

###############################################
- id: 'function_security_triger_while_armed_night'
  alias: 'Function - Security - Alarme (nuit)'
  trigger:
    - platform: state
      entity_id: binary_sensor.outside_presence
      to: "on"
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarme_maison
      state: armed_night
  action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.alarme_maison

###############################################
- id: 'function_security_triger_acton'
  alias: 'Function - Security - Traitement alarme'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarme_maison
      to: "triggered"
  action:
  - service: notify.mobile_seb
    data:
      message: "ALARME! Mouvement detecté: {{ expand('group.home_occupancy') | selectattr('state', 'eq', 'on') | list | map(attribute='name') | join(', ') }}"

###############################################
- id: 'function_security_fire_alarm'
  alias: 'Function - Security -  Alarm Incendie'
  trigger:
  - platform: state
    entity_id: binary_sensor.capteur_fumee_couloir
    to: 'on'
  action:
  - service: notify.notify
    data:
      message: >
        {%if 'to_state' in trigger %}
        {% set friendly_name = trigger.to_state.attributes.friendly_name %}
        {% endif %}
        Alarm incendie: {{friendly_name|d}}

###############################################