automation:
###############################################
- id: function_tv_turn_on
  alias: Function - TV - Turn on
  description: ''
  trigger:
  - platform: device
    device_id: dbcce08a96672b067e52881e90409470
    domain: philips_js
    type: turn_on
  condition: []
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 70:af:24:0d:b4:b7
  mode: single
  ###############################################
- id: function_tv_xbox_switch_source
  alias: Function - TV - Switch source XBOX
  description: ""
  mode: single
  trigger:
    - platform: state
      entity_id:
        - media_player.xbox_salon
      to: "on"
      id: turned_on
    - platform: state
      entity_id:
        - media_player.xbox_salon
      to: "off"
      id: turned_off
  condition: []
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: turned_off
          sequence:
            - service: media_player.turn_off
              data: {}
              target:
                entity_id: media_player.tv01
      default:
        - service: script.function_tv_xbox_switch_source
          data: {}

script:
  function_tv_xbox_switch_source:
    alias: Function - TV - Switch source XBOX
    sequence:
      - if:
        - condition: state
          entity_id: media_player.tv01
          state: "off"
        then:
          - service: media_player.turn_on
            data: {}
            target:
              entity_id: media_player.tv01
          - delay:
              hours: 0
              minutes: 0
              seconds: 8
              milliseconds: 0
      - service: remote.send_command
        data:
          delay_secs: 0.5
          command:
            - Source
        target:
          entity_id: remote.tv01
      - delay:
          seconds: 2
      - service: remote.send_command
        data:
          delay_secs: 0.5
          command:
            - CursorDown
            - CursorDown
            - CursorDown
            - CursorUp
            - Confirm
        target:
          entity_id: remote.tv01

intent_script:
###############################################################################
  tvXBoxOn:
    async_action: false
    speech:
      text: "c'est partie, bon jeux"
    action:
      - service: script.function_tv_xbox_switch_source
        data: {}