# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
  - platform: marytts
    host: "marytts"
    port: 59125
    codec: "WAVE_FILE"
    voice: "upmc-pierre-hsmm"
    language: "fr"

notify:
  - platform: tts
    name: notify_salon
    entity_id: tts.google_say
    media_player: media_player.salon
    language: fr

#web
http:
  use_x_forwarded_for: true
  trusted_proxies:
  - 192.168.10.0/23
  - 127.0.0.1
  - 10.42.0.0/16
  - 172.16.0.0/16 

recorder:
  purge_keep_days: 10
#  db_url: !secret k3s_db_url
#  exclude:
#    domains:
#      - device_tracker

wake_on_lan:

#logs
logger:
  default: error
  logs:
    homeassistant.components.recorder: critical
    homeassistant.components.apple_tv: critical
    homeassistant.components.template: critical
    homeassistant.components.mqtt: critical
    homeassistant.components.flipr: critical
    homeassistant.components.netatmo: error
    homeassistant.components.mfi: error

    homeassistant.components.sonos: error
    homeassistant.components.media_player: error
    custom_components.husqvarna_automower: error
    custom_components.chime_tts: error
    #custom_components.deepstack_face: error

sensor:
  - platform: time_date
    display_options:
      - 'date_time_iso'

binary_sensor:
  - platform: tod
    name: Nuit
    after: sunset
    before: sunrise
