---
### MQTT Monitor ###

automation:
################################################################################
- id: 'system_gate_notification'
  alias: System - Notification - Portail deconnecté
  description: ''
  trigger:
  - trigger: state
    entity_id: cover.portail_2
    to: unavailable
    for: 00:01:00
  condition: []
  action:
  - action: notify.notify
    data:
      message: Portail déconnecté
      title: Alerte Portail
  - action: notify.mobile_seb
    data:
      message: Portail déconnecté
      title: Alerte Portail
  mode: single
################################################################################
