---
 ###
binary_sensor:
  - name: VPN connection #### VPN Gatway
    platform: ping
    host: 10.1.1.1
  - name: odr01
    platform: ping
    host: odr01.intra.sberard.fr
  - name: odr02
    platform: ping
    host: odr02.intra.sberard.fr
  - name: odr03
    platform: ping
    host: odr03.intra.sberard.fr
  - name: up01
    platform: ping
    host: up01.intra.sberard.fr
  - name: up02
    platform: ping
    host: up02.intra.sberard.fr
  - name: up03
    platform: ping
    host: up03.intra.sberard.fr
  - name: nuc01
    platform: ping
    host: nuc01.intra.sberard.fr
  - name: nuc02
    platform: ping
    host: nuc02.intra.sberard.fr
  - name: nuc03
    platform: ping
    host: nuc03.intra.sberard.fr

### Monitor system ###
group:
  required_hub_devices:
    name: Hub devices
    all: true
    icon: mdi:router-network
    entities:
      - device_tracker.legrand_home_controle
      - device_tracker.dream_machine
      - device_tracker.netatmo_thermostat

  required_security_devices:
    name: Security devices
    all: true
    icon: mdi:cctv
    entities:
      - device_tracker.netatmo_presence_entree
      - device_tracker.netatmo_presence_parking
      - device_tracker.netatmo_welcome
      - device_tracker.netatmo_welcome_2  

  required_door_devices:
    name: Door devices
    all: true
    icon: mdi:garage-variant
    entities:
      - device_tracker.garagedoor_1
      - device_tracker.garagedoor_2
      - device_tracker.garagedoor_3
      - device_tracker.entrance_gate #Portail

  required_cluster_devices:
    name: cluster devices
    all: true
    icon: mdi:server-network
    entities:
      - binary_sensor.up01
      - binary_sensor.up02
      - binary_sensor.up03
      - binary_sensor.odr01
      - binary_sensor.odr02
      - binary_sensor.odr03
      - binary_sensor.nuc01
      - binary_sensor.nuc02
      - binary_sensor.nuc03


  required_other_devices:
    name: Other devices
    all: true
    icon: mdi:power-plug
    entities:
      - device_tracker.bed_heater
      - device_tracker.teddy_light
      - device_tracker.flipr_wifi_relay

  required_devices:
    name: monitored devices
    all: true
    icon: mdi:router-network
    entities:
      - group.required_hub_devices
      - group.required_security_devices
      - group.required_door_devices
      - group.required_cluster_devices
      - group.required_other_devices

automation:
################################################################################
- id: required_devices_alert
  alias: System - Notification - Network device alerte
  description: Notification appareil deconnecté
  trigger:
  - platform: state
    entity_id: group.required_devices
    to: 'not_home'
  - platform: homeassistant
    event: start
  condition:
  - condition: state
    entity_id: group.required_devices
    state: 'not_home'
  action:
  - service: persistent_notification.create
    data: 
      notification_id: required_devices_alert
      title: >
        {{ expand('group.required_devices') | selectattr('state', 'eq', 'not_home') | list | count }} appareil(s) déconnecté(s)
      message: >
        Appareil(s) déconnecté(s) : {{ expand('group.required_devices') | selectattr('state', 'eq', 'not_home') | map(attribute='name') | join(', ') }}
  - service: notify.mobile_seb
    data:
      title: >
        {{ expand('group.required_devices') | selectattr('state', 'eq', 'not_home') | list | count }} appareil(s) déconnecté(s)
      message: >
        Appareil(s) déconnecté(s) : {{ expand('group.required_devices') | selectattr('state', 'eq', 'not_home') | map(attribute='name') | join(', ') }}
  mode: single
################################################################################

################################################################################
- id: required_devices_alert_end
  alias: System - Notification - Network device alerte (end)
  description: Notification appareil deconnecté - Fin
  trigger:
  - platform: state
    entity_id: group.required_devices
    to: 'home'
  condition: []
  action:
  - service: persistent_notification.dismiss
    data: 
      notification_id: required_devices_alert
  mode: single
################################################################################
