---
### Monitor system ###

automation:
################################################################################
- id: system_notification_new_device
  alias: 'System - Notification - New Device'
  # initial_state: 'on'
  trigger:
    - platform: event
      event_type: device_tracker_new_device
  action:
    - service: notify.mobile_seb
      data_template:
        message: >
          Home Assistant a découvert un nouvel appareil:
          {{trigger.event.data.entity_id}}
        title: Nouvel appareil
################################################################################
- id: system_notification_restart
  alias: 'System - Notification - Home Assistant Restart'
  #initial_state: 'off'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: notify.mobile_seb
    data:
      message: 'Home Assistant a redémarré.'
################################################################################
